/* Autogenerated from config: jupiter */
#ifndef JUPITER_GENERATED_H
#define JUPITER_GENERATED_H

#include <stdint.h>

typedef int8_t s8;
typedef uint8_t u8;
typedef int16_t s16;
typedef uint16_t u16;
typedef int32_t s32;
typedef uint32_t u32;

#pragma pack(push, 1)

/* INST_CMN_WMT: WMT */
/* Total length: 28 bytes (0x001c) */
typedef struct INST_CMN_WMT {
    u8  SW;            // len:    1 @ 0x0000, Wave Switch
    u8  WAV_GTYPE;     // len:    1 @ 0x0001, Wave Group Type
    u16 WAV_GID;       // len:    2 @ 0x0002, Wave Group ID
    u16 WAV_NUM_L;     // len:    2 @ 0x0004, Wave Number L
    u16 WAV_NUM_R;     // len:    2 @ 0x0006, Wave Number R
    u8  WAV_GAIN;      // len:    1 @ 0x0008, Wave Gain
    u8  FXM_SW;        // len:    1 @ 0x0009, Wave FXM Switch
    u8  FXM_COLOR;     // len:    1 @ 0x000a, Wave FXM Color
    u8  FXM_DEPTH;     // len:    1 @ 0x000b, Wave FXM Depth
    s8  PIT_CRS;       // len:    1 @ 0x000c, Wave Coarse Tune
    s8  PIT_FINE;      // len:    1 @ 0x000d, Wave Fine Tune
    s8  PAN;           // len:    1 @ 0x000e, Wave Pan
    u8  PAN_RND_SW;    // len:    1 @ 0x000f, Wave Random Pan Sw
    u8  PAN_ALT_SW;    // len:    1 @ 0x0010, Wave Alternate Pan Sw
    u8  LEVEL;         // len:    1 @ 0x0011, Wave Level
    u8  PADDING1;      // len:    1 @ 0x0012, __padding
    u8  DELAY_MODE;    // len:    1 @ 0x0013, Delay Mode
    u8  DLY_TIME_SYNC; // len:    1 @ 0x0014, DelayTime Sync
    u8  DLY_TIME_NOTE; // len:    1 @ 0x0015, DelayTime (note)
    u16 DLY_TIME;      // len:    2 @ 0x0016, DelayTime
    u8  VRANGE_LO;     // len:    1 @ 0x0018, VeloRange Lower
    u8  VRANGE_UP;     // len:    1 @ 0x0019, VeloRange Upper
    u8  VFADE_LO;      // len:    1 @ 0x001a, VeloFade Lower
    u8  VFADE_UP;      // len:    1 @ 0x001b, VeloFade Upper
} INST_CMN_WMT;

/* INST_CMN: PCMRhythm Inst Common */
/* Total length: 152 bytes (0x0098) */
typedef struct INST_CMN {
    u8           NAME_1;         // len:    1 @ 0x0000, Name 1
    u8           reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8           CATEGORY;       // len:    1 @ 0x0010, Category
    u8           LEVEL;          // len:    1 @ 0x0011, Level
    u8           SRC_KEY;        // len:    1 @ 0x0012, Source Key
    s8           PIT_FINE;       // len:    1 @ 0x0013, Fine Tune
    u16          PIT_RND;        // len:    2 @ 0x0014, Random Pitch Depth
    u8           PAN_RND;        // len:    1 @ 0x0016, Random Pan Depth
    s8           PAN_ALT;        // len:    1 @ 0x0017, Alternate Pan Depth
    u8           ASGN_TYPE;      // len:    1 @ 0x0018, Assign Type
    u8           ENV_MODE;       // len:    1 @ 0x0019, Envelope Mode
    u8           WMT_VEL_CTRL;   // len:    1 @ 0x001a, WMT Velocity Control
    u8           PADDING1;       // len:    1 @ 0x001b, __padding
    INST_CMN_WMT WMT[4];         // len:  112 @ 0x001c, WMT
    u8           FILTER_TYPE;    // len:    1 @ 0x008c, TVF Filter Type
    u8           PADDING2;       // len:    1 @ 0x008d, __padding
    u16          CUTOFF;         // len:    2 @ 0x008e, TVF Cutoff Frequency
    u8           CUTOFF_VCRV;    // len:    1 @ 0x0090, TVF Cutoff Velocity Curve
    s8           CUTOFF_VSENS;   // len:    1 @ 0x0091, TVF Cutoff Velocity Sens
    u16          RESO;           // len:    2 @ 0x0092, TVF Resonance
    s8           RESO_VSENS;     // len:    1 @ 0x0094, TVF Resonance Velocity Sens
    u8           LEVEL_VCRV;     // len:    1 @ 0x0095, TVA Level Velocity Curve
    s8           LEVEL_VSENS;    // len:    1 @ 0x0096, TVA Level Velocity Sens
    u8           TEMPO_SYNC;     // len:    1 @ 0x0097, Wave Tempo Sync
} INST_CMN;

/* MDLCORE: Model Core Parameter */
/* Total length: 112 bytes (0x0070) */
typedef struct MDLCORE {
    u8  MODEL;       // len:    1 @ 0x0000, Model
    u8  LFOWAVE;     // len:    1 @ 0x0001, LFO WAVE FORM
    u16 LFORATE;     // len:    2 @ 0x0002, LFO RATE
    u16 LFODLY;      // len:    2 @ 0x0004, LFO DELAY TIME
    s8  OSC1MOD;     // len:    1 @ 0x0006, OSC1 MOD
    s8  OSC1PENV;    // len:    1 @ 0x0007, OSC1 PITCH ENV DEPTH
    u8  OSC1DEST;    // len:    1 @ 0x0008, OSC1 DEST SELECT
    u8  OSC1ENVS;    // len:    1 @ 0x0009, OSC1 ENVT SELECT
    u16 OSC1WAVE;    // len:    2 @ 0x000a, OSC1 WAVE FORM
    u8  OSC1FEET;    // len:    1 @ 0x000c, OSC1 FEET
    s8  OSC1COARSE;  // len:    1 @ 0x000d, OSC1 COARSE TUNE
    s8  OSC1FINE;    // len:    1 @ 0x000e, OSC1 FINE TUNE
    u8  OSC1LOWFREQ; // len:    1 @ 0x000f, OSC1 LOW FREQ PITCH
    u8  OSC1MODE;    // len:    1 @ 0x0010, OSC1 MODE
    s8  OSC1PWM;     // len:    1 @ 0x0011, OSC1 PWM DEPTH
    u8  OSC1PLSW;    // len:    1 @ 0x0012, OSC1 PULSE WIDTH
    u8  OSC1PLSM;    // len:    1 @ 0x0013, OSC1 PULSE WIDTH MODE
    s8  OSC2MOD;     // len:    1 @ 0x0014, OSC2 MOD
    s8  OSC2PENV;    // len:    1 @ 0x0015, OSC2 PITCH ENV DEPTH
    u16 OSC2WAVE;    // len:    2 @ 0x0016, OSC2 WAVE FORM
    u8  OSC2FEET;    // len:    1 @ 0x0018, OSC2 FEET
    s8  OSC2COARSE;  // len:    1 @ 0x0019, OSC2 COARSE TUNE
    s8  OSC2FINE;    // len:    1 @ 0x001a, OSC2 FINE TUNE
    u8  OSC2LOWFREQ; // len:    1 @ 0x001b, OSC2 LOW FREQ PITCH
    u8  OSC2MODE;    // len:    1 @ 0x001c, OSC2 MODE
    u8  OSC2PW;      // len:    1 @ 0x001d, OSC2 PULSE WIDTH
    s8  OSC3MOD;     // len:    1 @ 0x001e, OSC3 MOD
    s8  OSC3PENV;    // len:    1 @ 0x001f, OSC3 PITCH ENV DEPTH
    u16 OSC3WAVE;    // len:    2 @ 0x0020, OSC3 WAVE FORM
    u8  OSC3FEET;    // len:    1 @ 0x0022, OSC3 FEET
    s8  OSC3COARSE;  // len:    1 @ 0x0023, OSC3 COARSE TUNE
    s8  OSC3FINE;    // len:    1 @ 0x0024, OSC3 FINE TUNE
    u8  OSC3LOWFREQ; // len:    1 @ 0x0025, OSC3 LOW FREQ PITCH
    u8  OSC3MODE;    // len:    1 @ 0x0026, OSC3 MODE
    u8  NOISE;       // len:    1 @ 0x0027, NOISE
    u16 MODDPTH;     // len:    2 @ 0x0028, MOD DEPTH
    u8  MODMODE;     // len:    1 @ 0x002a, MOD MODE
    u8  MXROSC1;     // len:    1 @ 0x002b, OSC1 LEVEL
    u8  MXROSC2;     // len:    1 @ 0x002c, OSC2 LEVEL
    u8  MXROSC3;     // len:    1 @ 0x002d, OSC3 LEVEL
    u8  MXRNOISE;    // len:    1 @ 0x002e, NOISE LEVEL
    s8  MXRENVD;     // len:    1 @ 0x002f, MIXER ENV DEPTH
    u8  MXRENVS;     // len:    1 @ 0x0030, MIXER ENV SELECT
    u8  MXRDYNA;     // len:    1 @ 0x0031, MIXER DYNAMICS
    u8  FLTTYPE;     // len:    1 @ 0x0032, FILTER TYPE
    u8  FLTHPF2;     // len:    1 @ 0x0033, FILTER HPF STEP
    u16 FLTHPF1;     // len:    2 @ 0x0034, FILTER HPF
    u16 FLTFREQ;     // len:    2 @ 0x0036, FILTER FREQ
    u16 FLTRESO;     // len:    2 @ 0x0038, FILTER RESO
    s16 FLTENVD;     // len:    2 @ 0x003a, FILTER ENV DEPTH
    u8  FLTENVS;     // len:    1 @ 0x003c, FILTER ENV SELECT
    u8  FLTSLOPE;    // len:    1 @ 0x003d, FILTER SLOPE
    s16 FLTKYBD;     // len:    2 @ 0x003e, FILTER KEY FOLLOW
    s8  FLTMOD;      // len:    1 @ 0x0040, FILTER MOD
    u8  PADDING1;    // len:    1 @ 0x0041, __padding
    u8  AMPLVL;      // len:    1 @ 0x0042, AMP LEVEL
    s8  AMPMOD1;     // len:    1 @ 0x0043, AMP MOD
    u8  AMPMOD2;     // len:    1 @ 0x0044, AMP MOD STEP
    u8  AMPENVS;     // len:    1 @ 0x0045, AMP ENV SELECT
    u16 ENV1A;       // len:    2 @ 0x0046, ENV1 ATTACK
    u16 ENV1D;       // len:    2 @ 0x0048, ENV1 DECAY
    u16 ENV1S;       // len:    2 @ 0x004a, ENV1 SUSTAIN
    u16 ENV1R;       // len:    2 @ 0x004c, ENV1 RELEASE
    s8  ENV1KYBD1;   // len:    1 @ 0x004e, ENV1 KEY FOLLOW
    u8  ENV1KYBD2;   // len:    1 @ 0x004f, ENV1 KEY FOLLOW STEP
    u16 ENV2A;       // len:    2 @ 0x0050, ENV2 ATTACK
    u16 ENV2D;       // len:    2 @ 0x0052, ENV2 DECAY
    u16 ENV2S;       // len:    2 @ 0x0054, ENV2 SUSTAIN
    u16 ENV2R;       // len:    2 @ 0x0056, ENV2 RELEASE
    u8  ENV2MODE;    // len:    1 @ 0x0058, ENV2 MODE
    s8  ENV2KYBD1;   // len:    1 @ 0x0059, ENV2 KEY FOLLOW
    u8  ENV2KYBD2;   // len:    1 @ 0x005a, ENV2 KEY FOLLOW STEP
    u8  DYNPTCH;     // len:    1 @ 0x005b, DYNAMICS PITCH
    u8  DYNFLTT;     // len:    1 @ 0x005c, DYNAMICS FILTER
    u8  DYNAMP;      // len:    1 @ 0x005d, DYNAMICS AMP
    u8  PCHDRFT;     // len:    1 @ 0x005e, PITCH DRIFT
    u8  BNDPTCH2;    // len:    1 @ 0x005f, BENDER PITCH DEPTH STEP
    s8  BNDFLT;      // len:    1 @ 0x0060, BENDER FILTER DEPTH
    s8  BNDLFO;      // len:    1 @ 0x0061, MODULATION LFO DEPTH
    u16 BNDPTCH1;    // len:    2 @ 0x0062, BENDER PITCH DEPTH
    u16 PTATIME;     // len:    2 @ 0x0064, PORTAMENT TIME
    u8  PTAMODE;     // len:    1 @ 0x0066, PORTAMENT MODE
    u8  KBDMODE;     // len:    1 @ 0x0067, KEY MODE
    u8  EXPAND;      // len:    1 @ 0x0068, PARAMETER EXPANSION SWITCH
    u8  CONDITION;   // len:    1 @ 0x0069, CONDITION
    u8  PTACRV;      // len:    1 @ 0x006a, PORTAMENT CURVE TYPE
    s8  AFT_LFO;     // len:    1 @ 0x006b, AFTER TOUCH SENS LFO
    s8  AFT_FREQ;    // len:    1 @ 0x006c, AFTER TOUCH SENS FREQ
    s8  AFT_LEV;     // len:    1 @ 0x006d, AFTER TOUCH SENS LEVEL
    u16 PADDING2;    // len:    2 @ 0x006e, __padding
} MDLCORE;

/* MDLJD800COM: JD-800 Model Common */
/* Total length: 44 bytes (0x002c) */
typedef struct MDLJD800COM {
    u8  LEVEL;        // len:    1 @ 0x0000, Level
    u8  KEYA_RNG_LO;  // len:    1 @ 0x0001, Key Range A Low
    u8  KEYA_RNG_HI;  // len:    1 @ 0x0002, Key Range A High
    u8  KEYB_RNG_LO;  // len:    1 @ 0x0003, Key Range B Low
    u8  KEYB_RNG_HI;  // len:    1 @ 0x0004, Key Range B High
    u8  KEYC_RNG_LO;  // len:    1 @ 0x0005, Key Range C Low
    u8  KEYC_RNG_HI;  // len:    1 @ 0x0006, Key Range C High
    u8  KEYD_RNG_LO;  // len:    1 @ 0x0007, Key Range D Low
    u8  KEYD_RNG_HI;  // len:    1 @ 0x0008, Key Range D High
    u8  BND_RNG_DW;   // len:    1 @ 0x0009, Bender Range Down
    u8  BND_RNG_UP;   // len:    1 @ 0x000a, Bender Range Up
    u8  AFT_BEND;     // len:    1 @ 0x000b, After Touch Bend Sens
    u8  SOLO_SW;      // len:    1 @ 0x000c, Solo Switch
    u8  LEGATO_SW;    // len:    1 @ 0x000d, Solo Legato Switch
    u8  PORT_SW;      // len:    1 @ 0x000e, Portamento Switch
    u8  PORT_MODE;    // len:    1 @ 0x000f, Portamento Mode
    u8  PORT_TIME;    // len:    1 @ 0x0010, Portamento Time
    u8  EQ_MID_Q;     // len:    1 @ 0x0011, EQ Mid Q
    u16 EQ_LO_F;      // len:    2 @ 0x0012, EQ Low Frequency
    u16 EQ_MID_F;     // len:    2 @ 0x0014, EQ Mid Frequency
    u16 EQ_HI_F;      // len:    2 @ 0x0016, EQ High Frequency
    s16 EQ_LO_G;      // len:    2 @ 0x0018, EQ Low Gain
    s16 EQ_MID_G;     // len:    2 @ 0x001a, EQ Mid Gain
    s16 EQ_HI_G;      // len:    2 @ 0x001c, EQ High Gain
    u8  EQ_SW;        // len:    1 @ 0x001e, EQ Switch
    u8  UNISON;       // len:    1 @ 0x001f, Unison Switch
    u8  PADDING1[12]; // len:   12 @ 0x0020, __padding
} MDLJD800COM;

/* MDLJD800FxB: JD-800 Model Group B Effect */
/* Total length: 32 bytes (0x0020) */
typedef struct MDLJD800FxB {
    u8  SEQUENCE;    // len:    1 @ 0x0000, Sequence
    u8  DLY_SW;      // len:    1 @ 0x0001, DL Switch
    u8  DLY_C_SYNC;  // len:    1 @ 0x0002, Delay Center (sync sw)
    u8  DLY_C_TIME;  // len:    1 @ 0x0003, Delay Center (time)
    u8  DLY_C_NOTE;  // len:    1 @ 0x0004, Delay Center (note)
    u8  DLY_L_SYNC;  // len:    1 @ 0x0005, Delay Left (sync sw)
    u8  DLY_L_TIME;  // len:    1 @ 0x0006, Delay Left (time)
    u8  DLY_L_NOTE;  // len:    1 @ 0x0007, Delay Left (note)
    u8  DLY_R_SYNC;  // len:    1 @ 0x0008, Delay Right (sync sw)
    u8  DLY_R_TIME;  // len:    1 @ 0x0009, Delay Right (time)
    u8  DLY_R_NOTE;  // len:    1 @ 0x000a, Delay Right (note)
    u8  DLY_C_LEV;   // len:    1 @ 0x000b, Center Level
    u8  DLY_L_LEV;   // len:    1 @ 0x000c, Left Level
    u8  DLY_R_LEV;   // len:    1 @ 0x000d, Right Level
    u8  DLY_FB;      // len:    1 @ 0x000e, Delay Feedback
    u8  CHO_SW;      // len:    1 @ 0x000f, Chorus Sw
    u8  CHO_RATE;    // len:    1 @ 0x0010, Chorus Rate
    u8  CHO_DEPTH;   // len:    1 @ 0x0011, Chorus Depth
    u8  CHO_DLY;     // len:    1 @ 0x0012, Chorus Delay
    u8  CHO_FB;      // len:    1 @ 0x0013, Chorus Feedback
    u8  CHO_LEV;     // len:    1 @ 0x0014, Chorus Level
    u8  REV_SW;      // len:    1 @ 0x0015, Reverb Sw
    u8  REV_TYPE;    // len:    1 @ 0x0016, Reverb Type
    u8  REV_DLY;     // len:    1 @ 0x0017, Reverb Pre Delay
    u8  REV_ER_LEV;  // len:    1 @ 0x0018, Reverb ER Lev
    u8  REV_HF_DAMP; // len:    1 @ 0x0019, Reverb HF Damp
    u8  REV_TIME;    // len:    1 @ 0x001a, Reverb Time
    u8  REV_LEV;     // len:    1 @ 0x001b, Reverb Level
    u8  BAL;         // len:    1 @ 0x001c, Balance
    u8  LEVEL;       // len:    1 @ 0x001d, Level
    u16 PADDING1;    // len:    2 @ 0x001e, __padding
} MDLJD800FxB;

/* MDLJD800PTL: JD-800 Model Partial */
/* Total length: 80 bytes (0x0050) */
typedef struct MDLJD800PTL {
    u8  PTL_SW;      // len:    1 @ 0x0000, Layer Partial Switch
    u8  ACT_SW;      // len:    1 @ 0x0001, Active Partial Switch
    u8  VELO_CRV;    // len:    1 @ 0x0002, Velocity Curve
    u8  HOLD_CTRL;   // len:    1 @ 0x0003, Hold Control Switch
    u8  LFO1_WAV;    // len:    1 @ 0x0004, LFO1:Waveform
    u8  LFO1_SYNC;   // len:    1 @ 0x0005, LFO1:Rate sync
    u8  LFO1_RATE;   // len:    1 @ 0x0006, LFO1:Rate
    u8  LFO1_NOTE;   // len:    1 @ 0x0007, LFO1:Rate nt
    u8  LFO1_DLY;    // len:    1 @ 0x0008, LFO1:Delay time
    s8  LFO1_FADE;   // len:    1 @ 0x0009, LFO1:Fade time
    u8  LFO1_OFST;   // len:    1 @ 0x000a, LFO1:Offset
    u8  LFO1_KEY;    // len:    1 @ 0x000b, LFO1:Key trig
    u8  LFO2_WAV;    // len:    1 @ 0x000c, LFO2:Waveform
    u8  LFO2_SYNC;   // len:    1 @ 0x000d, LFO2:Rate Sync
    u8  LFO2_RATE;   // len:    1 @ 0x000e, LFO2:Rate
    u8  LFO2_NOTE;   // len:    1 @ 0x000f, LFO2:Rate nt
    u8  LFO2_DLY;    // len:    1 @ 0x0010, LFO2:Delay Time
    s8  LFO2_FADE;   // len:    1 @ 0x0011, LFO2:Fade time
    u8  LFO2_OFST;   // len:    1 @ 0x0012, LFO2:Offset
    u8  LFO2_KEY;    // len:    1 @ 0x0013, LFO2:Key trig
    u16 WAV_NUM;     // len:    2 @ 0x0014, WG:Waveform
    u8  WAV_SRC;     // len:    1 @ 0x0016, WG:Wave source
    u8  WAV_GAIN;    // len:    1 @ 0x0017, WG:Wave gain
    s8  PIT_COARSE;  // len:    1 @ 0x0018, WG:Pitch coarse
    s8  PIT_FINE;    // len:    1 @ 0x0019, WG:Pitch fine
    u8  PIT_RND;     // len:    1 @ 0x001a, WG:Pitch random
    u8  PIT_KF;      // len:    1 @ 0x001b, WG:Pitch KF
    u8  BENDER_SW;   // len:    1 @ 0x001c, WG:Bender Sw
    u8  AFT_BEND_SW; // len:    1 @ 0x001d, WG:Atch bend sw
    s8  LFO1_DEP;    // len:    1 @ 0x001e, WG:LFO1 depth
    s8  LFO2_DEP;    // len:    1 @ 0x001f, WG:LFO2 depth
    s8  LEVER_SENS;  // len:    1 @ 0x0020, WG:Lever sens
    s8  AFT_SENS;    // len:    1 @ 0x0021, WG:Atch msens
    s8  PENV_VSENS;  // len:    1 @ 0x0022, Pitch Env Velocity Sens
    s8  PENV_T_VS;   // len:    1 @ 0x0023, Pitch Env Time Velocity Sens
    s8  PENV_T_KF;   // len:    1 @ 0x0024, Pitch Env Time Keyfollow
    s8  PENV_L0;     // len:    1 @ 0x0025, Pitch Env L0
    s8  PENV_L1;     // len:    1 @ 0x0026, Pitch Env L1
    s8  PENV_L2;     // len:    1 @ 0x0027, Pitch Env L2
    u8  PENV_T1;     // len:    1 @ 0x0028, Pitch Env T1
    u8  PENV_T2;     // len:    1 @ 0x0029, Pitch Env T2
    u8  PENV_T3;     // len:    1 @ 0x002a, Pitch Env T3
    u8  TVF_FLT;     // len:    1 @ 0x002b, TVF:Filter mode
    u8  TVF_CUTOFF;  // len:    1 @ 0x002c, TVF:Cutoff freq
    u8  TVF_RESO;    // len:    1 @ 0x002d, TVF:Resonance
    u8  TVF_KF;      // len:    1 @ 0x002e, TVF:Cutoff KF
    s8  TVF_AFT;     // len:    1 @ 0x002f, TVF:Atch sens
    u8  TVF_LFO;     // len:    1 @ 0x0030, TVF:LFO select
    s8  TVF_LFO_DEP; // len:    1 @ 0x0031, TVF:LFO depth
    s8  TVF_ENV_DEP; // len:    1 @ 0x0032, TVF:ENV depth
    s8  FENV_VSENS;  // len:    1 @ 0x0033, F-ENV:Velo sens
    s8  FENV_T_VS;   // len:    1 @ 0x0034, F-ENV:T vsens
    s8  FENV_T_KF;   // len:    1 @ 0x0035, F-ENV:Time KF
    u8  FENV_L1;     // len:    1 @ 0x0036, F-ENV:Level 1
    u8  FENV_L2;     // len:    1 @ 0x0037, F-ENV:Level 2
    u8  FENV_SUS;    // len:    1 @ 0x0038, F-ENV:Sus Level
    u8  FENV_L4;     // len:    1 @ 0x0039, F-ENV:Level 4
    u8  FENV_T1;     // len:    1 @ 0x003a, F-ENV:Time 1
    u8  FENV_T2;     // len:    1 @ 0x003b, F-ENV:Time 2
    u8  FENV_T3;     // len:    1 @ 0x003c, F-ENV:Time 3
    u8  FENV_T4;     // len:    1 @ 0x003d, F-ENV:Time 4
    u8  TVA_BS_DIR;  // len:    1 @ 0x003e, TVA Bias Direction
    u8  TVA_BS_KEY;  // len:    1 @ 0x003f, TVA Bias Point
    s8  TVA_BS_LVL;  // len:    1 @ 0x0040, TVA:Bias level
    u8  TVA_LEVEL;   // len:    1 @ 0x0041, TVA:Level
    s8  TVA_AFT;     // len:    1 @ 0x0042, TVA After Touch Sens
    u8  TVA_LFO;     // len:    1 @ 0x0043, TVA:LFO select
    s8  TVA_LFO_DEP; // len:    1 @ 0x0044, TVA:LFO depth
    s8  AENV_VSENS;  // len:    1 @ 0x0045, A-ENV:Velo sens
    s8  AENV_T_VS;   // len:    1 @ 0x0046, A-ENV:T vsens
    s8  AENV_T_KF;   // len:    1 @ 0x0047, A-ENV:Time KF
    u8  AENV_L1;     // len:    1 @ 0x0048, A-ENV:Level 1
    u8  AENV_L2;     // len:    1 @ 0x0049, A-ENV:Level 2
    u8  AENV_SUS;    // len:    1 @ 0x004a, A-ENV:Sus level
    u8  AENV_T1;     // len:    1 @ 0x004b, A-ENV:Time 1
    u8  AENV_T2;     // len:    1 @ 0x004c, A-ENV:Time 2
    u8  AENV_T3;     // len:    1 @ 0x004d, A-ENV:Time 3
    u8  AENV_T4;     // len:    1 @ 0x004e, A-ENV:Time 4
    u8  PADDING1;    // len:    1 @ 0x004f, __padding
} MDLJD800PTL;

/* MDLJPX_FENV: FENV */
/* Total length: 12 bytes (0x000c) */
typedef struct MDLJPX_FENV {
    u16 A;     // len:    2 @ 0x0000, FILTER ENV01$ ATTACK
    u16 D;     // len:    2 @ 0x0002, FILTER ENV01$ DECAY
    u16 S;     // len:    2 @ 0x0004, FILTER ENV01$ SUSTAIN
    u16 R;     // len:    2 @ 0x0006, FILTER ENV01$ RELEASE
    s16 DEPTH; // len:    2 @ 0x0008, FILTER ENV01$ DEPTH
    s8  VSENS; // len:    1 @ 0x000a, FILTER ENV01$ VELOCITY SENS
    s8  KYBD;  // len:    1 @ 0x000b, FILTER ENV01$ KEY FOLLOW
} MDLJPX_FENV;

/* MDLJPX_LFO: LFO */
/* Total length: 16 bytes (0x0010) */
typedef struct MDLJPX_LFO {
    u8  WAVE;        // len:    1 @ 0x0000, LFO01$ WAVE FORM
    u8  NOTE;        // len:    1 @ 0x0001, LFO01$ RATE (Note)
    u16 RATE;        // len:    2 @ 0x0002, LFO01$ RATE
    u16 DELAY;       // len:    2 @ 0x0004, LFO01$ DELAY TIME
    s8  DEPTH_P;     // len:    1 @ 0x0006, LFO01$ PITCH DEPTH
    s8  DEPTH_F;     // len:    1 @ 0x0007, LFO01$ FILTER DEPTH
    s8  DEPTH_A;     // len:    1 @ 0x0008, LFO01$ AMP DEPTH
    u8  DEST_P;      // len:    1 @ 0x0009, LFO01$ PITCH DESTINATION SELECT
    u8  SYNC;        // len:    1 @ 0x000a, LFO01$ SYNC SWITCH
    u8  KEY_TRG;     // len:    1 @ 0x000b, LFO01$ KEY TRIGGER
    s8  PAN_DEPTH;   // len:    1 @ 0x000c, LFO01$ PAN DEPTH
    u8  PADDING1[3]; // len:    3 @ 0x000d, __padding
} MDLJPX_LFO;

/* MDLJPX_OSC: OSC */
/* Total length: 12 bytes (0x000c) */
typedef struct MDLJPX_OSC {
    u8  WAVE;       // len:    1 @ 0x0000, OSC01$ WAVEFORM
    s8  COARSE;     // len:    1 @ 0x0001, OSC01$ COARSE TUNE
    s8  FINE;       // len:    1 @ 0x0002, OSC01$ FINE TUNE
    u8  LEVEL;      // len:    1 @ 0x0003, OSC01$ LEVEL
    u8  PW_PWM;     // len:    1 @ 0x0004, OSC01$ PW PWM
    u8  PW_MODE;    // len:    1 @ 0x0005, OSC01$ PW MODE
    u16 DELAY;      // len:    2 @ 0x0006, OSC01$ DELAY TIME
    u8  DELAY_SYNC; // len:    1 @ 0x0008, OSC01$ DELAY TIME SYNC
    u8  DELAY_NOTE; // len:    1 @ 0x0009, OSC01$ DELAY TIME (Note)
    s8  PAN;        // len:    1 @ 0x000a, OSC01$ PAN
    s8  PAN_ALT;    // len:    1 @ 0x000b, OSC01$ ALTERNATE PAN DEPTH
} MDLJPX_OSC;

/* MDLJPX_PENV: PENV */
/* Total length: 12 bytes (0x000c) */
typedef struct MDLJPX_PENV {
    u16 A;     // len:    2 @ 0x0000, PITCH ENV01$ ATTACK
    u16 D;     // len:    2 @ 0x0002, PITCH ENV01$ DECAY
    u16 S;     // len:    2 @ 0x0004, PITCH ENV01$ SUSTAIN
    u16 R;     // len:    2 @ 0x0006, PITCH ENV01$ RELEASE
    s8  DEPTH; // len:    1 @ 0x0008, PITCH ENV01$ DEPTH
    s8  VSENS; // len:    1 @ 0x0009, PITCH ENV01$ VELOCITY SENS
    u8  DEST;  // len:    1 @ 0x000a, PITCH ENV01$ DESTINATION SELECT
    s8  KYBD;  // len:    1 @ 0x000b, PITCH ENV01$ KEY FOLLOW
} MDLJPX_PENV;

/* MDLJPX: JUPITER-X OSC Parameter */
/* Total length: 108 bytes (0x006c) */
typedef struct MDLJPX {
    MDLJPX_OSC  OSC;           // len:   12 @ 0x0000, OSC
    MDLJPX_LFO  LFO;           // len:   16 @ 0x000c, LFO
    MDLJPX_PENV PENV;          // len:   12 @ 0x001c, PENV
    MDLJPX_FENV FENV;          // len:   12 @ 0x0028, FENV
    u16         FLT_FREQ;      // len:    2 @ 0x0034, FILTER CUTOFF FREQ
    u16         FLT_RESO;      // len:    2 @ 0x0036, FILTER RESONANCE
    u16         FLT_HPF;       // len:    2 @ 0x0038, FILTER HPF
    u8          FLT_SLOPE;     // len:    1 @ 0x003a, FILTER SLOPE
    u8          FLT_TYPE;      // len:    1 @ 0x003b, FILTER TYPE
    u8          FLT_KYBD;      // len:    1 @ 0x003c, FILTER KEY FOLLOW
    s8          FLT_VSENS;     // len:    1 @ 0x003d, FILTER VELOCITY SENS
    u16         AENV_A;        // len:    2 @ 0x003e, AMP ENV ATTACK
    u16         AENV_D;        // len:    2 @ 0x0040, AMP ENV DECAY
    u16         AENV_S;        // len:    2 @ 0x0042, AMP ENV SUSTAIN
    u16         AENV_R;        // len:    2 @ 0x0044, AMP ENV RELEASE
    s8          AENV_VSENS;    // len:    1 @ 0x0046, AMP ENV VELOCITY SENS
    s8          AENV_KYBD;     // len:    1 @ 0x0047, AMP ENV KEY FOLLOW
    u8          reserved_1[6]; // len:    6 @ 0x0048, implicit padding
    u8          PENVLINK;      // len:    1 @ 0x004e, PITCH ENV1/2 LINK SWITCH
    u8          FENVLINK;      // len:    1 @ 0x004f, FILTER ENV1/2 LINK SWITCH
    u8          AMP_LEVEL;     // len:    1 @ 0x0050, AMP LEVEL
    u8          reserved_2[2]; // len:    2 @ 0x0051, implicit padding
    u8          PTA_MODE;      // len:    1 @ 0x0053, PORTAMENT MODE
    u16         PTA_TIME;      // len:    2 @ 0x0054, PORTAMENT TIME
    u8          PTA_CRV;       // len:    1 @ 0x0056, PORTAMENT CURVE TYPE
    s8          AFT_LFO;       // len:    1 @ 0x0057, AFTER TOUCH SENS LFO
    s8          AFT_FREQ;      // len:    1 @ 0x0058, AFTER TOUCH SENS FREQ
    s8          AFT_LEV;       // len:    1 @ 0x0059, AFTER TOUCH SENS LEVEL
    s8          AFT_PITCH;     // len:    1 @ 0x005a, AFTER TOUCH SENS PITCH
    u8          BND_PTCH_UP;   // len:    1 @ 0x005b, BENDER PITCH DEPTH UP
    u8          BND_PTCH_DW;   // len:    1 @ 0x005c, BENDER PITCH DEPTH DOWN
    s8          BND_FLT;       // len:    1 @ 0x005d, BENDER FILTER DEPTH
    s8          BND_LFO;       // len:    1 @ 0x005e, MODULATION LFO DEPTH
    s8          BND_LFO_RATE;  // len:    1 @ 0x005f, MODULATION LFO RATE SENS
    u8          KBDMODE;       // len:    1 @ 0x0060, KEY MODE
    u8          PCHDRFT;       // len:    1 @ 0x0061, PITCH DRIFT
    u8          UNISON_DETUNE; // len:    1 @ 0x0062, UNISON DETUNE
    u8          CONDITION;     // len:    1 @ 0x0063, CONDITION
    u8          PADDING1[8];   // len:    8 @ 0x0064, __padding
} MDLJPX;

/* MDLSYN0: Model Synth Parameter Interface type0 */
/* Total length: 112 bytes (0x0070) */
typedef struct MDLSYN0 {
    u8  MODEL;       // len:    1 @ 0x0000, Model
    u8  LFOWAVE;     // len:    1 @ 0x0001, LFO WAVE FORM
    u16 LFORATE;     // len:    2 @ 0x0002, LFO RATE
    u16 LFODLY;      // len:    2 @ 0x0004, LFO DELAY TIME
    s8  OSC1MOD;     // len:    1 @ 0x0006, OSC1 MOD
    s8  OSC1PENV;    // len:    1 @ 0x0007, OSC1 PITCH ENV DEPTH
    u8  OSC1DEST;    // len:    1 @ 0x0008, OSC1 DEST SELECT
    u8  OSC1ENVS;    // len:    1 @ 0x0009, OSC1 ENVT SELECT
    u16 OSC1WAVE;    // len:    2 @ 0x000a, OSC1 WAVE FORM
    u8  OSC1FEET;    // len:    1 @ 0x000c, OSC1 FEET
    s8  OSC1COARSE;  // len:    1 @ 0x000d, OSC1 COARSE TUNE
    s8  OSC1FINE;    // len:    1 @ 0x000e, OSC1 FINE TUNE
    u8  OSC1LOWFREQ; // len:    1 @ 0x000f, OSC1 LOW FREQ PITCH
    u8  OSC1MODE;    // len:    1 @ 0x0010, OSC1 MODE
    s8  OSC1PWM;     // len:    1 @ 0x0011, OSC1 PWM DEPTH
    u8  OSC1PLSW;    // len:    1 @ 0x0012, OSC1 PULSE WIDTH
    u8  OSC1PLSM;    // len:    1 @ 0x0013, OSC1 PULSE WIDTH MODE
    s8  OSC2MOD;     // len:    1 @ 0x0014, OSC2 MOD
    s8  OSC2PENV;    // len:    1 @ 0x0015, OSC2 PITCH ENV DEPTH
    u16 OSC2WAVE;    // len:    2 @ 0x0016, OSC2 WAVE FORM
    u8  OSC2FEET;    // len:    1 @ 0x0018, OSC2 FEET
    s8  OSC2COARSE;  // len:    1 @ 0x0019, OSC2 COARSE TUNE
    s8  OSC2FINE;    // len:    1 @ 0x001a, OSC2 FINE TUNE
    u8  OSC2LOWFREQ; // len:    1 @ 0x001b, OSC2 LOW FREQ PITCH
    u8  OSC2MODE;    // len:    1 @ 0x001c, OSC2 MODE
    u8  OSC2PW;      // len:    1 @ 0x001d, OSC2 PULSE WIDTH
    s8  OSC3MOD;     // len:    1 @ 0x001e, OSC3 MOD
    s8  OSC3PENV;    // len:    1 @ 0x001f, OSC3 PITCH ENV DEPTH
    u16 OSC3WAVE;    // len:    2 @ 0x0020, OSC3 WAVE FORM
    u8  OSC3FEET;    // len:    1 @ 0x0022, OSC3 FEET
    s8  OSC3COARSE;  // len:    1 @ 0x0023, OSC3 COARSE TUNE
    s8  OSC3FINE;    // len:    1 @ 0x0024, OSC3 FINE TUNE
    u8  OSC3LOWFREQ; // len:    1 @ 0x0025, OSC3 LOW FREQ PITCH
    u8  OSC3MODE;    // len:    1 @ 0x0026, OSC3 MODE
    u8  NOISE;       // len:    1 @ 0x0027, NOISE
    u16 MODDPTH;     // len:    2 @ 0x0028, MOD DEPTH
    u8  MODMODE;     // len:    1 @ 0x002a, MOD MODE
    u8  MXROSC1;     // len:    1 @ 0x002b, OSC1 LEVEL
    u8  MXROSC2;     // len:    1 @ 0x002c, OSC2 LEVEL
    u8  MXROSC3;     // len:    1 @ 0x002d, OSC3 LEVEL
    u8  MXRNOISE;    // len:    1 @ 0x002e, NOISE LEVEL
    s8  MXRENVD;     // len:    1 @ 0x002f, MIXER ENV DEPTH
    u8  MXRENVS;     // len:    1 @ 0x0030, MIXER ENV SELECT
    u8  MXRDYNA;     // len:    1 @ 0x0031, MIXER DYNAMICS
    u8  FLTTYPE;     // len:    1 @ 0x0032, FILTER TYPE
    u8  FLTHPF2;     // len:    1 @ 0x0033, FILTER HPF STEP
    u16 FLTHPF1;     // len:    2 @ 0x0034, FILTER HPF
    u16 FLTFREQ;     // len:    2 @ 0x0036, FILTER FREQ
    u16 FLTRESO;     // len:    2 @ 0x0038, FILTER RESO
    s16 FLTENVD;     // len:    2 @ 0x003a, FILTER ENV DEPTH
    u8  FLTENVS;     // len:    1 @ 0x003c, FILTER ENV SELECT
    u8  FLTSLOPE;    // len:    1 @ 0x003d, FILTER SLOPE
    s16 FLTKYBD;     // len:    2 @ 0x003e, FILTER KEY FOLLOW
    s8  FLTMOD;      // len:    1 @ 0x0040, FILTER MOD
    u8  PADDING1;    // len:    1 @ 0x0041, __padding
    u8  AMPLVL;      // len:    1 @ 0x0042, AMP LEVEL
    s8  AMPMOD1;     // len:    1 @ 0x0043, AMP MOD
    u8  AMPMOD2;     // len:    1 @ 0x0044, AMP MOD STEP
    u8  AMPENVS;     // len:    1 @ 0x0045, AMP ENV SELECT
    u16 ENV1A;       // len:    2 @ 0x0046, ENV1 ATTACK
    u16 ENV1D;       // len:    2 @ 0x0048, ENV1 DECAY
    u16 ENV1S;       // len:    2 @ 0x004a, ENV1 SUSTAIN
    u16 ENV1R;       // len:    2 @ 0x004c, ENV1 RELEASE
    s8  ENV1KYBD1;   // len:    1 @ 0x004e, ENV1 KEY FOLLOW
    u8  ENV1KYBD2;   // len:    1 @ 0x004f, ENV1 KEY FOLLOW STEP
    u16 ENV2A;       // len:    2 @ 0x0050, ENV2 ATTACK
    u16 ENV2D;       // len:    2 @ 0x0052, ENV2 DECAY
    u16 ENV2S;       // len:    2 @ 0x0054, ENV2 SUSTAIN
    u16 ENV2R;       // len:    2 @ 0x0056, ENV2 RELEASE
    u8  ENV2MODE;    // len:    1 @ 0x0058, ENV2 MODE
    s8  ENV2KYBD1;   // len:    1 @ 0x0059, ENV2 KEY FOLLOW
    u8  ENV2KYBD2;   // len:    1 @ 0x005a, ENV2 KEY FOLLOW STEP
    u8  DYNPTCH;     // len:    1 @ 0x005b, DYNAMICS PITCH
    u8  DYNFLTT;     // len:    1 @ 0x005c, DYNAMICS FILTER
    u8  DYNAMP;      // len:    1 @ 0x005d, DYNAMICS AMP
    u8  PCHDRFT;     // len:    1 @ 0x005e, PITCH DRIFT
    u8  BNDPTCH2;    // len:    1 @ 0x005f, BENDER PITCH DEPTH STEP
    s8  BNDFLT;      // len:    1 @ 0x0060, BENDER FILTER DEPTH
    s8  BNDLFO;      // len:    1 @ 0x0061, MODULATION LFO DEPTH
    u16 BNDPTCH1;    // len:    2 @ 0x0062, BENDER PITCH DEPTH
    u16 PTATIME;     // len:    2 @ 0x0064, PORTAMENT TIME
    u8  PTAMODE;     // len:    1 @ 0x0066, PORTAMENT MODE
    u8  KBDMODE;     // len:    1 @ 0x0067, KEY MODE
    u8  EXPAND;      // len:    1 @ 0x0068, PARAMETER EXPANSION SWITCH
    u8  CONDITION;   // len:    1 @ 0x0069, CONDITION
    u8  PTACRV;      // len:    1 @ 0x006a, PORTAMENT CURVE TYPE
    s8  AFT_LFO;     // len:    1 @ 0x006b, AFTER TOUCH SENS LFO
    s8  AFT_FREQ;    // len:    1 @ 0x006c, AFTER TOUCH SENS FREQ
    s8  AFT_LEV;     // len:    1 @ 0x006d, AFTER TOUCH SENS LEVEL
    u16 PADDING2;    // len:    2 @ 0x006e, __padding
} MDLSYN0;

/* MDLVDN: Vocal Designer Model */
/* Total length: 32 bytes (0x0020) */
typedef struct MDLVDN {
    u8 MSTR_LVL;      // len:    1 @ 0x0000, Level
    u8 MIC_LVL;       // len:    1 @ 0x0001, Mic Direct Level
    u8 VOC_LVL;       // len:    1 @ 0x0002, Vocoder Level
    u8 ALGO;          // len:    1 @ 0x0003, Algorithm
    u8 CRR_TYPE;      // len:    1 @ 0x0004, Carrier Type
    u8 RSV_CRR_BASIC; // len:    1 @ 0x0005, Reserved
    u8 LEVEL;         // len:    1 @ 0x0006, Carrier Basic Level
    s8 PAN;           // len:    1 @ 0x0007, Carrier Basic Pan
    s8 PIT_CRS;       // len:    1 @ 0x0008, Carrier Basic Coarse Tune
    s8 PIT_FINE;      // len:    1 @ 0x0009, Carrier Basic Fine Tune
    s8 OCTAVE;        // len:    1 @ 0x000a, Carrier Basic Octave Shift
    u8 PADDING1[21];  // len:   21 @ 0x000b, __padding
} MDLVDN;

/* MFX: Block */
/* Total length: 84 bytes (0x0054) */
typedef struct MFX {
    u8  mfxType;        // len:    1 @ 0x0000, Type
    u8  mfxSwitch;      // len:    1 @ 0x0001, MFX Switch
    u8  choSend;        // len:    1 @ 0x0002, MFX Chorus Send Level
    u8  revSend;        // len:    1 @ 0x0003, MFX Reverb Send Level
    u8  ctrlSrc1;       // len:    1 @ 0x0004, MFX CtrlSrc 1
    s8  ctrlSens1;      // len:    1 @ 0x0005, MFX CtrlSens 1
    u8  ctrlSrc2;       // len:    1 @ 0x0006, MFX CtrlSrc 2
    s8  ctrlSens2;      // len:    1 @ 0x0007, MFX CtrlSens 2
    u8  ctrlSrc3;       // len:    1 @ 0x0008, MFX CtrlSrc 3
    s8  ctrlSens3;      // len:    1 @ 0x0009, MFX CtrlSens 3
    u8  ctrlSrc4;       // len:    1 @ 0x000a, MFX CtrlSrc 4
    s8  ctrlSens4;      // len:    1 @ 0x000b, MFX CtrlSens 4
    u8  ctrlAsgn_1;     // len:    1 @ 0x000c, MFX CtrlAsgn 1
    u8  reserved_1[3];  // len:    3 @ 0x000d, implicit padding
    s16 param_1;        // len:    2 @ 0x0010, MFX Parameter 1
    u8  reserved_2[62]; // len:   62 @ 0x0012, implicit padding
    u32 PADDING1;       // len:    4 @ 0x0050, __padding
} MFX;

/* PCMR_CMN: PCMRhythm Common */
/* Total length: 28 bytes (0x001c) */
typedef struct PCMR_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u16 PADDING1;         // len:    2 @ 0x0010, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Phrase Number
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    u16 PADDING2;         // len:    2 @ 0x0015, __padding
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x0017, Phrase Velo Rate
    s8  PHRASE_VEL_SHIFT; // len:    1 @ 0x0018, Phrase Velo Shift
    u8  PADDING3[3];      // len:    3 @ 0x0019, __padding
} PCMR_CMN;

/* PCMR_PTL: PCMRhythm Partial */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMR_PTL {
    u16 INST_NUM;      // len:    2 @ 0x0000, Inst Number
    u8  INST_GTYPE;    // len:    1 @ 0x0002, Inst Bank
    u8  PADDING1;      // len:    1 @ 0x0003, __padding
    u16 INST_GID;      // len:    2 @ 0x0004, Inst Group ID
    u8  LEVEL;         // len:    1 @ 0x0006, Level
    u8  PADDING2;      // len:    1 @ 0x0007, __padding
    s8  PAN;           // len:    1 @ 0x0008, Pan
    u8  CHO_SEND;      // len:    1 @ 0x0009, Chorus Send Level
    u8  REV_SEND;      // len:    1 @ 0x000a, Reverb Send Level
    u8  MUTE_GRP;      // len:    1 @ 0x000b, Mute Group
    u8  OUT_ASGN;      // len:    1 @ 0x000c, Output Assign
    s8  KEY_OFST;      // len:    1 @ 0x000d, Key Offset
    s8  PIT_FINE_OFST; // len:    1 @ 0x000e, Fine Tune Offset
    s8  CUTOFF_OFST;   // len:    1 @ 0x000f, TVF Cutoff Offset
    s8  RESO_OFST;     // len:    1 @ 0x0010, TVF Resonance Offset
    s8  TVA_ATK_OFST;  // len:    1 @ 0x0011, TVA Attack Time Offset
    s8  TVA_DCY_OFST;  // len:    1 @ 0x0012, TVA Decay Time Offset
    s8  TVA_REL_OFST;  // len:    1 @ 0x0013, TVA Release Time Offset
} PCMR_PTL;

/* PCMS_CMN: PCMSynth Common */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMS_CMN {
    u8 UNISON_SW;          // len:    1 @ 0x0000, Unison Switch
    u8 UNISON_SIZE;        // len:    1 @ 0x0001, Unison Size
    u8 UNISON_DETN;        // len:    1 @ 0x0002, Unison Detune
    u8 PADDING1;           // len:    1 @ 0x0003, __padding
    u8 BEND_RANGE_FINE_UP; // len:    1 @ 0x0004, Bend Range Fine Up
    u8 BEND_RANGE_FINE_DW; // len:    1 @ 0x0005, Bend Range Fine Down
    u8 RND_PIT_VAL;        // len:    1 @ 0x0006, Pitch Drift
    u8 RND_PIT_NUM;        // len:    1 @ 0x0007, Pitch Drift Cycle Number
    u8 CONDITION;          // len:    1 @ 0x0008, Condition
    u8 PADDING2[11];       // len:   11 @ 0x0009, __padding
} PCMS_CMN;

/* PCMS_PMT: PCMSynth PMT */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PMT {
    u8  STRUCT12;        // len:    1 @ 0x0000, Structure1-2
    u8  STRUCT34;        // len:    1 @ 0x0001, Structure3-4
    u16 PADDING1;        // len:    2 @ 0x0002, __padding
    u8  RING12_LEVEL;    // len:    1 @ 0x0004, RING1-2 Level
    u8  RING34_LEVEL;    // len:    1 @ 0x0005, RING3-4 Level
    u8  RING_OSC1_LEVEL; // len:    1 @ 0x0006, RING OSC1 Level
    u8  RING_OSC2_LEVEL; // len:    1 @ 0x0007, RING OSC2 Level
    u8  RING_OSC3_LEVEL; // len:    1 @ 0x0008, RING OSC3 Level
    u8  RING_OSC4_LEVEL; // len:    1 @ 0x0009, RING OSC4 Level
    u16 PADDING2;        // len:    2 @ 0x000a, __padding
    u16 XMOD12_DEPTH;    // len:    2 @ 0x000c, CrossMod1-2 Depth
    u16 XMOD34_DEPTH;    // len:    2 @ 0x000e, CrossMod3-4 Depth
    u8  XMOD_OSC1_LEVEL; // len:    1 @ 0x0010, CrossMod OSC1 Level
    u8  XMOD_OSC2_LEVEL; // len:    1 @ 0x0011, CrossMod OSC2 Level
    u8  XMOD_OSC3_LEVEL; // len:    1 @ 0x0012, CrossMod OSC3 Level
    u8  XMOD_OSC4_LEVEL; // len:    1 @ 0x0013, CrossMod OSC4 Level
    u8  PTL_PHS_LOCK;    // len:    1 @ 0x0014, Partial Phase Lock
    u8  XMOD2_12_DEPTH;  // len:    1 @ 0x0015, CrossMod2 1-2 Depth
    u8  XMOD2_34_DEPTH;  // len:    1 @ 0x0016, CrossMod2 3-4 Depth
    u8  PADDING3[13];    // len:   13 @ 0x0017, __padding
} PCMS_PMT;

/* PCMS_PTL: PCMSynth Partial */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PTL {
    u8  OSC_TYPE;         // len:    1 @ 0x0000, OSC Type
    u8  VA_FORM;          // len:    1 @ 0x0001, VA Waveform
    u16 SYNC_WAV_NUM;     // len:    2 @ 0x0002, PCM-Sync Wave Number
    u8  PW;               // len:    1 @ 0x0004, Pulse Width
    s8  PWM_DEPTH;        // len:    1 @ 0x0005, PWM Depth
    u8  SSAW_DETUNE;      // len:    1 @ 0x0006, SuperSAW Detune
    u8  CLICK_TYPE;       // len:    1 @ 0x0007, Click Type
    u16 HPF_CUTOFF;       // len:    2 @ 0x0008, HPF Cutoff
    u8  FILTER_TYPE;      // len:    1 @ 0x000a, Filter Type
    u8  FILTER_SLOPE;     // len:    1 @ 0x000b, Filter Slope
    u8  ADSR_ENV_SW;      // len:    1 @ 0x000c, ADSREnv Switch
    u8  FAT;              // len:    1 @ 0x000d, Fat
    u8  VCF_TYPE;         // len:    1 @ 0x000e, VCF Type
    u8  OSC_ATT;          // len:    1 @ 0x000f, OSC Attenuator
    u8  CUTOFF_KF_BP;     // len:    1 @ 0x0010, Cutoff Keyfollow Base Point
    u8  VA_INVERT_SW;     // len:    1 @ 0x0011, VA Waveform Invert Switch
    s8  FENV_FINE_DEPTH;  // len:    1 @ 0x0012, TVF Env Fine Depth
    u8  PENV_LFO_TRIG_SW; // len:    1 @ 0x0013, PENV LFO Trigger Switch
    u8  FENV_LFO_TRIG_SW; // len:    1 @ 0x0014, FENV LFO Trigger Switch
    u8  AENV_LFO_TRIG_SW; // len:    1 @ 0x0015, AENV LFO Trigger Switch
    u8  PITCH_DOWN_DEPTH; // len:    1 @ 0x0016, Pitch Down Depth
    u8  VCF_GC;           // len:    1 @ 0x0017, VCF Gain Correction
    u8  VA_INIT_PHASE;    // len:    1 @ 0x0018, VA Init Phase
    u8  PADDING1[11];     // len:   11 @ 0x0019, __padding
} PCMS_PTL;

/* PCMT_CMN: PCMTone Common */
/* Total length: 64 bytes (0x0040) */
typedef struct PCMT_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u8  CATEGORY;         // len:    1 @ 0x0010, Category
    u8  PADDING1;         // len:    1 @ 0x0011, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Reserved
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    s8  PAN;              // len:    1 @ 0x0015, Pan
    u16 PADDING2;         // len:    2 @ 0x0016, __padding
    u8  PRIORITY;         // len:    1 @ 0x0018, Priority
    s8  PIT_CRS;          // len:    1 @ 0x0019, Tone Coarse Tune
    s8  PIT_FINE;         // len:    1 @ 0x001a, Tone Fine Tune
    s8  OCTAVE;           // len:    1 @ 0x001b, Octave Shift
    u8  STRETCH;          // len:    1 @ 0x001c, Stretch Tune Depth
    u8  ANALOG_FEEL;      // len:    1 @ 0x001d, Analog Feel
    u8  MONO_POLY;        // len:    1 @ 0x001e, Mono/Poly
    u8  LEGATO_SW;        // len:    1 @ 0x001f, Legato Switch
    u8  RETRIG_INTVL;     // len:    1 @ 0x0020, Legato Retrigger Interval
    u8  PORTA_SW;         // len:    1 @ 0x0021, Portamento Switch
    u8  PORTA_MODE;       // len:    1 @ 0x0022, Portamento Mode
    u8  PORTA_TYPE;       // len:    1 @ 0x0023, Portamento Type
    u8  PADDING3;         // len:    1 @ 0x0024, __padding
    u8  PORTA_START;      // len:    1 @ 0x0025, Portamento Start
    u16 PORTA_TIME;       // len:    2 @ 0x0026, Portamento Time
    u8  BEND_RANGE_UP;    // len:    1 @ 0x0028, Bend Range Up
    u8  BEND_RANGE_DW;    // len:    1 @ 0x0029, Bend Range Down
    u8  BEND_MODE;        // len:    1 @ 0x002a, Bend Mode
    u8  SOFT_LEVEL_SENS;  // len:    1 @ 0x002b, Soft Level Sens
    u8  PHRASE_OCT;       // len:    1 @ 0x002c, Reserved
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x002d, Reserved
    u8  PHRASE_VEL_SHIFT; // len:    1 @ 0x002e, Reserved
    u8  SYMP_DEPTH;       // len:    1 @ 0x002f, Reserved
    u8  PORTA_CRV;        // len:    1 @ 0x0030, Portamento Curve Type
    u8  PTL_LFO_LOCK;     // len:    1 @ 0x0031, Partial LFO Phase Lock
    u8  PADDING4[14];     // len:   14 @ 0x0032, __padding
} PCMT_CMN;

/* PCMT_PMT_PMT: PMT */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PMT_PMT {
    u8 PTL_SW;      // len:    1 @ 0x0000, Partial Switch
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
    u8 KRANGE_LO;   // len:    1 @ 0x0004, KeyRange Lower
    u8 KRANGE_UP;   // len:    1 @ 0x0005, KeyRange Upper
    u8 KFADE_LO;    // len:    1 @ 0x0006, KeyFade Lower
    u8 KFADE_UP;    // len:    1 @ 0x0007, KeyFade Upper
    u8 VRANGE_LO;   // len:    1 @ 0x0008, VeloRange Lower
    u8 VRANGE_UP;   // len:    1 @ 0x0009, VeloRange Upper
    u8 VFADE_LO;    // len:    1 @ 0x000a, VeloFade Lower
    u8 VFADE_UP;    // len:    1 @ 0x000b, VeloFade Upper
} PCMT_PMT_PMT;

/* PCMT_PMT: PCMTone PartialMixTable */
/* Total length: 52 bytes (0x0034) */
typedef struct PCMT_PMT {
    u8           VEL_CTRL;      // len:    1 @ 0x0000, Velocity Control
    u8           PMT_LEVEL_CRV; // len:    1 @ 0x0001, PMT Level Curve
    u16          PADDING1;      // len:    2 @ 0x0002, __padding
    PCMT_PMT_PMT PMT[4];        // len:   48 @ 0x0004, PMT
} PCMT_PMT;

/* PCMT_PTL_MCTL: Matrix Control */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PTL_MCTL {
    u8 SRC;         // len:    1 @ 0x0000, Source
    u8 DST1;        // len:    1 @ 0x0001, Destination 1
    s8 SENS1;       // len:    1 @ 0x0002, Sens 1
    u8 DST2;        // len:    1 @ 0x0003, Destination 2
    s8 SENS2;       // len:    1 @ 0x0004, Sens 2
    u8 DST3;        // len:    1 @ 0x0005, Destination 3
    s8 SENS3;       // len:    1 @ 0x0006, Sens 3
    u8 DST4;        // len:    1 @ 0x0007, Destination 4
    s8 SENS4;       // len:    1 @ 0x0008, Sens 4
    u8 PADDING1[3]; // len:    3 @ 0x0009, __padding
} PCMT_PTL_MCTL;

/* PCMT_PTL: PCMTone Partial */
/* Total length: 124 bytes (0x007c) */
typedef struct PCMT_PTL {
    u8            LEVEL;         // len:    1 @ 0x0000, Level
    u8            PADDING1;      // len:    1 @ 0x0001, __padding
    s8            PIT_CRS;       // len:    1 @ 0x0002, Coarse Tune
    s8            PIT_FINE;      // len:    1 @ 0x0003, Fine Tune
    u16           PIT_RND;       // len:    2 @ 0x0004, Random Pitch Depth
    s8            PAN;           // len:    1 @ 0x0006, Pan
    s8            PAN_KF;        // len:    1 @ 0x0007, Pan Keyfollow
    u8            PAN_RND;       // len:    1 @ 0x0008, Random Pan Depth
    s8            PAN_ALT;       // len:    1 @ 0x0009, Alternate Pan Depth
    u8            ENV_MODE;      // len:    1 @ 0x000a, Envelope Mode
    u8            DELAY_MODE;    // len:    1 @ 0x000b, Delay Mode
    u8            DLY_TIME_SYNC; // len:    1 @ 0x000c, DelayTime Sync
    u8            DLY_TIME_NOTE; // len:    1 @ 0x000d, DelayTime (note)
    u16           DLY_TIME;      // len:    2 @ 0x000e, DelayTime
    u8            CHO_SEND;      // len:    1 @ 0x0010, Chorus Send Level
    u8            REV_SEND;      // len:    1 @ 0x0011, Reverb Send Level
    u8            RX_BEND;       // len:    1 @ 0x0012, Receive Bender
    u8            RX_EXPR;       // len:    1 @ 0x0013, Receive Expression
    u8            RX_HOLD;       // len:    1 @ 0x0014, Receive Hold-1
    u8            REDAMP_SW;     // len:    1 @ 0x0015, Redamper Switch
    u8            OUT_ASGN;      // len:    1 @ 0x0016, Output Assign
    u8            WAV_GTYPE;     // len:    1 @ 0x0017, Wave Group Type
    u16           WAV_GID;       // len:    2 @ 0x0018, Wave Group ID
    u16           WAV_NUM_L;     // len:    2 @ 0x001a, Wave Number L
    u16           WAV_NUM_R;     // len:    2 @ 0x001c, Wave Number R
    u8            WAV_GAIN;      // len:    1 @ 0x001e, Gain
    u8            FXM_SW;        // len:    1 @ 0x001f, FXM Switch
    u8            FXM_COLOR;     // len:    1 @ 0x0020, FXM Color
    u8            FXM_DEPTH;     // len:    1 @ 0x0021, FXM Depth
    s16           PIT_KF;        // len:    2 @ 0x0022, Pitch Keyfollow
    u8            SOFT_EQ_SENS;  // len:    1 @ 0x0024, Soft EQ Sens
    u8            FILTER_TYPE;   // len:    1 @ 0x0025, TVF Filter Type
    u16           PADDING2;      // len:    2 @ 0x0026, __padding
    u16           CUTOFF;        // len:    2 @ 0x0028, TVF Cutoff Frequency
    s16           CUTOFF_KF;     // len:    2 @ 0x002a, TVF Cutoff Keyfollow
    u8            CUTOFF_VCRV;   // len:    1 @ 0x002c, TVF Cutoff Velocity Curve
    s8            CUTOFF_VSENS;  // len:    1 @ 0x002d, TVF Cutoff Velocity Sens
    u16           RESO;          // len:    2 @ 0x002e, TVF Resonance
    s8            RESO_VSENS;    // len:    1 @ 0x0030, TVF Resonance Velocity Sens
    s8            BIAS_LEVEL;    // len:    1 @ 0x0031, Bias Level
    u8            BIAS_POS;      // len:    1 @ 0x0032, Bias Position
    u8            BIAS_DIR;      // len:    1 @ 0x0033, Bias Direction
    u8            LEVEL_VCRV;    // len:    1 @ 0x0034, TVA Level Velocity Curve
    s8            LEVEL_VSENS;   // len:    1 @ 0x0035, TVA Level Velocity Sens
    s8            PENV_TKF;      // len:    1 @ 0x0036, Pitch Env Time Keyfollow
    s8            FENV_TKF;      // len:    1 @ 0x0037, TVF Env Time Keyfollow
    s8            AENV_TKF;      // len:    1 @ 0x0038, TVA Env Time Keyfollow
    s8            VIB_PIT_SENS;  // len:    1 @ 0x0039, Vibrato Pitch Sens
    s8            VIB_CUT_SENS;  // len:    1 @ 0x003a, Vibrato Cutoff Sens
    s8            VIB_AMP_SENS;  // len:    1 @ 0x003b, Vibrato Level Sens
    PCMT_PTL_MCTL MCTL[4];       // len:   48 @ 0x003c, Matrix Control
    u8            DAMP_FREE;     // len:    1 @ 0x006c, Damper Free Note
    u8            STEREO_WIDTH;  // len:    1 @ 0x006d, Stereo Width
    s8            STEREO_DETN;   // len:    1 @ 0x006e, Stereo Detune
    s8            DF_DCY_OFST;   // len:    1 @ 0x006f, Damper Free Decay Offset
    u8            TEMPO_SYNC;    // len:    1 @ 0x0070, Wave Tempo Sync
    u8            PADDING3[11];  // len:   11 @ 0x0071, __padding
} PCMT_PTL;

/* PTL_AENV: Partial TVA Envelope */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_AENV {
    s8  T1_VSENS; // len:    1 @ 0x0000, TVA Env Time1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0001, TVA Env Time4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0002, TVA Env Time1
    u16 T2;       // len:    2 @ 0x0004, TVA Env Time2
    u16 T3;       // len:    2 @ 0x0006, TVA Env Time3
    u16 T4;       // len:    2 @ 0x0008, TVA Env Time4
    u16 L1;       // len:    2 @ 0x000a, TVA Env Level1
    u16 L2;       // len:    2 @ 0x000c, TVA Env Level2
    u16 L3;       // len:    2 @ 0x000e, TVA Env Level3
} PTL_AENV;

/* PTL_EQ: Partial EQ */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_EQ {
    s16 LO_GAIN;  // len:    2 @ 0x0000, EQ Low Gain
    s16 MID_GAIN; // len:    2 @ 0x0002, EQ Mid Gain
    s16 HI_GAIN;  // len:    2 @ 0x0004, EQ High Gain
    u16 LO_FREQ;  // len:    2 @ 0x0006, EQ Low Frequency
    u16 MID_FREQ; // len:    2 @ 0x0008, EQ Mid Frequency
    u16 HI_FREQ;  // len:    2 @ 0x000a, EQ High Frequency
    u8  MID_Q;    // len:    1 @ 0x000c, EQ Mid Q
    u8  SW;       // len:    1 @ 0x000d, EQ Switch
    u16 PADDING1; // len:    2 @ 0x000e, __padding
} PTL_EQ;

/* PTL_FENV: Partial TVF Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_FENV {
    s8  DEPTH;    // len:    1 @ 0x0000, TVF Env Depth
    u8  VCRV;     // len:    1 @ 0x0001, TVF Env Velocity Curve
    s8  VSENS;    // len:    1 @ 0x0002, TVF Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0003, TVF Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0004, TVF Env T4 Velocity Sens
    u8  PADDING1; // len:    1 @ 0x0005, __padding
    u16 T1;       // len:    2 @ 0x0006, TVF Env Time1
    u16 T2;       // len:    2 @ 0x0008, TVF Env Time2
    u16 T3;       // len:    2 @ 0x000a, TVF Env Time3
    u16 T4;       // len:    2 @ 0x000c, TVF Env Time4
    u16 L0;       // len:    2 @ 0x000e, TVF Env Level0
    u16 L1;       // len:    2 @ 0x0010, TVF Env Level1
    u16 L2;       // len:    2 @ 0x0012, TVF Env Level2
    u16 L3;       // len:    2 @ 0x0014, TVF Env Level3
    u16 L4;       // len:    2 @ 0x0016, TVF Env Level4
} PTL_FENV;

/* PTL_LFO_LFO: LFO */
/* Total length: 52 bytes (0x0034) */
typedef struct PTL_LFO_LFO {
    u8  FORM;           // len:    1 @ 0x0000, Waveform
    u8  RATE_SYNC;      // len:    1 @ 0x0001, Rate Sync
    u8  RATE_NOTE;      // len:    1 @ 0x0002, Rate (note)
    u8  STEP_MAX;       // len:    1 @ 0x0003, Step Size
    u16 RATE;           // len:    2 @ 0x0004, Rate
    s8  OFST;           // len:    1 @ 0x0006, Offset
    u8  RATE_DETN;      // len:    1 @ 0x0007, Rate Detune
    u16 DELAY;          // len:    2 @ 0x0008, Delay Time
    s8  DELAY_KF;       // len:    1 @ 0x000a, Delay Time Keyfolow
    u8  FADE_MODE;      // len:    1 @ 0x000b, Fade Mode
    u16 FADE;           // len:    2 @ 0x000c, Fade Time
    u8  KEY_TRIG;       // len:    1 @ 0x000e, Key Trigger
    s8  PIT_DEPTH;      // len:    1 @ 0x000f, Pitch Depth
    s8  TVF_DEPTH;      // len:    1 @ 0x0010, TVF Depth
    s8  TVA_DEPTH;      // len:    1 @ 0x0011, TVA Depth
    s8  PAN_DEPTH;      // len:    1 @ 0x0012, PAN Depth
    u8  PHASE_POS;      // len:    1 @ 0x0013, Phase Position
    s8  STEP_1;         // len:    1 @ 0x0014, Step 1
    u8  reserved_1[15]; // len:   15 @ 0x0015, implicit padding
    u8  STEP_CURVE_1;   // len:    1 @ 0x0024, Step Curve 1
    u8  reserved_2[15]; // len:   15 @ 0x0025, trailing padding
} PTL_LFO_LFO;

/* PTL_LFO: Partial LFO */
/* Total length: 104 bytes (0x0068) */
typedef struct PTL_LFO {
    PTL_LFO_LFO LFO[2]; // len:  104 @ 0x0000, LFO
} PTL_LFO;

/* PTL_PENV: Partial Pitch Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_PENV {
    s8  DEPTH;    // len:    1 @ 0x0000, Pitch Env Depth
    s8  VSENS;    // len:    1 @ 0x0001, Pitch Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0002, Pitch Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0003, Pitch Env T4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0004, Pitch Env Time1
    u16 T2;       // len:    2 @ 0x0006, Pitch Env Time2
    u16 T3;       // len:    2 @ 0x0008, Pitch Env Time3
    u16 T4;       // len:    2 @ 0x000a, Pitch Env Time4
    s16 L0;       // len:    2 @ 0x000c, Pitch Env Level0
    s16 L1;       // len:    2 @ 0x000e, Pitch Env Level1
    s16 L2;       // len:    2 @ 0x0010, Pitch Env Level2
    s16 L3;       // len:    2 @ 0x0012, Pitch Env Level3
    s16 L4;       // len:    2 @ 0x0014, Pitch Env Level4
    u8  VCRV;     // len:    1 @ 0x0016, Pitch Env Velocity Curve
    u8  PADDING1; // len:    1 @ 0x0017, __padding
} PTL_PENV;

/* RCMP: System RhythmComp */
/* Total length: 8 bytes (0x0008) */
typedef struct RCMP {
    u8 SW;        // len:    1 @ 0x0000, Comp Switch
    u8 ATTCK;     // len:    1 @ 0x0001, Comp Attack Time
    u8 RELEASE;   // len:    1 @ 0x0002, Comp Release Time
    s8 THRESHOLD; // len:    1 @ 0x0003, Comp Threshold
    u8 RATIO;     // len:    1 @ 0x0004, Comp Ratio
    u8 KNEE;      // len:    1 @ 0x0005, Comp Knee
    s8 POSTGAIN;  // len:    1 @ 0x0006, Comp Output Gain
    u8 OUT_ASGN;  // len:    1 @ 0x0007, Comp Output Assign
} RCMP;

/* TONECOM: ToneCom */
/* Total length: 20 bytes (0x0014) */
typedef struct TONECOM {
    u8  NAME_1;         // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  CATEGORY;       // len:    1 @ 0x0010, Category
    u8  RSRV8;          // len:    1 @ 0x0011, Reserved
    u16 RSRV16;         // len:    2 @ 0x0012, Reserved
} TONECOM;

/* MdlJD800: Group */
/* Total length: 500 bytes (0x01f4) */
typedef struct MdlJD800 {
    MDLJD800COM MDLJD800COM;    // len:   44 @ 0x0000, MDLJD800COM
    MDLJD800PTL MDLJD800PTL[4]; // len:  320 @ 0x002c, MDLJD800PTL
    MFX         MFX;            // len:   84 @ 0x016c, MFX
    MDLJD800FxB MDLJD800FxB;    // len:   32 @ 0x01c0, MDLJD800FxB
    TONECOM     TONECOM;        // len:   20 @ 0x01e0, TONECOM
} MdlJD800;

/* MdlSynPrm0: Group */
/* Total length: 216 bytes (0x00d8) */
typedef struct MdlSynPrm0 {
    MDLSYN0 MDLSYN0; // len:  112 @ 0x0000, MDLSYN0
    MFX     MFX;     // len:   84 @ 0x0070, MFX
    TONECOM TONECOM; // len:   20 @ 0x00c4, TONECOM
} MdlSynPrm0;

/* PCMEX: Group */
/* Total length: 1632 bytes (0x0660) */
typedef struct PCMEX {
    PCMT_CMN PCMT_CMN;    // len:   64 @ 0x0000, PCMT_CMN
    MFX      MFX;         // len:   84 @ 0x0040, MFX
    PCMT_PMT PCMT_PMT;    // len:   52 @ 0x0094, PCMT_PMT
    PCMT_PTL PCMT_PTL[4]; // len:  496 @ 0x00c8, PCMT_PTL
    PTL_PENV PTL_PENV[4]; // len:   96 @ 0x02b8, PTL_PENV
    PTL_FENV PTL_FENV[4]; // len:   96 @ 0x0318, PTL_FENV
    PTL_AENV PTL_AENV[4]; // len:   64 @ 0x0378, PTL_AENV
    PTL_LFO  PTL_LFO[4];  // len:  416 @ 0x03b8, PTL_LFO
    PTL_EQ   PTL_EQ[4];   // len:   64 @ 0x0558, PTL_EQ
    PCMS_CMN PCMS_CMN;    // len:   20 @ 0x0598, PCMS_CMN
    PCMS_PMT PCMS_PMT;    // len:   36 @ 0x05ac, PCMS_PMT
    PCMS_PTL PCMS_PTL[4]; // len:  144 @ 0x05d0, PCMS_PTL
} PCMEX;

/* PCMR: Group */
/* Total length: 3328 bytes (0x0d00) */
typedef struct PCMR {
    PCMR_CMN PCMR_CMN;     // len:   28 @ 0x0000, PCMR_CMN
    MFX      MFX;          // len:   84 @ 0x001c, MFX
    RCMP     RCMP[6];      // len:   48 @ 0x0070, RCMP
    PCMR_PTL PCMR_PTL[88]; // len: 1760 @ 0x00a0, PCMR_PTL
    PTL_EQ   PTL_EQ[88];   // len: 1408 @ 0x0780, PTL_EQ
} PCMR;

/* VoDsgn: Group */
/* Total length: 136 bytes (0x0088) */
typedef struct VoDsgn {
    MDLVDN  MDLVDN;  // len:   32 @ 0x0000, MDLVDN
    TONECOM TONECOM; // len:   20 @ 0x0020, TONECOM
    MFX     MFX;     // len:   84 @ 0x0034, MFX
} VoDsgn;

#pragma pack(pop)

#endif /* JUPITER_GENERATED_H */
