/* Autogenerated from config: mv_1_180_A */
#ifndef MV_1_180_A_GENERATED_H
#define MV_1_180_A_GENERATED_H

#include <stdint.h>

typedef int8_t s8;
typedef uint8_t u8;
typedef int16_t s16;
typedef uint16_t u16;
typedef int32_t s32;
typedef uint32_t u32;

#pragma pack(push, 1)

/* ARP: Block */
/* Total length: 128 bytes (0x0080) */
typedef struct ARP {
    u8 ARP_SW;        // len:    1 @ 0x0000, Arpeggio Switch
    u8 ARP_HOLD;      // len:    1 @ 0x0001, Arpeggio Hold
    u8 ARP_MOTIF;     // len:    1 @ 0x0002, Arpeggio Motif
    u8 ARP_DURATION;  // len:    1 @ 0x0003, Arpeggio Duration
    u8 ARP_VELO;      // len:    1 @ 0x0004, Arpeggio Velocity
    s8 ARP_OCT;       // len:    1 @ 0x0005, Arpeggio Octave Range
    u8 ARP_RATE;      // len:    1 @ 0x0006, Arpeggio Shuffle Rate
    u8 ARP_RESO;      // len:    1 @ 0x0007, Arpeggio Shuffle Resolution
    u8 ARP_GRID;      // len:    1 @ 0x0008, Arpeggio Grid
    u8 PADDING1[3];   // len:    3 @ 0x0009, __padding
    u8 PADDING2[116]; // len:  116 @ 0x000c, __padding
} ARP;

/* CLC: Block */
/* Total length: 128 bytes (0x0080) */
typedef struct CLC {
    u8  NAME_1;         // len:    1 @ 0x0000,  1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u16 TEMPO;          // len:    2 @ 0x0010, Clip Tempo
    s8  TYPE;           // len:    1 @ 0x0012, Clip Type
    u8  PADDING1;       // len:    1 @ 0x0013, __padding
    u8  TAG_KEY;        // len:    1 @ 0x0014, Key
    u8  TAG_SCALE;      // len:    1 @ 0x0015, Scale
    s8  PAD_OCT_SHIFT;  // len:    1 @ 0x0016, Pad Oct Shift
    u8  PADDING2;       // len:    1 @ 0x0017, __padding
    u8  PADDING3[104];  // len:  104 @ 0x0018, __padding
} CLC;

/* CLP_KNOB: KNOB */
/* Total length: 72 bytes (0x0048) */
typedef struct CLP_KNOB {
    s16 ASGN_1;        // len:    2 @ 0x0000, Knob Assign 1
    u8  reserved_1[8]; // len:    8 @ 0x0002, implicit padding
    u16 PADDING1;      // len:    2 @ 0x000a, __padding
    s16 MIN_1;         // len:    2 @ 0x000c, Knob Asssin Range Min 1
    u8  reserved_2[8]; // len:    8 @ 0x000e, implicit padding
    u16 PADDING2;      // len:    2 @ 0x0016, __padding
    s16 MAX_1;         // len:    2 @ 0x0018, Knob Asssin Range Max 1
    u8  reserved_3[8]; // len:    8 @ 0x001a, implicit padding
    u16 PADDING3;      // len:    2 @ 0x0022, __padding
    u8  PADDING4[36];  // len:   36 @ 0x0024, __padding
} CLP_KNOB;

/* CLP: Block */
/* Total length: 640 bytes (0x0280) */
typedef struct CLP {
    u8       LEVEL;         // len:    1 @ 0x0000, Level
    s8       PAN;           // len:    1 @ 0x0001, Pan (CC#10)
    s8       PIT_CRS;       // len:    1 @ 0x0002, Coarse Tune (RPN#2)
    s8       PIT_FINE;      // len:    1 @ 0x0003, Fine Tune (RPN#1)
    u8       MONO_POLY;     // len:    1 @ 0x0004, Mono/Poly
    u8       LEGATO;        // len:    1 @ 0x0005, Legato Sw
    u8       BEND_RANGE;    // len:    1 @ 0x0006, Bend Range
    u8       PORT_SW;       // len:    1 @ 0x0007, Portamento Sw (CC#65)
    u8       PORT_TIME;     // len:    1 @ 0x0008, Portamento Time (CC#5)
    s8       CUTOFF_OFST;   // len:    1 @ 0x0009, Cutoff Offset (CC#74)
    s8       RESO_OFST;     // len:    1 @ 0x000a, Resonance Offset (CC#71)
    s8       ATK_OFST;      // len:    1 @ 0x000b, Attack Time Offset (CC#73)
    s8       DCY_OFST;      // len:    1 @ 0x000c, Decay Time Offset (CC#75)
    s8       REL_OFST;      // len:    1 @ 0x000d, Release Time Offset (CC#72)
    s8       VIB_RATE;      // len:    1 @ 0x000e, Vibrato Rate (CC#76)
    s8       VIB_DEPTH;     // len:    1 @ 0x000f, Vibrato Depth (CC#77)
    s8       VIB_DELAY;     // len:    1 @ 0x0010, Vibrato Delay (CC#78)
    s8       OCT_SHIFT;     // len:    1 @ 0x0011, Octave Shift
    s8       VEL_SENS_OFST; // len:    1 @ 0x0012, Velocity Sens Offset
    u8       CHO_SEND;      // len:    1 @ 0x0013, Delay Send Level (CC#93)
    u8       REV_SEND;      // len:    1 @ 0x0014, Reverb Send Level (CC#91)
    u8       OUTPUT;        // len:    1 @ 0x0015, Output Assign
    u8       ASGN_MODE;     // len:    1 @ 0x0016, Voice Assign Mode
    u8       BEND_MODE;     // len:    1 @ 0x0017, Bend Mode
    u8       UNISON_SW;     // len:    1 @ 0x0018, Unison Sw
    u8       VCRV_TYPE;     // len:    1 @ 0x0019, Velocity Curve Type
    u16      PADDING1;      // len:    2 @ 0x001a, __padding
    u8       TUNE_TYPE;     // len:    1 @ 0x001c, Scale Tune Type
    u8       TUNE_KEY;      // len:    1 @ 0x001d, Scale Tune Key
    s8       TUNE_C;        // len:    1 @ 0x001e, Scale Tune for C
    s8       TUNE_CS;       // len:    1 @ 0x001f, Scale Tune for C#
    s8       TUNE_D;        // len:    1 @ 0x0020, Scale Tune for D
    s8       TUNE_DS;       // len:    1 @ 0x0021, Scale Tune for D#
    s8       TUNE_E;        // len:    1 @ 0x0022, Scale Tune for E
    s8       TUNE_F;        // len:    1 @ 0x0023, Scale Tune for F
    s8       TUNE_FS;       // len:    1 @ 0x0024, Scale Tune for F#
    s8       TUNE_G;        // len:    1 @ 0x0025, Scale Tune for G
    s8       TUNE_GS;       // len:    1 @ 0x0026, Scale Tune for G#
    s8       TUNE_A;        // len:    1 @ 0x0027, Scale Tune for A
    s8       TUNE_AS;       // len:    1 @ 0x0028, Scale Tune for A#
    s8       TUNE_B;        // len:    1 @ 0x0029, Scale Tune for B
    u16      PADDING2;      // len:    2 @ 0x002a, __padding
    CLP_KNOB KNOB[8];       // len:  576 @ 0x002c, KNOB
    u8       MODULATION;    // len:    1 @ 0x026c, SYS-Ctrl1
    u8       AFTERTOUCH;    // len:    1 @ 0x026d, SYS-Ctrl2
    u8       BREATH;        // len:    1 @ 0x026e, SYS-Ctrl3
    u8       FOOTTYPE;      // len:    1 @ 0x026f, SYS-Ctrl4
    s16      PITCH_BEND;    // len:    2 @ 0x0270, Pitch Bend
    u8       MIX_LEV;       // len:    1 @ 0x0272, Mix Level
    s8       SEL_NOTE;      // len:    1 @ 0x0273, Select Note
    u8       PADDING3[12];  // len:   12 @ 0x0274, __padding
} CLP;

/* GLT: Block */
/* Total length: 64 bytes (0x0040) */
typedef struct GLT {
    u8  POS;            // len:    1 @ 0x0000, Scatter Position
    u8  MIDI_SYNC;      // len:    1 @ 0x0001, Scatter MIDI Sync
    u8  SPEED;          // len:    1 @ 0x0002, Scatter Speed
    u8  LOOP;           // len:    1 @ 0x0003, Scatter Loop Hold
    u8  MEAS;           // len:    1 @ 0x0004, Scatter Measure
    u8  SPLIT;          // len:    1 @ 0x0005, Scatter Split
    u8  PLAY;           // len:    1 @ 0x0006, Scatter Switch
    u8  TURN;           // len:    1 @ 0x0007, Scatter Turn
    s8  CLIP;           // len:    1 @ 0x0008, Scatter Clip
    u8  ALL_GRAIN;      // len:    1 @ 0x0009, Scatter All Grain
    u16 ALL_ATK;        // len:    2 @ 0x000a, Scatter All Attack
    u16 ALL_DCY;        // len:    2 @ 0x000c, Scatter All Decay
    u8  PAD;            // len:    1 @ 0x000e, Scatter PAD
    u8  PAD_MODE;       // len:    1 @ 0x000f, Scatter PAD_MODE
    u8  BASE_SCALE;     // len:    1 @ 0x0010, Base Scale
    u8  BASE_LENGTH;    // len:    1 @ 0x0011, Base Step
    u8  ALTERNATE_MODE; // len:    1 @ 0x0012, Alternate Mode
    u8  PAD_QUANTIZE;   // len:    1 @ 0x0013, Pad Quantize
    u8  DE_CLICK;       // len:    1 @ 0x0014, De-Click
    u8  PADDING1[43];   // len:   43 @ 0x0015, __padding
} GLT;

/* GLT2_DT: DT */
/* Total length: 36 bytes (0x0024) */
typedef struct GLT2_DT {
    u8  COLOR;       // len:    1 @ 0x0000, LED Color
    u8  SIZE;        // len:    1 @ 0x0001, Scatter Size
    u8  MUTE_SW;     // len:    1 @ 0x0002, Scatter Mute Sw
    u8  LEVEL;       // len:    1 @ 0x0003, Scatter Level
    s16 LEVEL_GLD;   // len:    2 @ 0x0004, Scatter Level Glide
    u8  PAN;         // len:    1 @ 0x0006, Scatter Pan
    u8  PADDING1;    // len:    1 @ 0x0007, __padding
    s16 PAN_GLD;     // len:    2 @ 0x0008, Scatter Pan Glide
    u8  REVERSE;     // len:    1 @ 0x000a, Scatter Reverse
    s8  PITCH_CHRM;  // len:    1 @ 0x000b, Scatter Pitch Chromatic
    u8  PADDING2[3]; // len:    3 @ 0x000c, __padding
    s8  PITCH_FINE;  // len:    1 @ 0x000f, Scatter Pitch Fine
    u16 PITCH_BEND;  // len:    2 @ 0x0010, Scatter Pitch Bend
    s16 PITCH_GLD;   // len:    2 @ 0x0012, Scatter Pitch Glide
    u8  RETRIG;      // len:    1 @ 0x0014, Scatter Retrig
    s8  RETRIG_GLD;  // len:    1 @ 0x0015, Scatter Retrig Glide
    u8  HOLD;        // len:    1 @ 0x0016, Scatter Hold
    u8  OVERLAP;     // len:    1 @ 0x0017, Scatter Mask
    u16 PADDING3;    // len:    2 @ 0x0018, __padding
    u16 ATK_TIME;    // len:    2 @ 0x001a, Scatter Attack
    u16 DCY_TIME;    // len:    2 @ 0x001c, Scatter Decay
    u8  FX_DRY;      // len:    1 @ 0x001e, FX Dry Lv
    u8  FX_WET_GFX1; // len:    1 @ 0x001f, FX1 Wet Lv
    u8  FX_WET_GFX2; // len:    1 @ 0x0020, FX2 Wet Lv
    u8  FX_WET_SR;   // len:    1 @ 0x0021, FX S/R Wet Lv
    u8  GRAIN;       // len:    1 @ 0x0022, Scatter Grain
    u8  PADDING4;    // len:    1 @ 0x0023, __padding
} GLT2_DT;

/* GLT2_PL: PL */
/* Total length: 36 bytes (0x0024) */
typedef struct GLT2_PL {
    u8  EDIT_MARKER; // len:    1 @ 0x0000, Edited marker
    u8  SIZE;        // len:    1 @ 0x0001, Scatter Size
    u8  MUTE_SW;     // len:    1 @ 0x0002, Scatter Mute Sw
    u8  LEVEL;       // len:    1 @ 0x0003, Scatter Level
    s16 LEVEL_GLD;   // len:    2 @ 0x0004, Scatter Level Glide
    u8  PAN;         // len:    1 @ 0x0006, Scatter Pan
    u8  PADDING1;    // len:    1 @ 0x0007, __padding
    s16 PAN_GLD;     // len:    2 @ 0x0008, Scatter Pan Glide
    u8  REVERSE;     // len:    1 @ 0x000a, Scatter Reverse
    s8  PITCH_CHRM;  // len:    1 @ 0x000b, Scatter Pitch Chromatic
    s8  PITCH_FINE;  // len:    1 @ 0x000c, Scatter Pitch Fine
    u8  PADDING2[3]; // len:    3 @ 0x000d, __padding
    u16 PITCH_BEND;  // len:    2 @ 0x0010, Scatter Pitch Bend
    s16 PITCH_GLD;   // len:    2 @ 0x0012, Scatter Pitch Glide
    u8  RETRIG;      // len:    1 @ 0x0014, Scatter Retrig
    s8  RETRIG_GLD;  // len:    1 @ 0x0015, Scatter Retrig Glide
    u8  HOLD;        // len:    1 @ 0x0016, Scatter Hold
    u8  OVERLAP;     // len:    1 @ 0x0017, Scatter Mask
    u16 ATK_TIME;    // len:    2 @ 0x0018, Scatter Attack
    u16 DCY_TIME;    // len:    2 @ 0x001a, Scatter Decay
    u8  FX_DRY;      // len:    1 @ 0x001c, FX Dry Lv
    u8  FX_WET_GFX1; // len:    1 @ 0x001d, FX1 Wet Lv
    u8  FX_WET_GFX2; // len:    1 @ 0x001e, FX2 Wet Lv
    u8  FX_WET_SR;   // len:    1 @ 0x001f, FX S/R Wet Lv
    u8  GRAIN;       // len:    1 @ 0x0020, Scatter Grain
    u8  SEQ;         // len:    1 @ 0x0021, Scatter Seq
    u8  PAD;         // len:    1 @ 0x0022, Scatter PAD
    u8  PADDING3;    // len:    1 @ 0x0023, __padding
} GLT2_PL;

/* GLT2: Block */
/* Total length: 76 bytes (0x004c) */
typedef struct GLT2 {
    GLT2_PL PL;       // len:   36 @ 0x0000, PL
    GLT2_DT DT;       // len:   36 @ 0x0024, DT
    u32     PADDING1; // len:    4 @ 0x0048, __padding
} GLT2;

/* INST_CMN_WMT: WMT */
/* Total length: 28 bytes (0x001c) */
typedef struct INST_CMN_WMT {
    u8  SW;            // len:    1 @ 0x0000, Wave Switch
    u8  WAV_GTYPE;     // len:    1 @ 0x0001, Wave Group Type
    u16 WAV_GID;       // len:    2 @ 0x0002, Wave Group ID
    u16 WAV_NUM_L;     // len:    2 @ 0x0004, Wave Number L
    u16 WAV_NUM_R;     // len:    2 @ 0x0006, Wave Number R
    u8  WAV_GAIN;      // len:    1 @ 0x0008, Wave Gain
    u8  FXM_SW;        // len:    1 @ 0x0009, Wave FXM Switch
    u8  FXM_COLOR;     // len:    1 @ 0x000a, Wave FXM Color
    u8  FXM_DEPTH;     // len:    1 @ 0x000b, Wave FXM Depth
    s8  PIT_CRS;       // len:    1 @ 0x000c, Wave Coarse Tune
    s8  PIT_FINE;      // len:    1 @ 0x000d, Wave Fine Tune
    s8  PAN;           // len:    1 @ 0x000e, Wave Pan
    u8  PAN_RND_SW;    // len:    1 @ 0x000f, Wave Random Pan Sw
    u8  PAN_ALT_SW;    // len:    1 @ 0x0010, Wave Alternate Pan Sw
    u8  LEVEL;         // len:    1 @ 0x0011, Wave Level
    u8  PADDING1;      // len:    1 @ 0x0012, __padding
    u8  DELAY_MODE;    // len:    1 @ 0x0013, Delay Mode
    u8  DLY_TIME_SYNC; // len:    1 @ 0x0014, DelayTime Sync
    u8  DLY_TIME_NOTE; // len:    1 @ 0x0015, DelayTime (note)
    u16 DLY_TIME;      // len:    2 @ 0x0016, DelayTime
    u8  VRANGE_LO;     // len:    1 @ 0x0018, VeloRange Lower
    u8  VRANGE_UP;     // len:    1 @ 0x0019, VeloRange Upper
    u8  VFADE_LO;      // len:    1 @ 0x001a, VeloFade Lower
    u8  VFADE_UP;      // len:    1 @ 0x001b, VeloFade Upper
} INST_CMN_WMT;

/* INST_CMN: PCMRhythm Inst Common */
/* Total length: 152 bytes (0x0098) */
typedef struct INST_CMN {
    u8           NAME_1;         // len:    1 @ 0x0000, Name 1
    u8           reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8           CATEGORY;       // len:    1 @ 0x0010, Category
    u8           LEVEL;          // len:    1 @ 0x0011, Level
    u8           SRC_KEY;        // len:    1 @ 0x0012, Source Key
    s8           PIT_FINE;       // len:    1 @ 0x0013, Fine Tune
    u16          PIT_RND;        // len:    2 @ 0x0014, Random Pitch Depth
    u8           PAN_RND;        // len:    1 @ 0x0016, Random Pan Depth
    s8           PAN_ALT;        // len:    1 @ 0x0017, Alternate Pan Depth
    u8           ASGN_TYPE;      // len:    1 @ 0x0018, Assign Type
    u8           ENV_MODE;       // len:    1 @ 0x0019, Envelope Mode
    u8           WMT_VEL_CTRL;   // len:    1 @ 0x001a, WMT Velocity Control
    u8           PADDING1;       // len:    1 @ 0x001b, __padding
    INST_CMN_WMT WMT[4];         // len:  112 @ 0x001c, WMT
    u8           FILTER_TYPE;    // len:    1 @ 0x008c, TVF Filter Type
    u8           PADDING2;       // len:    1 @ 0x008d, __padding
    u16          CUTOFF;         // len:    2 @ 0x008e, TVF Cutoff Frequency
    u8           CUTOFF_VCRV;    // len:    1 @ 0x0090, TVF Cutoff Velocity Curve
    s8           CUTOFF_VSENS;   // len:    1 @ 0x0091, TVF Cutoff Velocity Sens
    u16          RESO;           // len:    2 @ 0x0092, TVF Resonance
    s8           RESO_VSENS;     // len:    1 @ 0x0094, TVF Resonance Velocity Sens
    u8           LEVEL_VCRV;     // len:    1 @ 0x0095, TVA Level Velocity Curve
    s8           LEVEL_VSENS;    // len:    1 @ 0x0096, TVA Level Velocity Sens
    u8           TEMPO_SYNC;     // len:    1 @ 0x0097, Wave Tempo Sync
} INST_CMN;

/* KBDARP: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct KBDARP {
    u8  STYLE;        // len:    1 @ 0x0000, Style
    u8  HOLD;         // len:    1 @ 0x0001, Hold
    u8  VARIATION;    // len:    1 @ 0x0002, Variation
    u8  MOTIF;        // len:    1 @ 0x0003, Motif
    u8  KB_VELO;      // len:    1 @ 0x0004, Keyboard Velocity
    s8  OCT_RANGE;    // len:    1 @ 0x0005, Octave Rage
    u8  ACC_RATE;     // len:    1 @ 0x0006, Accent Rate
    u8  SHUFFLE_RATE; // len:    1 @ 0x0007, Shuffle Rate
    u8  SHUFFLE_RESO; // len:    1 @ 0x0008, Shuffle Resolution
    u8  CHORD;        // len:    1 @ 0x0009, Chord Mode
    u16 PADDING1;     // len:    2 @ 0x000a, __padding
} KBDARP;

/* LOOP_CMN: PCMRhythm Common */
/* Total length: 124 bytes (0x007c) */
typedef struct LOOP_CMN {
    u8  NAME_1;         // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  EXPORT_LOCK;    // len:    1 @ 0x0010, Export Lock
    u8  PADDING1[3];    // len:    3 @ 0x0011, __padding
    u8  LPR_TM_STRETCH; // len:    1 @ 0x0014, Pitch/Stretch
    s8  PITCH_CHRM;     // len:    1 @ 0x0015, Pitch Chromatic
    s8  PITCH_FINE;     // len:    1 @ 0x0016, Pitch Fine
    u8  LPR_REVERSE;    // len:    1 @ 0x0017, Reverse
    u8  SHUFFLE_POS;    // len:    1 @ 0x0018, Shuffle Pos
    u8  SHUFFLE_RATIO;  // len:    1 @ 0x0019, Shuffle Ratio
    u8  PRI_MEAS_BPM;   // len:    1 @ 0x001a, Pri Meas/BPM
    u8  LPR_MEAS;       // len:    1 @ 0x001b, Measure
    u16 BPM;            // len:    2 @ 0x001c, BPM
    u16 PADDING2;       // len:    2 @ 0x001e, __padding
    u16 START_OFST;     // len:    2 @ 0x0020, Start Ofst
    s16 END_OFST;       // len:    2 @ 0x0022, End Ofst
    u8  START_STEP;     // len:    1 @ 0x0024, Start Step
    s8  LAST_STEP;      // len:    1 @ 0x0025, Last Step
    u8  STEP_LENGTH;    // len:    1 @ 0x0026, Step Length
    u8  PADDING3;       // len:    1 @ 0x0027, __padding
    u16 PITCH_BEND;     // len:    2 @ 0x0028, Pitch Shift
    u8  SCALE;          // len:    1 @ 0x002a, Base Scale
    u8  SCALE_LENGTH;   // len:    1 @ 0x002b, Base Length
    u8  LEVEL;          // len:    1 @ 0x002c, Level
    u8  TM_WINDOW;      // len:    1 @ 0x002d, Stretch Window
    u8  ATK_TIME;       // len:    1 @ 0x002e, Attack Time
    u8  PADDING4;       // len:    1 @ 0x002f, __padding
    u8  PADDING5[76];   // len:   76 @ 0x0030, __padding
} LOOP_CMN;

/* MFX: Block */
/* Total length: 84 bytes (0x0054) */
typedef struct MFX {
    u8  mfxType;        // len:    1 @ 0x0000, Type
    u8  mfxSwitch;      // len:    1 @ 0x0001, MFX Switch
    u8  choSend;        // len:    1 @ 0x0002, MFX Delay Send Level
    u8  revSend;        // len:    1 @ 0x0003, MFX Reverb Send Level
    u8  ctrlSrc1;       // len:    1 @ 0x0004, MFX CtrlSrc 1
    s8  ctrlSens1;      // len:    1 @ 0x0005, MFX CtrlSens 1
    u8  ctrlSrc2;       // len:    1 @ 0x0006, MFX CtrlSrc 2
    s8  ctrlSens2;      // len:    1 @ 0x0007, MFX CtrlSens 2
    u8  ctrlSrc3;       // len:    1 @ 0x0008, MFX CtrlSrc 3
    s8  ctrlSens3;      // len:    1 @ 0x0009, MFX CtrlSens 3
    u8  ctrlSrc4;       // len:    1 @ 0x000a, MFX CtrlSrc 4
    s8  ctrlSens4;      // len:    1 @ 0x000b, MFX CtrlSens 4
    u8  ctrlAsgn_1;     // len:    1 @ 0x000c, MFX CtrlAsgn 1
    u8  reserved_1[3];  // len:    3 @ 0x000d, implicit padding
    s16 param_1;        // len:    2 @ 0x0010, MFX Parameter 1
    u8  reserved_2[62]; // len:   62 @ 0x0012, implicit padding
    u32 PADDING1;       // len:    4 @ 0x0050, __padding
} MFX;

/* MSMP_CMN: Multisample Common */
/* Total length: 16 bytes (0x0010) */
typedef struct MSMP_CMN {
    u8 NAME_1;         // len:    1 @ 0x0000, Multisample Name 1
    u8 reserved_1[15]; // len:   15 @ 0x0001, trailing padding
} MSMP_CMN;

/* MSMP_SPLT: Multisample Split */
/* Total length: 4 bytes (0x0004) */
typedef struct MSMP_SPLT {
    u16 WAV_NUM;  // len:    2 @ 0x0000, Wave Number
    u8  LEVEL;    // len:    1 @ 0x0002, Level
    s8  PIT_FINE; // len:    1 @ 0x0003, Partial Fine Tune
} MSMP_SPLT;

/* PCMR_CMN: PCMRhythm Common */
/* Total length: 28 bytes (0x001c) */
typedef struct PCMR_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u16 PADDING1;         // len:    2 @ 0x0010, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Phrase Number
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    u16 PADDING2;         // len:    2 @ 0x0015, __padding
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x0017, Phrase Velo Rate
    s8  PHRASE_VEL_SHIFT; // len:    1 @ 0x0018, Phrase Velo Shift
    u8  PADDING3[3];      // len:    3 @ 0x0019, __padding
} PCMR_CMN;

/* PCMR_PTL: PCMRhythm Partial */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMR_PTL {
    u16 INST_NUM;      // len:    2 @ 0x0000, Inst Number
    u8  INST_GTYPE;    // len:    1 @ 0x0002, Inst Bank
    u8  PADDING1;      // len:    1 @ 0x0003, __padding
    u16 INST_GID;      // len:    2 @ 0x0004, Inst Group ID
    u8  LEVEL;         // len:    1 @ 0x0006, Level
    u8  PADDING2;      // len:    1 @ 0x0007, __padding
    s8  PAN;           // len:    1 @ 0x0008, Pan
    u8  CHO_SEND;      // len:    1 @ 0x0009, Delay Send Level
    u8  REV_SEND;      // len:    1 @ 0x000a, Reverb Send Level
    u8  MUTE_GRP;      // len:    1 @ 0x000b, Mute Group
    u8  OUT_ASGN;      // len:    1 @ 0x000c, Output Assign
    s8  KEY_OFST;      // len:    1 @ 0x000d, Key Offset
    s8  PIT_FINE_OFST; // len:    1 @ 0x000e, Fine Tune Offset
    s8  CUTOFF_OFST;   // len:    1 @ 0x000f, TVF Cutoff Offset
    s8  RESO_OFST;     // len:    1 @ 0x0010, TVF Resonance Offset
    s8  TVA_ATK_OFST;  // len:    1 @ 0x0011, TVA Attack Time Offset
    s8  TVA_DCY_OFST;  // len:    1 @ 0x0012, TVA Decay Time Offset
    s8  TVA_REL_OFST;  // len:    1 @ 0x0013, TVA Release Time Offset
} PCMR_PTL;

/* PCMS_CMN: PCMSynth Common */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMS_CMN {
    u8 UNISON_SW;          // len:    1 @ 0x0000, Unison Switch
    u8 UNISON_SIZE;        // len:    1 @ 0x0001, Unison Size
    u8 UNISON_DETN;        // len:    1 @ 0x0002, Unison Detune
    u8 PADDING1;           // len:    1 @ 0x0003, __padding
    u8 BEND_RANGE_FINE_UP; // len:    1 @ 0x0004, Bend Range Fine Up
    u8 BEND_RANGE_FINE_DW; // len:    1 @ 0x0005, Bend Range Fine Down
    u8 RND_PIT_VAL;        // len:    1 @ 0x0006, Pitch Drift
    u8 RND_PIT_NUM;        // len:    1 @ 0x0007, Pitch Drift Cycle Number
    u8 CONDITION;          // len:    1 @ 0x0008, Condition
    u8 PADDING2[11];       // len:   11 @ 0x0009, __padding
} PCMS_CMN;

/* PCMS_PMT: PCMSynth PMT */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PMT {
    u8  STRUCT12;        // len:    1 @ 0x0000, Structure 1-2
    u8  STRUCT34;        // len:    1 @ 0x0001, Structure 3-4
    u16 PADDING1;        // len:    2 @ 0x0002, __padding
    u8  RING12_LEVEL;    // len:    1 @ 0x0004, RING 1-2 Level
    u8  RING34_LEVEL;    // len:    1 @ 0x0005, RING 3-4 Level
    u8  RING_OSC1_LEVEL; // len:    1 @ 0x0006, RING OSC1 Level
    u8  RING_OSC2_LEVEL; // len:    1 @ 0x0007, RING OSC2 Level
    u8  RING_OSC3_LEVEL; // len:    1 @ 0x0008, RING OSC3 Level
    u8  RING_OSC4_LEVEL; // len:    1 @ 0x0009, RING OSC4 Level
    u16 PADDING2;        // len:    2 @ 0x000a, __padding
    u16 XMOD12_DEPTH;    // len:    2 @ 0x000c, CrossMod 1-2 Depth
    u16 XMOD34_DEPTH;    // len:    2 @ 0x000e, CrossMod 3-4 Depth
    u8  XMOD_OSC1_LEVEL; // len:    1 @ 0x0010, CrossMod OSC1 Level
    u8  XMOD_OSC2_LEVEL; // len:    1 @ 0x0011, CrossMod OSC2 Level
    u8  XMOD_OSC3_LEVEL; // len:    1 @ 0x0012, CrossMod OSC3 Level
    u8  XMOD_OSC4_LEVEL; // len:    1 @ 0x0013, CrossMod OSC4 Level
    u8  PTL_PHS_LOCK;    // len:    1 @ 0x0014, Partial Phase Lock
    u8  XMOD2_12_DEPTH;  // len:    1 @ 0x0015, CrossMod2 1-2 Depth
    u8  XMOD2_34_DEPTH;  // len:    1 @ 0x0016, CrossMod2 3-4 Depth
    u8  PADDING3[13];    // len:   13 @ 0x0017, __padding
} PCMS_PMT;

/* PCMS_PTL: PCMSynth Partial */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PTL {
    u8  OSC_TYPE;         // len:    1 @ 0x0000, OSC Type
    u8  VA_FORM;          // len:    1 @ 0x0001, VA Waveform
    u16 SYNC_WAV_NUM;     // len:    2 @ 0x0002, PCM-Sync Wave Number
    u8  PW;               // len:    1 @ 0x0004, Pulse Width
    s8  PWM_DEPTH;        // len:    1 @ 0x0005, PWM Depth
    u8  SSAW_DETUNE;      // len:    1 @ 0x0006, SuperSAW Detune
    u8  CLICK_TYPE;       // len:    1 @ 0x0007, Click Type
    u16 HPF_CUTOFF;       // len:    2 @ 0x0008, HPF Cutoff
    u8  FILTER_TYPE;      // len:    1 @ 0x000a, Filter Type
    u8  FILTER_SLOPE;     // len:    1 @ 0x000b, Filter Slope
    u8  ADSR_ENV_SW;      // len:    1 @ 0x000c, ADSREnv Switch
    u8  FAT;              // len:    1 @ 0x000d, Fat
    u8  VCF_TYPE;         // len:    1 @ 0x000e, VCF Type
    u8  OSC_ATT;          // len:    1 @ 0x000f, OSC Attenuator
    u8  CUTOFF_KF_BP;     // len:    1 @ 0x0010, Cutoff Keyfollow Base Point
    u8  VA_INVERT_SW;     // len:    1 @ 0x0011, VA Waveform Invert Switch
    s8  FENV_FINE_DEPTH;  // len:    1 @ 0x0012, TVF Env Fine Depth
    u8  PENV_LFO_TRIG_SW; // len:    1 @ 0x0013, PENV LFO Trigger Switch
    u8  FENV_LFO_TRIG_SW; // len:    1 @ 0x0014, FENV LFO Trigger Switch
    u8  AENV_LFO_TRIG_SW; // len:    1 @ 0x0015, AENV LFO Trigger Switch
    u8  PITCH_DOWN_DEPTH; // len:    1 @ 0x0016, Pitch Down Depth
    u8  VCF_GC;           // len:    1 @ 0x0017, VCF Gain Correction
    u8  PADDING1[12];     // len:   12 @ 0x0018, __padding
} PCMS_PTL;

/* PCMT_CMN: PCMTone Common */
/* Total length: 64 bytes (0x0040) */
typedef struct PCMT_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u8  CATEGORY;         // len:    1 @ 0x0010, Category
    u8  PADDING1;         // len:    1 @ 0x0011, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Reserved
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    s8  PAN;              // len:    1 @ 0x0015, Pan
    u16 PADDING2;         // len:    2 @ 0x0016, __padding
    u8  PRIORITY;         // len:    1 @ 0x0018, Priority
    s8  PIT_CRS;          // len:    1 @ 0x0019, Tone Coarse Tune
    s8  PIT_FINE;         // len:    1 @ 0x001a, Tone Fine Tune
    s8  OCTAVE;           // len:    1 @ 0x001b, Octave Shift
    u8  STRETCH;          // len:    1 @ 0x001c, Stretch Tune Depth
    u8  ANALOG_FEEL;      // len:    1 @ 0x001d, Analog Feel
    u8  MONO_POLY;        // len:    1 @ 0x001e, Mono/Poly
    u8  LEGATO_SW;        // len:    1 @ 0x001f, Legato Switch
    u8  RETRIG_INTVL;     // len:    1 @ 0x0020, Legato Retrigger Interval
    u8  PORTA_SW;         // len:    1 @ 0x0021, Portamento Switch
    u8  PORTA_MODE;       // len:    1 @ 0x0022, Portamento Mode
    u8  PORTA_TYPE;       // len:    1 @ 0x0023, Portamento Type
    u8  PADDING3;         // len:    1 @ 0x0024, __padding
    u8  PORTA_START;      // len:    1 @ 0x0025, Portamento Start
    u16 PORTA_TIME;       // len:    2 @ 0x0026, Portamento Time
    u8  BEND_RANGE_UP;    // len:    1 @ 0x0028, Bend Range Up
    u8  BEND_RANGE_DW;    // len:    1 @ 0x0029, Bend Range Down
    u8  BEND_MODE;        // len:    1 @ 0x002a, Bend Mode
    u8  SOFT_LEVEL_SENS;  // len:    1 @ 0x002b, Soft Level Sens
    u8  PHRASE_OCT;       // len:    1 @ 0x002c, Reserved
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x002d, Reserved
    u8  PHRASE_VEL_SHIFT; // len:    1 @ 0x002e, Reserved
    u8  SYMP_DEPTH;       // len:    1 @ 0x002f, Reserved
    u8  PORTA_CRV;        // len:    1 @ 0x0030, Portamento Curve Type
    u8  PTL_LFO_LOCK;     // len:    1 @ 0x0031, Partial LFO Phase Lock
    u8  PADDING4[14];     // len:   14 @ 0x0032, __padding
} PCMT_CMN;

/* PCMT_PMT_PMT: PMT */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PMT_PMT {
    u8 PTL_SW;      // len:    1 @ 0x0000, Partial Switch
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
    u8 KRANGE_LO;   // len:    1 @ 0x0004, KeyRange Lower
    u8 KRANGE_UP;   // len:    1 @ 0x0005, KeyRange Upper
    u8 KFADE_LO;    // len:    1 @ 0x0006, KeyFade Lower
    u8 KFADE_UP;    // len:    1 @ 0x0007, KeyFade Upper
    u8 VRANGE_LO;   // len:    1 @ 0x0008, VeloRange Lower
    u8 VRANGE_UP;   // len:    1 @ 0x0009, VeloRange Upper
    u8 VFADE_LO;    // len:    1 @ 0x000a, VeloFade Lower
    u8 VFADE_UP;    // len:    1 @ 0x000b, VeloFade Upper
} PCMT_PMT_PMT;

/* PCMT_PMT: PCMTone PartialMixTable */
/* Total length: 52 bytes (0x0034) */
typedef struct PCMT_PMT {
    u8           VEL_CTRL;      // len:    1 @ 0x0000, Velocity Control
    u8           PMT_LEVEL_CRV; // len:    1 @ 0x0001, PMT Level Curve
    u16          PADDING1;      // len:    2 @ 0x0002, __padding
    PCMT_PMT_PMT PMT[4];        // len:   48 @ 0x0004, PMT
} PCMT_PMT;

/* PCMT_PTL_MCTL: Matrix Control */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PTL_MCTL {
    u8 SRC;         // len:    1 @ 0x0000, Source
    u8 DST1;        // len:    1 @ 0x0001, Destination 1
    s8 SENS1;       // len:    1 @ 0x0002, Sens 1
    u8 DST2;        // len:    1 @ 0x0003, Destination 2
    s8 SENS2;       // len:    1 @ 0x0004, Sens 2
    u8 DST3;        // len:    1 @ 0x0005, Destination 3
    s8 SENS3;       // len:    1 @ 0x0006, Sens 3
    u8 DST4;        // len:    1 @ 0x0007, Destination 4
    s8 SENS4;       // len:    1 @ 0x0008, Sens 4
    u8 PADDING1[3]; // len:    3 @ 0x0009, __padding
} PCMT_PTL_MCTL;

/* PCMT_PTL: PCMTone Partial */
/* Total length: 124 bytes (0x007c) */
typedef struct PCMT_PTL {
    u8            LEVEL;         // len:    1 @ 0x0000, Level
    u8            PADDING1;      // len:    1 @ 0x0001, __padding
    s8            PIT_CRS;       // len:    1 @ 0x0002, Coarse Tune
    s8            PIT_FINE;      // len:    1 @ 0x0003, Fine Tune
    u16           PIT_RND;       // len:    2 @ 0x0004, Random Pitch Depth
    s8            PAN;           // len:    1 @ 0x0006, Pan
    s8            PAN_KF;        // len:    1 @ 0x0007, Pan Keyfollow
    u8            PAN_RND;       // len:    1 @ 0x0008, Random Pan Depth
    s8            PAN_ALT;       // len:    1 @ 0x0009, Alternate Pan Depth
    u8            ENV_MODE;      // len:    1 @ 0x000a, Envelope Mode
    u8            DELAY_MODE;    // len:    1 @ 0x000b, Delay Mode
    u8            DLY_TIME_SYNC; // len:    1 @ 0x000c, DelayTime Sync
    u8            DLY_TIME_NOTE; // len:    1 @ 0x000d, DelayTime (note)
    u16           DLY_TIME;      // len:    2 @ 0x000e, DelayTime
    u8            CHO_SEND;      // len:    1 @ 0x0010, Delay Send Level
    u8            REV_SEND;      // len:    1 @ 0x0011, Reverb Send Level
    u8            RX_BEND;       // len:    1 @ 0x0012, Receive Bender
    u8            RX_EXPR;       // len:    1 @ 0x0013, Receive Expression
    u8            RX_HOLD;       // len:    1 @ 0x0014, Receive Hold-1
    u8            REDAMP_SW;     // len:    1 @ 0x0015, Redamper Switch
    u8            OUT_ASGN;      // len:    1 @ 0x0016, Output Assign
    u8            WAV_GTYPE;     // len:    1 @ 0x0017, Wave Group Type
    u16           WAV_GID;       // len:    2 @ 0x0018, Wave Group ID
    u16           WAV_NUM_L;     // len:    2 @ 0x001a, Wave Number L
    u16           WAV_NUM_R;     // len:    2 @ 0x001c, Wave Number R
    u8            WAV_GAIN;      // len:    1 @ 0x001e, Gain
    u8            FXM_SW;        // len:    1 @ 0x001f, FXM Switch
    u8            FXM_COLOR;     // len:    1 @ 0x0020, FXM Color
    u8            FXM_DEPTH;     // len:    1 @ 0x0021, FXM Depth
    s16           PIT_KF;        // len:    2 @ 0x0022, Pitch Keyfollow
    u8            SOFT_EQ_SENS;  // len:    1 @ 0x0024, Soft EQ Sens
    u8            FILTER_TYPE;   // len:    1 @ 0x0025, TVF Filter Type
    u16           PADDING2;      // len:    2 @ 0x0026, __padding
    u16           CUTOFF;        // len:    2 @ 0x0028, TVF Cutoff Frequency
    s16           CUTOFF_KF;     // len:    2 @ 0x002a, TVF Cutoff Keyfollow
    u8            CUTOFF_VCRV;   // len:    1 @ 0x002c, TVF Cutoff Velocity Curve
    s8            CUTOFF_VSENS;  // len:    1 @ 0x002d, TVF Cutoff Velocity Sens
    u16           RESO;          // len:    2 @ 0x002e, TVF Resonance
    s8            RESO_VSENS;    // len:    1 @ 0x0030, TVF Resonance Velocity Sens
    s8            BIAS_LEVEL;    // len:    1 @ 0x0031, Bias Level
    u8            BIAS_POS;      // len:    1 @ 0x0032, Bias Position
    u8            BIAS_DIR;      // len:    1 @ 0x0033, Bias Direction
    u8            LEVEL_VCRV;    // len:    1 @ 0x0034, TVA Level Velocity Curve
    s8            LEVEL_VSENS;   // len:    1 @ 0x0035, TVA Level Velocity Sens
    s8            PENV_TKF;      // len:    1 @ 0x0036, Pitch Env Time Keyfollow
    s8            FENV_TKF;      // len:    1 @ 0x0037, TVF Env Time Keyfollow
    s8            AENV_TKF;      // len:    1 @ 0x0038, TVA Env Time Keyfollow
    s8            VIB_PIT_SENS;  // len:    1 @ 0x0039, Vibrato Pitch Sens
    s8            VIB_CUT_SENS;  // len:    1 @ 0x003a, Vibrato Cutoff Sens
    s8            VIB_AMP_SENS;  // len:    1 @ 0x003b, Vibrato Level Sens
    PCMT_PTL_MCTL MCTL[4];       // len:   48 @ 0x003c, Matrix Control
    u8            DAMP_FREE;     // len:    1 @ 0x006c, Damper Free Note
    u8            STEREO_WIDTH;  // len:    1 @ 0x006d, Stereo Width
    s8            STEREO_DETN;   // len:    1 @ 0x006e, Stereo Detune
    s8            DF_DCY_OFST;   // len:    1 @ 0x006f, Damper Free Decay Offset
    u8            TEMPO_SYNC;    // len:    1 @ 0x0070, Wave Tempo Sync
    u8            PADDING3[11];  // len:   11 @ 0x0071, __padding
} PCMT_PTL;

/* PEQ: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct PEQ {
    s8 EQ_IN_GAIN;  // len:    1 @ 0x0000, EQ Input Gain
    s8 EQ_LO_GAIN;  // len:    1 @ 0x0001, EQ Low Gain
    s8 EQ_MID_GAIN; // len:    1 @ 0x0002, EQ Mid Gain
    s8 EQ_HI_GAIN;  // len:    1 @ 0x0003, EQ High Gain
    u8 EQ_LO_FREQ;  // len:    1 @ 0x0004, EQ Low Frequency
    u8 EQ_MID_FREQ; // len:    1 @ 0x0005, EQ Mid Frequency
    u8 EQ_HI_FREQ;  // len:    1 @ 0x0006, EQ High Frequency
    u8 EQ_MID_Q;    // len:    1 @ 0x0007, EQ Mid Q
    u8 EQ_SW;       // len:    1 @ 0x0008, EQ Sw
    u8 PADDING1[3]; // len:    3 @ 0x0009, __padding
} PEQ;

/* PHR_BND: Block */
/* Total length: 16 bytes (0x0010) */
typedef struct PHR_BND {
    s16 BEND_VAL_1;     // len:    2 @ 0x0000, SEQ Bend Value 1
    u8  reserved_1[14]; // len:   14 @ 0x0002, trailing padding
} PHR_BND;

/* PHR_CC: Block */
/* Total length: 64 bytes (0x0040) */
typedef struct PHR_CC {
    s8 PRM1_VAL_1;    // len:    1 @ 0x0000, SEQ Prm1 Value 1
    u8 reserved_1[7]; // len:    7 @ 0x0001, implicit padding
    s8 PRM2_VAL_1;    // len:    1 @ 0x0008, SEQ Prm2 Value 1
    u8 reserved_2[7]; // len:    7 @ 0x0009, implicit padding
    s8 PRM3_VAL_1;    // len:    1 @ 0x0010, SEQ Prm3 Value 1
    u8 reserved_3[7]; // len:    7 @ 0x0011, implicit padding
    s8 PRM4_VAL_1;    // len:    1 @ 0x0018, SEQ Prm4 Value 1
    u8 reserved_4[7]; // len:    7 @ 0x0019, implicit padding
    s8 PRM5_VAL_1;    // len:    1 @ 0x0020, SEQ Prm5 Value 1
    u8 reserved_5[7]; // len:    7 @ 0x0021, implicit padding
    s8 PRM6_VAL_1;    // len:    1 @ 0x0028, SEQ Prm6 Value 1
    u8 reserved_6[7]; // len:    7 @ 0x0029, implicit padding
    s8 PRM7_VAL_1;    // len:    1 @ 0x0030, SEQ Prm7 Value 1
    u8 reserved_7[7]; // len:    7 @ 0x0031, implicit padding
    s8 PRM8_VAL_1;    // len:    1 @ 0x0038, SEQ Prm8 Value 1
    u8 reserved_8[7]; // len:    7 @ 0x0039, trailing padding
} PHR_CC;

/* PHR_NT: Block */
/* Total length: 96 bytes (0x0060) */
typedef struct PHR_NT {
    u8 MUTE_1;         // len:    1 @ 0x0000, Random Mute 1
    u8 reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    s8 NOTE_1;         // len:    1 @ 0x0010, Note 1
    u8 reserved_2[15]; // len:   15 @ 0x0011, implicit padding
    u8 VELO_1;         // len:    1 @ 0x0020, Velocity 1
    u8 reserved_3[15]; // len:   15 @ 0x0021, implicit padding
    s8 START_1;        // len:    1 @ 0x0030, Start 1
    u8 reserved_4[15]; // len:   15 @ 0x0031, implicit padding
    u8 END_1;          // len:    1 @ 0x0040, End 1
    u8 reserved_5[15]; // len:   15 @ 0x0041, implicit padding
    u8 SUB_STEP_1;     // len:    1 @ 0x0050, Sub Step 1
    u8 reserved_6[15]; // len:   15 @ 0x0051, trailing padding
} PHR_NT;

/* PHR: Block */
/* Total length: 192 bytes (0x00c0) */
typedef struct PHR {
    u8  SCALE;              // len:    1 @ 0x0000, Scale
    u8  LENGTH;             // len:    1 @ 0x0001, Step Length
    u8  FIRST;              // len:    1 @ 0x0002, First Step
    u8  FIRST_SW;           // len:    1 @ 0x0003, First Step Sw
    u8  LAST;               // len:    1 @ 0x0004, Last Step
    u8  LAST_SW;            // len:    1 @ 0x0005, Last Step Sw
    u16 PLAY_LENGTH;        // len:    2 @ 0x0006, Play Step Length
    s8  SHUFFLE;            // len:    1 @ 0x0008, Shuffle
    u8  DIRECTION;          // len:    1 @ 0x0009, Direction
    s8  TRANSPOSE;          // len:    1 @ 0x000a, Transpose
    s8  NEXT_CLIP;          // len:    1 @ 0x000b, Next Clip
    u8  QUANTIZE_TIGHTNESS; // len:    1 @ 0x000c, Quantize Tightness
    u8  MOTION_SW;          // len:    1 @ 0x000d, Motion Sw
    u16 PADDING1;           // len:    2 @ 0x000e, __padding
    u8  NOTE_MUTE_1;        // len:    1 @ 0x0010, Note Mute 1
    u8  reserved_1[127];    // len:  127 @ 0x0011, implicit padding
    s8  CC_NUM_1;           // len:    1 @ 0x0090, CC Number 1
    u8  reserved_2[15];     // len:   15 @ 0x0091, implicit padding
    u8  CC_MUTE_1;          // len:    1 @ 0x00a0, CC Mute 1
    u8  reserved_3[15];     // len:   15 @ 0x00a1, implicit padding
    u8  BEND_MUTE;          // len:    1 @ 0x00b0, Bend Mute
    u8  PADDING2[3];        // len:    3 @ 0x00b1, __padding
    u8  PADDING3[12];       // len:   12 @ 0x00b4, __padding
} PHR;

/* PJC_SCENE: SCENE */
/* Total length: 8 bytes (0x0008) */
typedef struct PJC_SCENE {
    s8 CLIP_1;        // len:    1 @ 0x0000,  1
    u8 reserved_1[7]; // len:    7 @ 0x0001, trailing padding
} PJC_SCENE;

/* PJC: Block */
/* Total length: 369 bytes (0x0171) */
typedef struct PJC {
    u8        NAME_1;                 // len:    1 @ 0x0000, Project Name 1
    u8        reserved_1[15];         // len:   15 @ 0x0001, implicit padding
    u16       TEMPO;                  // len:    2 @ 0x0010, Project Tempo
    u8        LEVEL;                  // len:    1 @ 0x0012, Project Level
    u8        PADDING1;               // len:    1 @ 0x0013, __padding
    u8        V_RSRV;                 // len:    1 @ 0x0014, Voice Reserve Layer(01$)
    u8        WAV_CUE_LEV;            // len:    1 @ 0x0015, WAV Cue Level
    u8        WAV_LEV;                // len:    1 @ 0x0016, WAV Level
    u8        EXT_SENS;               // len:    1 @ 0x0017, External Sens
    u8        EXT_CUE_LEV;            // len:    1 @ 0x0018, External Cue Level
    u8        EXT_LEV;                // len:    1 @ 0x0019, External Level
    u8        PC_CUE_LEV;             // len:    1 @ 0x001a, PC Cue Level
    u8        PC_LEV;                 // len:    1 @ 0x001b, PC Level
    u8        SEND_RETURN_POS;        // len:    1 @ 0x001c, Send Return Pos
    u8        SEND_LEV;               // len:    1 @ 0x001d, Send Level
    u8        RETURN_LEV;             // len:    1 @ 0x001e, Return Level
    u8        ASGN_CUE_LEV;           // len:    1 @ 0x001f, Assign Cue Level
    u8        ASGN_LEV;               // len:    1 @ 0x0020, Assign Level
    u8        EXT_STEREO;             // len:    1 @ 0x0021, EXT Stereo
    u8        SEND_STEREO;            // len:    1 @ 0x0022, Send Stereo
    u8        RETURN_STEREO;          // len:    1 @ 0x0023, Return Stereo
    u8        REC_POS;                // len:    1 @ 0x0024, Rec Source
    u8        SEQ_SCALE;              // len:    1 @ 0x0025, Base Scale
    u8        SEQ_LENGTH;             // len:    1 @ 0x0026, Base Step
    s8        SEQ_SHUFFLE;            // len:    1 @ 0x0027, Shuffle
    u8        SEQ_SHUFFLE_SRC;        // len:    1 @ 0x0028, Shuffle Source
    u8        SEQ_QUANTIZE_SW;        // len:    1 @ 0x0029, Quanzie Sw
    u8        SEQ_QUANTIZE_TIGHTNESS; // len:    1 @ 0x002a, Quanzie Tightness
    u8        SEQ_MOTION_SW;          // len:    1 @ 0x002b, Motion Switch
    s8        PAD_TRANSPOSE;          // len:    1 @ 0x002c, Pad Trancepose
    u32       PADDING2;               // len:    4 @ 0x002d, __padding
    s16       TUNE;                   // len:    2 @ 0x0031, Master Tune
    s8        KEY_SHIFT;              // len:    1 @ 0x0033, Master Key Shift
    u8        SCALE_TUNE_SW;          // len:    1 @ 0x0034, Scale Tune Sw
    u8        _reserved_;             // len:    1 @ 0x0035, reserved
    u8        REC_MEAS;               // len:    1 @ 0x0036, Rec Measure
    s8        REC_FADE;               // len:    1 @ 0x0037, Rec Fade
    u8        FIRST_SCENE;            // len:    1 @ 0x0038, First Scene
    u8        PADDING3[128];          // len:  128 @ 0x0039, __padding
    PJC_SCENE SCENE[8];               // len:   64 @ 0x00b9, SCENE
    s16       MASTER_REV_KNOB1_ASGN;  // len:    2 @ 0x00f9, Rev Knob1 Assign
    s16       MASTER_REV_KNOB2_ASGN;  // len:    2 @ 0x00fb, Rev Knob2 Assign
    s16       MASTER_DEL_KNOB1_ASGN;  // len:    2 @ 0x00fd, Dly Knob1 Assign
    s16       MASTER_DEL_KNOB2_ASGN;  // len:    2 @ 0x00ff, Dly Knob2 Assign
    s16       MASTER_MFXL_KNOB1_ASGN; // len:    2 @ 0x0101, MFX Knob1 Assign
    s16       MASTER_MFX_KNOB2_ASGN;  // len:    2 @ 0x0103, MFX Knob2 Assign
    u8        RHY_COMP_VALID;         // len:    1 @ 0x0105, Drum Comp Active
    u8        RHY_COMP_SW;            // len:    1 @ 0x0106, Drum Comp Sw
    u8        RHY_COMP_PART;          // len:    1 @ 0x0107, Drum Comp Track
    u8        EXT_PAN;                // len:    1 @ 0x0108, External Pan
    u8        PC_PAN;                 // len:    1 @ 0x0109, PC Pan
    u8        PAD_COLOR;              // len:    1 @ 0x010a, PAD Note Color
    u8        OCT_COLOR;              // len:    1 @ 0x010b, PAD OCT Color
    u8        CLIP_COLOR_PLAY;        // len:    1 @ 0x010c, Play Clip Color
    u8        CLIP_COLOR_STAY;        // len:    1 @ 0x010d, Stay Clip Color
    u8        MUTE_PAD_COLOR;         // len:    1 @ 0x010e, Mute Pad Color
    u8        STOP_PAD_COLOR;         // len:    1 @ 0x010f, Stop Pad Color
    u8        CHORD_COLOR_1;          // len:    1 @ 0x0110, PAD Chord Color 1
    u8        reserved_2[15];         // len:   15 @ 0x0111, implicit padding
    u8        PAD_NOTE_SCALE;         // len:    1 @ 0x0120, PAD NOTE SCALE
    u8        STYLE_D_COLOR;          // len:    1 @ 0x0121, Drum Style Color
    u8        STYLE_M_COLOR;          // len:    1 @ 0x0122, Melodic Style Color
    u8        PADDING4[78];           // len:   78 @ 0x0123, __padding
} PJC;

/* PJC2_CHORDSET: CHORDSET */
/* Total length: 8 bytes (0x0008) */
typedef struct PJC2_CHORDSET {
    u8 NOTE_1;        // len:    1 @ 0x0000,  1
    u8 reserved_1[7]; // len:    7 @ 0x0001, trailing padding
} PJC2_CHORDSET;

/* PJC2: Block */
/* Total length: 134 bytes (0x0086) */
typedef struct PJC2 {
    PJC2_CHORDSET CHORDSET[16]; // len:  128 @ 0x0000, CHORDSET
    u8            SAVED_PRDUCT; // len:    1 @ 0x0080, Saved Product
    u8            PADDING1;     // len:    1 @ 0x0081, __padding
    u16           SEVED_BUILD;  // len:    2 @ 0x0082, Saved Build Number
    u16           RPJ_PRM_REV;  // len:    2 @ 0x0084, Project Paramter Rev
} PJC2;

/* PJT: Block */
/* Total length: 256 bytes (0x0100) */
typedef struct PJT {
    u8  BANK_MSB;            // len:    1 @ 0x0000, Tone Bank Select MSB (CC#0)
    u8  BANK_LSB;            // len:    1 @ 0x0001, Tone Bank Select LSB (CC#32)
    u8  PC;                  // len:    1 @ 0x0002, Tone Program Change (PC)
    u8  PADDING1;            // len:    1 @ 0x0003, __padding
    s8  TRACK_TYPE;          // len:    1 @ 0x0004, Track Type
    u8  PTACH_SEL;           // len:    1 @ 0x0005, Sound Source
    u16 PADDING2;            // len:    2 @ 0x0006, __padding
    u8  SEQ_RUN;             // len:    1 @ 0x0008, Run
    u8  SEQ_TX_MIDI1;        // len:    1 @ 0x0009, Tx MIDI Out1
    u8  SEQ_TX_MIDI2;        // len:    1 @ 0x000a, Tx MIDI Out2
    u8  SEQ_TX_USBMIDI;      // len:    1 @ 0x000b, Tx USB MIDI
    u32 PADDING3;            // len:    4 @ 0x000c, __padding
    u8  MUTE_SW;             // len:    1 @ 0x0010, Mute Sw
    u8  CUE_SW;              // len:    1 @ 0x0011, Cue Sw
    u8  DUCK_SW;             // len:    1 @ 0x0012, Duck Sw
    u8  ASGN_SW;             // len:    1 @ 0x0013, Output Select
    u32 PADDING4;            // len:    4 @ 0x0014, __padding
    u8  SW;                  // len:    1 @ 0x0018, Part Switch
    u8  RX_PC_SW;            // len:    1 @ 0x0019, Receive Program Change
    u8  RX_BS_SW;            // len:    1 @ 0x001a, Receive Bank Select
    u8  RX_PB_SW;            // len:    1 @ 0x001b, Receive Pitch Bend
    u8  RX_PAF_SW;           // len:    1 @ 0x001c, Receive Poly Key Pressure
    u8  RX_CAF_SW;           // len:    1 @ 0x001d, Receive Channel Pressure
    u8  RX_MOD_SW;           // len:    1 @ 0x001e, Receive Modulation
    u8  RX_CC07_SW;          // len:    1 @ 0x001f, Receive Volume
    u8  RX_CC10_SW;          // len:    1 @ 0x0020, Receive Pan
    u8  RX_CC11_SW;          // len:    1 @ 0x0021, Receive Expression
    u8  RX_CC64_SW;          // len:    1 @ 0x0022, Receive Hold-1
    u8  PADDING5;            // len:    1 @ 0x0023, __padding
    u8  LED_COLOR;           // len:    1 @ 0x0024, LED Color
    u8  PADDING6[3];         // len:    3 @ 0x0025, __padding
    u8  LOOPER_MIDI_SYNC;    // len:    1 @ 0x0028, Sync
    u8  LOOPER_SPEED;        // len:    1 @ 0x0029, Speed
    u8  LOOPER_LOOP_PLAY;    // len:    1 @ 0x002a, Loop
    u8  PADDING7;            // len:    1 @ 0x002b, __padding
    u8  SEQ_DRUM_PAD_MUTE_1; // len:    1 @ 0x002c, Drum Pad Mute 1
    u8  reserved_1[15];      // len:   15 @ 0x002d, implicit padding
    u8  LOOPER_MUTE_SW;      // len:    1 @ 0x003c, Mute Sw
    u8  TX_MIDI_NOTE;        // len:    1 @ 0x003d, Tx MIDI Note
    u8  TX_MIDI_CC;          // len:    1 @ 0x003e, Tx MIDI Control Change
    u8  TX_MIDI_PC;          // len:    1 @ 0x003f, Tx MIDI Program Change
    u8  LEVEL;               // len:    1 @ 0x0040, Track Level
    s8  PAN;                 // len:    1 @ 0x0041, Pan
    s8  REV_OFST;            // len:    1 @ 0x0042, Reverb Send Offset
    s8  DLY_OFST;            // len:    1 @ 0x0043, Delay Send Offset
    u8  PADDING8[188];       // len:  188 @ 0x0044, __padding
} PJT;

/* PTL_AENV: Partial TVA Envelope */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_AENV {
    s8  T1_VSENS; // len:    1 @ 0x0000, TVA Env Time1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0001, TVA Env Time4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0002, TVA Env Time1
    u16 T2;       // len:    2 @ 0x0004, TVA Env Time2
    u16 T3;       // len:    2 @ 0x0006, TVA Env Time3
    u16 T4;       // len:    2 @ 0x0008, TVA Env Time4
    u16 L1;       // len:    2 @ 0x000a, TVA Env Level1
    u16 L2;       // len:    2 @ 0x000c, TVA Env Level2
    u16 L3;       // len:    2 @ 0x000e, TVA Env Level3
} PTL_AENV;

/* PTL_EQ: Partial EQ */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_EQ {
    s16 LO_GAIN;  // len:    2 @ 0x0000, EQ Low Gain
    s16 MID_GAIN; // len:    2 @ 0x0002, EQ Mid Gain
    s16 HI_GAIN;  // len:    2 @ 0x0004, EQ High Gain
    u16 LO_FREQ;  // len:    2 @ 0x0006, EQ Low Frequency
    u16 MID_FREQ; // len:    2 @ 0x0008, EQ Mid Frequency
    u16 HI_FREQ;  // len:    2 @ 0x000a, EQ High Frequency
    u8  MID_Q;    // len:    1 @ 0x000c, EQ Mid Q
    u8  SW;       // len:    1 @ 0x000d, EQ Switch
    u16 PADDING1; // len:    2 @ 0x000e, __padding
} PTL_EQ;

/* PTL_FENV: Partial TVF Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_FENV {
    s8  DEPTH;    // len:    1 @ 0x0000, TVF Env Depth
    u8  VCRV;     // len:    1 @ 0x0001, TVF Env Velocity Curve
    s8  VSENS;    // len:    1 @ 0x0002, TVF Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0003, TVF Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0004, TVF Env T4 Velocity Sens
    u8  PADDING1; // len:    1 @ 0x0005, __padding
    u16 T1;       // len:    2 @ 0x0006, TVF Env Time1
    u16 T2;       // len:    2 @ 0x0008, TVF Env Time2
    u16 T3;       // len:    2 @ 0x000a, TVF Env Time3
    u16 T4;       // len:    2 @ 0x000c, TVF Env Time4
    u16 L0;       // len:    2 @ 0x000e, TVF Env Level0
    u16 L1;       // len:    2 @ 0x0010, TVF Env Level1
    u16 L2;       // len:    2 @ 0x0012, TVF Env Level2
    u16 L3;       // len:    2 @ 0x0014, TVF Env Level3
    u16 L4;       // len:    2 @ 0x0016, TVF Env Level4
} PTL_FENV;

/* PTL_LFO_LFO: LFO */
/* Total length: 52 bytes (0x0034) */
typedef struct PTL_LFO_LFO {
    u8  FORM;           // len:    1 @ 0x0000, Waveform
    u8  RATE_SYNC;      // len:    1 @ 0x0001, Rate Sync
    u8  RATE_NOTE;      // len:    1 @ 0x0002, Rate (note)
    u8  STEP_MAX;       // len:    1 @ 0x0003, Step Size
    u16 RATE;           // len:    2 @ 0x0004, Rate
    s8  OFST;           // len:    1 @ 0x0006, Offset
    u8  RATE_DETN;      // len:    1 @ 0x0007, Rate Detune
    u16 DELAY;          // len:    2 @ 0x0008, Delay Time
    s8  DELAY_KF;       // len:    1 @ 0x000a, Delay Time Keyfolow
    u8  FADE_MODE;      // len:    1 @ 0x000b, Fade Mode
    u16 FADE;           // len:    2 @ 0x000c, Fade Time
    u8  KEY_TRIG;       // len:    1 @ 0x000e, Key Trigger
    s8  PIT_DEPTH;      // len:    1 @ 0x000f, Pitch Depth
    s8  TVF_DEPTH;      // len:    1 @ 0x0010, TVF Depth
    s8  TVA_DEPTH;      // len:    1 @ 0x0011, TVA Depth
    s8  PAN_DEPTH;      // len:    1 @ 0x0012, PAN Depth
    u8  PHASE_POS;      // len:    1 @ 0x0013, Phase Position
    s8  STEP_1;         // len:    1 @ 0x0014, Step 1
    u8  reserved_1[15]; // len:   15 @ 0x0015, implicit padding
    u8  STEP_CURVE_1;   // len:    1 @ 0x0024, Step Curve 1
    u8  reserved_2[15]; // len:   15 @ 0x0025, trailing padding
} PTL_LFO_LFO;

/* PTL_LFO: Partial LFO */
/* Total length: 104 bytes (0x0068) */
typedef struct PTL_LFO {
    PTL_LFO_LFO LFO[2]; // len:  104 @ 0x0000, LFO
} PTL_LFO;

/* PTL_PENV: Partial Pitch Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_PENV {
    s8  DEPTH;    // len:    1 @ 0x0000, Pitch Env Depth
    s8  VSENS;    // len:    1 @ 0x0001, Pitch Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0002, Pitch Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0003, Pitch Env T4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0004, Pitch Env Time1
    u16 T2;       // len:    2 @ 0x0006, Pitch Env Time2
    u16 T3;       // len:    2 @ 0x0008, Pitch Env Time3
    u16 T4;       // len:    2 @ 0x000a, Pitch Env Time4
    s16 L0;       // len:    2 @ 0x000c, Pitch Env Level0
    s16 L1;       // len:    2 @ 0x000e, Pitch Env Level1
    s16 L2;       // len:    2 @ 0x0010, Pitch Env Level2
    s16 L3;       // len:    2 @ 0x0012, Pitch Env Level3
    s16 L4;       // len:    2 @ 0x0014, Pitch Env Level4
    u8  VCRV;     // len:    1 @ 0x0016, Pitch Env Velocity Curve
    u8  PADDING1; // len:    1 @ 0x0017, __padding
} PTL_PENV;

/* RCMP: Block */
/* Total length: 8 bytes (0x0008) */
typedef struct RCMP {
    u8 SW;        // len:    1 @ 0x0000, Comp Sw
    u8 ATTCK;     // len:    1 @ 0x0001, Comp Attack Time
    u8 RELEASE;   // len:    1 @ 0x0002, Comp Release Time
    s8 THRESHOLD; // len:    1 @ 0x0003, Comp Threshold
    u8 RATIO;     // len:    1 @ 0x0004, Comp Ratio
    u8 KNEE;      // len:    1 @ 0x0005, Comp Knee
    s8 POSTGAIN;  // len:    1 @ 0x0006, Comp Output Gain
    u8 OUT_ASGN;  // len:    1 @ 0x0007, Comp Output Assign
} RCMP;

/* SC: Block */
/* Total length: 256 bytes (0x0100) */
typedef struct SC {
    u8  KNOB_CATCH;                 // len:    1 @ 0x0000, Knob Mode
    u8  PAD_CURV;                   // len:    1 @ 0x0001, Pad Curve Type
    u8  PAD_THRESHOLD;              // len:    1 @ 0x0002, Pad Threshold
    u8  PAD_WEAKINPUT;              // len:    1 @ 0x0003, Weak Beat Input Way
    u8  MIDI_SYNC;                  // len:    1 @ 0x0004, MIDI Sync
    u8  MIDI_SYNC_OUT1;             // len:    1 @ 0x0005, MIDI Sync Out1
    u8  MIDI_SYNC_OUT2;             // len:    1 @ 0x0006, MIDI Sync Out2
    u8  MIDI_SYNC_OUT_USB;          // len:    1 @ 0x0007, MIDI Sync Out USB
    u8  MIDI_RX_STARTSTOP;          // len:    1 @ 0x0008, RX Start Stop
    u8  MIDI_RX_STARTSTOP_USB;      // len:    1 @ 0x0009, RX Start Stop USB
    u8  PADDING1;                   // len:    1 @ 0x000a, __padding
    u8  MIDI_CTRL_CH;               // len:    1 @ 0x000b, Control Channel
    u8  MIDI_TRK_CH_1;              // len:    1 @ 0x000c, Track Channel 1
    u8  reserved_1[7];              // len:    7 @ 0x000d, implicit padding
    u8  PAD_TRIG_SENS;              // len:    1 @ 0x0014, Pad Trigger Sensitivity
    u8  PAD_GAIN;                   // len:    1 @ 0x0015, Pad Gain
    u8  MIDI_CTRL_TX_OUT1;          // len:    1 @ 0x0016, Control Tx MIDI OUT1
    u8  MIDI_CTRL_TX_OUT2;          // len:    1 @ 0x0017, Control Tx MIDI OUT2
    u8  MIDI_CTRL_TX_USB;           // len:    1 @ 0x0018, Control Tx USB MIDI
    u8  MIDI_CTRL_RX;               // len:    1 @ 0x0019, Control Rx
    u8  USB_DRIVER;                 // len:    1 @ 0x001a, USB Driver
    u8  PADDING2[89];               // len:   89 @ 0x001b, __padding
    u8  SYS_CTRL_SRC_1;             // len:    1 @ 0x0074, System Control Source(011)
    u8  reserved_2[3];              // len:    3 @ 0x0075, implicit padding
    u8  LCD_CNT;                    // len:    1 @ 0x0078, LCD Contrast
    u8  LCD_BRT;                    // len:    1 @ 0x0079, LCD Backlight
    u8  LED_BRIGHT;                 // len:    1 @ 0x007a, LED Brightness
    u8  LED_GLOW;                   // len:    1 @ 0x007b, LED Glow
    u8  PADDING3;                   // len:    1 @ 0x007c, __padding
    u8  AUTO_OFF;                   // len:    1 @ 0x007d, Auto Poweroff
    u8  DEMO_WAITTIME;              // len:    1 @ 0x007e, DEMO Mode
    u8  BACKLIGHT_TIMER;            // len:    1 @ 0x007f, LCD Backlight Timer
    s8  OUT_GAIN;                   // len:    1 @ 0x0080, Output Gain
    u8  APLAY_LVL;                  // len:    1 @ 0x0081, Audio Player Level
    u8  USB_MIX_SEL;                // len:    1 @ 0x0082, USB Mix Select
    u8  CUE_SEL;                    // len:    1 @ 0x0083, Output Cue to Mix Out
    u8  DEV_ID;                     // len:    1 @ 0x0084, Device ID
    u8  SOFT_THRU;                  // len:    1 @ 0x0085, Soft Through 1
    u8  SOFT_THRU2;                 // len:    1 @ 0x0086, Soft Through 2
    u8  USB_MIDI_THRU;              // len:    1 @ 0x0087, USB-MIDI Thru 1
    u8  USB_MIDI_THRU2;             // len:    1 @ 0x0088, USB-MIDI Thru 2
    u8  MIDI_STEPREC;               // len:    1 @ 0x0089, Edit Note
    u16 PADDING4;                   // len:    2 @ 0x008a, __padding
    u8  RX_PC;                      // len:    1 @ 0x008c, Receive Program Change
    u8  RX_BS;                      // len:    1 @ 0x008d, Receive Bank Select
    u8  RX_EXC;                     // len:    1 @ 0x008e, Receive Exclusive
    u8  TX_EDIT;                    // len:    1 @ 0x008f, Transmit Edit Data
    u8  TR_REC_VELO;                // len:    1 @ 0x0090, TR Rec Default Velocity
    u8  TONE_EDIT_KNOB_MODE;        // len:    1 @ 0x0091, Tone Edit Knob Mode
    u8  LOAD_PROJ;                  // len:    1 @ 0x0092, Load Project
    u8  REC_QUANTIZE;               // len:    1 @ 0x0093, Rec Quantize
    u8  METRO_TYPE;                 // len:    1 @ 0x0094, Metronome Type
    u8  METRO_LEV;                  // len:    1 @ 0x0095, Metronome Level
    s8  SEQ_REC_TIMING;             // len:    1 @ 0x0096, Rec Timing
    u8  REC_TRIGGER;                // len:    1 @ 0x0097, Rec Trigger
    u8  METRO_OUT_SEL;              // len:    1 @ 0x0098, Metronome Position
    u8  WAV_AUTO_PREVIEW;           // len:    1 @ 0x0099, Wav Auto Preview Switch
    u8  MIDI_RX_AUTO_CH;            // len:    1 @ 0x009a, MIDI Rx Auto Channel
    u8  REC_TRIGGER_CLOCK_COUNT_IN; // len:    1 @ 0x009b, Rec Trigger Count In Sw
    u8  PADDING5[40];               // len:   40 @ 0x009c, __padding
    u8  MIC_PHANTOM;                // len:    1 @ 0x00c4, Phantom Power Sw
    u8  EXT_SEL;                    // len:    1 @ 0x00c5, External Input
    u8  COUNT_IN_SW;                // len:    1 @ 0x00c6, Count-in
    u8  LINE_GAIN;                  // len:    1 @ 0x00c7, Line Gain
    u8  EXT_CHO_SEND;               // len:    1 @ 0x00c8, EXT Delay Send Level
    u8  EXT_REV_SEND;               // len:    1 @ 0x00c9, EXT Reverb Send Level
    u8  PADDING6[54];               // len:   54 @ 0x00ca, __padding
} SC;

/* SCMP: Block */
/* Total length: 24 bytes (0x0018) */
typedef struct SCMP {
    u8 SW;              // len:    1 @ 0x0000, Sw
    u8 LO_ATTACK;       // len:    1 @ 0x0001, Low Attack Time
    u8 LO_RELEASE;      // len:    1 @ 0x0002, Low Release Time
    s8 LO_THRES;        // len:    1 @ 0x0003, Low Threshold
    u8 LO_RATIO;        // len:    1 @ 0x0004, Low Ratio
    u8 LO_KNEE;         // len:    1 @ 0x0005, Low Knee
    s8 LO_GAIN;         // len:    1 @ 0x0006, Low Output Gain
    u8 MI_ATTACK;       // len:    1 @ 0x0007, Mid Attack Time
    u8 MI_RELEASE;      // len:    1 @ 0x0008, Mid Release Time
    s8 MI_THRES;        // len:    1 @ 0x0009, Mid Threshold
    u8 MI_RATIO;        // len:    1 @ 0x000a, Mid Ratio
    u8 MI_KNEE;         // len:    1 @ 0x000b, Mid Knee
    s8 MI_GAIN;         // len:    1 @ 0x000c, Mid Output Gain
    u8 HI_ATTACK;       // len:    1 @ 0x000d, High Attack Time
    u8 HI_RELEASE;      // len:    1 @ 0x000e, High Release Time
    s8 HI_THRES;        // len:    1 @ 0x000f, High Threshold
    u8 HI_RATIO;        // len:    1 @ 0x0010, High Ratio
    u8 HI_KNEE;         // len:    1 @ 0x0011, High Knee
    s8 HI_GAIN;         // len:    1 @ 0x0012, High Output Gain
    u8 LO_SPLIT_FREQ;   // len:    1 @ 0x0013, Split Freq Low
    u8 HI_SPLIT_FREQ;   // len:    1 @ 0x0014, Split Freq High
    u8 LO_RELEASE_SYNC; // len:    1 @ 0x0015, Low Release Sync
    u8 MI_RELEASE_SYNC; // len:    1 @ 0x0016, Mid Release Sync
    u8 HI_RELEASE_SYNC; // len:    1 @ 0x0017, High Release Sync
} SCMP;

/* SCT: Block */
/* Total length: 64 bytes (0x0040) */
typedef struct SCT {
    u8  NAME_1;         // len:    1 @ 0x0000, Section Name 1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  LENGTH;         // len:    1 @ 0x0010, Section Length
    u8  COLOR;          // len:    1 @ 0x0011, LED Color
    u16 PADDING1;       // len:    2 @ 0x0012, __padding
    s8  CLIP_1;         // len:    1 @ 0x0014,  1
    u8  reserved_2[7];  // len:    7 @ 0x0015, implicit padding
    u8  PADDING2[36];   // len:   36 @ 0x001c, __padding
} SCT;

/* SEQ: Block */
/* Total length: 16 bytes (0x0010) */
typedef struct SEQ {
    s8 IN_GAIN;   // len:    1 @ 0x0000, EQ Input Gain
    s8 LO_GAIN;   // len:    1 @ 0x0001, EQ Low Gain
    s8 MID1_GAIN; // len:    1 @ 0x0002, EQ Mid1 Gain
    s8 MID2_GAIN; // len:    1 @ 0x0003, EQ Mid2 Gain
    s8 MID3_GAIN; // len:    1 @ 0x0004, EQ Mid3 Gain
    s8 HI_GAIN;   // len:    1 @ 0x0005, EQ High Gain
    u8 LO_FREQ;   // len:    1 @ 0x0006, EQ Low Frequency
    u8 MID1_FREQ; // len:    1 @ 0x0007, EQ Mid1 Frequency
    u8 MID2_FREQ; // len:    1 @ 0x0008, EQ Mid2 Frequency
    u8 MID3_FREQ; // len:    1 @ 0x0009, EQ Mid3 Frequency
    u8 HI_FREQ;   // len:    1 @ 0x000a, EQ High Frequency
    u8 MID1_Q;    // len:    1 @ 0x000b, EQ Mid1 Q
    u8 MID2_Q;    // len:    1 @ 0x000c, EQ Mid2 Q
    u8 MID3_Q;    // len:    1 @ 0x000d, EQ Mid3 Q
    u8 SW;        // len:    1 @ 0x000e, EQ Sw
    u8 PADDING1;  // len:    1 @ 0x000f, __padding
} SEQ;

/* SH: System Chorus */
/* Total length: 48 bytes (0x0030) */
typedef struct SH {
    u8  sw;             // len:    1 @ 0x0000, Switch
    u8  choType;        // len:    1 @ 0x0001, Chorus Type
    u8  level;          // len:    1 @ 0x0002, Chorus Level
    u8  PADDING1;       // len:    1 @ 0x0003, __padding
    u8  REV_SEND;       // len:    1 @ 0x0004, Reverb Send Level
    u8  PADDING2[3];    // len:    3 @ 0x0005, __padding
    s16 param_1;        // len:    2 @ 0x0008, Chorus Parameter 1
    u8  reserved_1[38]; // len:   38 @ 0x000a, trailing padding
} SH;

/* SLIM: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct SLIM {
    u8 SW;           // len:    1 @ 0x0000, Lim Sw
    u8 ATTACK;       // len:    1 @ 0x0001, Lim Attack Time
    u8 RELEASE;      // len:    1 @ 0x0002, Lim Release Time
    s8 THRESHOLD;    // len:    1 @ 0x0003, Lim Threshold
    u8 RATIO;        // len:    1 @ 0x0004, Lim Ratio
    u8 KNEE;         // len:    1 @ 0x0005, Lim Knee
    s8 POSTGAIN;     // len:    1 @ 0x0006, Lim Output Gain
    u8 RELEASE_SYNC; // len:    1 @ 0x0007, Lim Release Sync
    s8 CEILING;      // len:    1 @ 0x0008, Lim Ceiling
    u8 PADDING1[3];  // len:    3 @ 0x0009, __padding
} SLIM;

/* SNG_CMN: Block */
/* Total length: 64 bytes (0x0040) */
typedef struct SNG_CMN {
    u8  NAME_1;         // len:    1 @ 0x0000, Song Name 1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  LEVEL;          // len:    1 @ 0x0010, Song Level
    s8  TRANSPOSE;      // len:    1 @ 0x0011, Transpose
    u16 PADDING1;       // len:    2 @ 0x0012, __padding
    u8  TR1_TRANS_SW;   // len:    1 @ 0x0014, Track1 Transpose Sw
    u8  TR2_TRANS_SW;   // len:    1 @ 0x0015, Track2 Transpose Sw
    u8  TR3_TRANS_SW;   // len:    1 @ 0x0016, Track3 Transpose Sw
    u8  TR4_TRANS_SW;   // len:    1 @ 0x0017, Track4 Transpose Sw
    u8  TR5_TRANS_SW;   // len:    1 @ 0x0018, Track5 Transpose Sw
    u8  TR6_TRANS_SW;   // len:    1 @ 0x0019, Track6 Transpose Sw
    u8  TR7_TRANS_SW;   // len:    1 @ 0x001a, Track7 Transpose Sw
    u8  TR8_TRANS_SW;   // len:    1 @ 0x001b, Track8 Transpose Sw
    u8  TAG_KEY;        // len:    1 @ 0x001c, Key
    u8  TAG_SCALE;      // len:    1 @ 0x001d, Scale
    u16 PADDING2;       // len:    2 @ 0x001e, __padding
    s8  SECT_TYPE_1;    // len:    1 @ 0x0020, Section Type 1
    u8  reserved_2[15]; // len:   15 @ 0x0021, implicit padding
    u8  PADDING3[16];   // len:   16 @ 0x0030, __padding
} SNG_CMN;

/* SNG: Block */
/* Total length: 16 bytes (0x0010) */
typedef struct SNG {
    s8 SCT_NUM;      // len:    1 @ 0x0000, Section Number
    s8 TRANSPOSE;    // len:    1 @ 0x0001, Transpose
    u8 PADDING1[14]; // len:   14 @ 0x0002, __padding
} SNG;

/* SPATH: Block */
/* Total length: 256 bytes (0x0100) */
typedef struct SPATH {
    u8 PROJECT_PASS_1;  // len:    1 @ 0x0000, Project Path 1
    u8 reserved_1[255]; // len:  255 @ 0x0001, trailing padding
} SPATH;

/* STP_SEQ_MUTE_TRK: SEQ_MUTE_TRK */
/* Total length: 12 bytes (0x000c) */
typedef struct STP_SEQ_MUTE_TRK {
    u8 PRM_1;         // len:    1 @ 0x0000, SEQ Prm Mute 1
    u8 reserved_1[7]; // len:    7 @ 0x0001, implicit padding
    u8 BEND;          // len:    1 @ 0x0008, SEQ Bend Mute
    u8 PADDING1[3];   // len:    3 @ 0x0009, __padding
} STP_SEQ_MUTE_TRK;

/* STP_TRK: TRK */
/* Total length: 4 bytes (0x0004) */
typedef struct STP_TRK {
    u8 TRK_CUE_LEV; // len:    1 @ 0x0000, Cue Level
    u8 TRK_MIX_LEV; // len:    1 @ 0x0001, Mix Level
    u8 TRK_PAN;     // len:    1 @ 0x0002, Pan
    u8 PADDING1;    // len:    1 @ 0x0003, __padding
} STP_TRK;

/* STP: Block */
/* Total length: 506 bytes (0x01fa) */
typedef struct STP {
    u8               CUR_TRACK;           // len:    1 @ 0x0000, Current Track
    u8               LEVEL;               // len:    1 @ 0x0001, Master Level
    u16              TEMPO;               // len:    2 @ 0x0002, Master Tempo
    u8               APP_MODE;            // len:    1 @ 0x0004, Application mode
    u8               REC_STATE;           // len:    1 @ 0x0005, Rec Switch State
    u8               REC_QUANTIZE;        // len:    1 @ 0x0006, Rec Quantize
    u8               REC_CLEAR;           // len:    1 @ 0x0007, Rec Clear
    s8               STEP_SEL;            // len:    1 @ 0x0008, Select Step
    u8               TRK_SEL;             // len:    1 @ 0x0009, Select Part
    u8               TFX_SEL;             // len:    1 @ 0x000a, Select TFX
    u8               MEASURE_POS;         // len:    1 @ 0x000b, Measure Position
    u8               CUR_CLIP_1;          // len:    1 @ 0x000c, Current Clip 1
    u8               reserved_1[7];       // len:    7 @ 0x000d, implicit padding
    s8               CHANGE_CLIP_1;       // len:    1 @ 0x0014, Change Clip 1
    u8               reserved_2[7];       // len:    7 @ 0x0015, implicit padding
    s8               CHANGING_CLIP_1;     // len:    1 @ 0x001c, Changing Clip 1
    u8               reserved_3[7];       // len:    7 @ 0x001d, implicit padding
    u8               SEQ_RUN_1;           // len:    1 @ 0x0024, SEQ Run 1
    u8               reserved_4[7];       // len:    7 @ 0x0025, implicit padding
    u8               SEQ_STEP_PROGRESS_1; // len:    1 @ 0x002c, Progress Step 1
    u8               reserved_5[7];       // len:    7 @ 0x002d, implicit padding
    u8               SEQ_STEP_CUR_1;      // len:    1 @ 0x0034, Current Step 1
    u8               reserved_6[7];       // len:    7 @ 0x0035, implicit padding
    u8               SEQ_MASTER_STEP_CUR; // len:    1 @ 0x003c, Master Current Step
    u8               SEQ_MASTER_RUN;      // len:    1 @ 0x003d, Master Run
    u8               SEQ_MOTION_REC;      // len:    1 @ 0x003e, Motion Rec SW
    u8               PADDING1;            // len:    1 @ 0x003f, __padding
    STP_TRK          TRK[8];              // len:   32 @ 0x0040, TRK
    u8               EXT_SEL;             // len:    1 @ 0x0060, External Input
    u8               PHONES_LEV;          // len:    1 @ 0x0061, Phones Level
    u8               WAV_CUE_SW;          // len:    1 @ 0x0062, WAV Cue Sw
    u8               EXT_CUE_SW;          // len:    1 @ 0x0063, External Cue Sw
    u8               PC_CUE_SW;           // len:    1 @ 0x0064, PC Cue Sw
    u8               ASGN_CUE_SW;         // len:    1 @ 0x0065, Assign Cue Sw
    u8               PHONES_CUE_SW;       // len:    1 @ 0x0066, Phones Cue Sw
    u8               MIX_OUT_MUTE;        // len:    1 @ 0x0067, Mix Out Mute
    u8               MIX_OUT_LEV;         // len:    1 @ 0x0068, Mix Out Level
    u8               PADDING2[3];         // len:    3 @ 0x0069, __padding
    u8               REC_MIDI_SYNC;       // len:    1 @ 0x006c, Rec MIDI Sync
    u8               REC_TM_STRETCH;      // len:    1 @ 0x006d, Rec Time Stretch
    u8               REC_TM_WINDOW;       // len:    1 @ 0x006e, Rec Stretch Window
    u8               PADDING3;            // len:    1 @ 0x006f, __padding
    s8               REC_PITCH_CHRM;      // len:    1 @ 0x0070, Rec Pitch Chromatic
    s8               REC_PITCH_FINE;      // len:    1 @ 0x0071, Rec Pitch Fine
    u16              REC_PITCH_BEND;      // len:    2 @ 0x0072, Rec Pitch Bend
    u8               REC_SPEED;           // len:    1 @ 0x0074, Rec Speed
    u8               REC_SHUFFLE_POS;     // len:    1 @ 0x0075, Rec Shuffle Pos
    u8               REC_SHUFFLE_RATIO;   // len:    1 @ 0x0076, Rec Shuffle Ratio
    u8               REC_LOOP;            // len:    1 @ 0x0077, Rec Loop Play
    u8               REC_STANDBY;         // len:    1 @ 0x0078, Rec Standby
    u8               REC_PLAY;            // len:    1 @ 0x0079, Rec Play/Stop
    u8               REC_REVERSE;         // len:    1 @ 0x007a, Rec Reverse
    s8               REC_CLIP;            // len:    1 @ 0x007b, Rec Clip
    u32              PADDING4;            // len:    4 @ 0x007c, __padding
    u16              REC_START_OFST;      // len:    2 @ 0x0080, Rec Start Ofst
    s16              REC_END_OFST;        // len:    2 @ 0x0082, Rec End Ofst
    u8               REC_START_STEP;      // len:    1 @ 0x0084, Rec Start Step
    s8               REC_LAST_STEP;       // len:    1 @ 0x0085, Rec Last Step
    u8               REC_STEP_LENGTH;     // len:    1 @ 0x0086, Rec Step Length
    u8               SEQ_STEPINPUT;       // len:    1 @ 0x0087, Step Input
    u16              SAMPLE_EDIT_ZOOM;    // len:    2 @ 0x0088, Sample Edit Zoom
    STP_SEQ_MUTE_TRK SEQ_MUTE_TRK[8];     // len:   96 @ 0x008a, SEQ_MUTE_TRK
    u8               INT_EXT_CLK;         // len:    1 @ 0x00ea, Clock Src
    s8               PAD_OCT_SHIFT;       // len:    1 @ 0x00eb, Pad Oct Shift
    u8               VALUE_KNOB_MODE;     // len:    1 @ 0x00ec, VALUE AS TEMPO or INPUT
    u8               METRO_SW;            // len:    1 @ 0x00ed, Metronome Switch
    u8               METRO_FOR_REC;       // len:    1 @ 0x00ee, Metronome For Rec
    s8               REC_NORMALIZE_LEVEL; // len:    1 @ 0x00ef, Sample Normalize Level
    u8               REC_SLICE_LEVEL;     // len:    1 @ 0x00f0, Sample Slice Level
    u8               REC_SLICE_POINT;     // len:    1 @ 0x00f1, Sample Slice Point
    u8               REC_SLICE_PREVIEW;   // len:    1 @ 0x00f2, Sample Slice Preview
    u8               DUMMY_PUSH;          // len:    1 @ 0x00f3, Dummy Label For Edit
    u8               COUNT_IN_SW;         // len:    1 @ 0x00f4, Count-in
    u8               PADDING5;            // len:    1 @ 0x00f5, __padding
    u8               BRDG_SW;             // len:    1 @ 0x00f6, Bridger Sw
    u8               BRDG_XFADE;          // len:    1 @ 0x00f7, Bridger Fader
    u8               MIC_SW;              // len:    1 @ 0x00f8, Mic Sw
    u8               REC_PRE_EM_SW;       // len:    1 @ 0x00f9, Rec Pre-Emphasis Sw
    u8               VOCAL_LEVEL_CH_1;    // len:    1 @ 0x00fa, Vocal Channel Level 1
    u8               reserved_7[15];      // len:   15 @ 0x00fb, implicit padding
    u8               MIXDOWN_SW;          // len:    1 @ 0x010a, Mixdown Sw
    u8               MIXDOWN_FADE;        // len:    1 @ 0x010b, Mixdown Fade
    u8               KBDARP_SW;           // len:    1 @ 0x010c, Kbd Arp Sw
    u8               MICRO_PHRS_SW;       // len:    1 @ 0x010d, Micro Phrase Sw
    u8               SONG_REC_STATE;      // len:    1 @ 0x010e, Song Rec State
    u8               PAD_MODE_SEQ;        // len:    1 @ 0x010f, Pad Mode SEQ
    u8               PAD_MODE_SCT;        // len:    1 @ 0x0110, Pad Mode SCT
    u8               PAD_MODE_SNG;        // len:    1 @ 0x0111, Pad Mode SNG
    u8               VCLP_PATCH_NUM;      // len:    1 @ 0x0112, VP Patch Number
    u8               PADDING6[3];         // len:    3 @ 0x0113, __padding
    u8               PADDING7[228];       // len:  228 @ 0x0116, __padding
} STP;

/* SV: System Reverb */
/* Total length: 44 bytes (0x002c) */
typedef struct SV {
    u8  sw;             // len:    1 @ 0x0000, Switch
    u8  revType;        // len:    1 @ 0x0001, Reverb Type
    u8  level;          // len:    1 @ 0x0002, Reverb Level
    u8  PADDING1;       // len:    1 @ 0x0003, __padding
    s16 param_1;        // len:    2 @ 0x0004, Reverb Parameter 1
    u8  reserved_1[38]; // len:   38 @ 0x0006, trailing padding
} SV;

/* TAKE: Block */
/* Total length: 28 bytes (0x001c) */
typedef struct TAKE {
    u8  NAME_1;          // len:    1 @ 0x0000,  1
    u8  reserved_1[15];  // len:   15 @ 0x0001, implicit padding
    s16 SAMPLE_ID;       // len:    2 @ 0x0010, User Sample ID
    u16 PADDING1;        // len:    2 @ 0x0012, __padding
    u16 START_ADRS;      // len:    2 @ 0x0014, Start Address
    u16 END_ADRS;        // len:    2 @ 0x0016, End Address
    u8  LEVEL;           // len:    1 @ 0x0018, Level
    u8  OUTPUT_ASGN;     // len:    1 @ 0x0019, Output Assign
    s8  CONTROL_DATA_ID; // len:    1 @ 0x001a, Control Data ID
    u8  MUTE;            // len:    1 @ 0x001b, Mute
} TAKE;

/* TCMP: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct TCMP {
    u8  POS;       // len:    1 @ 0x0000, Comp Position
    u8  SW;        // len:    1 @ 0x0001, Comp Sw
    u8  ATTACK;    // len:    1 @ 0x0002, Comp Attack Time
    u8  RELEASE;   // len:    1 @ 0x0003, Comp Release Time
    s8  THRESHOLD; // len:    1 @ 0x0004, Comp Threshold
    u8  RATIO;     // len:    1 @ 0x0005, Comp Ratio
    u8  KNEE;      // len:    1 @ 0x0006, Comp Knee
    s8  POSTGAIN;  // len:    1 @ 0x0007, Comp Output Gain
    u32 PADDING1;  // len:    4 @ 0x0008, __padding
} TCMP;

/* UserSampleCmn: Block */
/* Total length: 64 bytes (0x0040) */
typedef struct UserSampleCmn {
    u8 NAME_1;         // len:    1 @ 0x0000, Project Name 1
    u8 reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8 EXPORT_LOCK;    // len:    1 @ 0x0010, Export Lock
    u8 PADDING1[3];    // len:    3 @ 0x0011, __padding
    u8 PADDING2[44];   // len:   44 @ 0x0014, __padding
} UserSampleCmn;

/* UserSampleModify: Block */
/* Total length: 14 bytes (0x000e) */
typedef struct UserSampleModify {
    u8  LOOP_MODE;        // len:    1 @ 0x0000, Loop Mode
    u8  LEVEL;            // len:    1 @ 0x0001, Level
    s16 PIT_FINE;         // len:    2 @ 0x0002, Fine Tune
    u8  GAIN;             // len:    1 @ 0x0004, Gain
    u8  ORG_KEY;          // len:    1 @ 0x0005, Original Key
    u16 PADDING1;         // len:    2 @ 0x0006, __padding
    u16 START_POINT;      // len:    2 @ 0x0008, Start Point
    u16 LOOP_START_POINT; // len:    2 @ 0x000a, Loop Start Point
    u16 END_POINT;        // len:    2 @ 0x000c, End Point
} UserSampleModify;

/* VCLP: Block */
/* Total length: 128 bytes (0x0080) */
typedef struct VCLP {
    u8  POSITION;            // len:    1 @ 0x0000, Position
    u8  SW;                  // len:    1 @ 0x0001, Sw
    u8  KEY_AUTO;            // len:    1 @ 0x0002, Auto
    u8  KEY_KEY;             // len:    1 @ 0x0003, Key
    u8  KEY_RECG_SRC;        // len:    1 @ 0x0004, Recg Src
    u8  KEY_MIDI2CHORD;      // len:    1 @ 0x0005, MIDI>Chord
    u8  KEY_M2C_ZONE_LOWER;  // len:    1 @ 0x0006, Zone Lwr
    u8  KEY_M2C_ZONE_UPPER;  // len:    1 @ 0x0007, Zone Upr
    u8  KEY_BEND_RANGE;      // len:    1 @ 0x0008, Bend Range
    u8  MST_NS;              // len:    1 @ 0x0009, Noise Threshold
    u8  MST_LEVEL;           // len:    1 @ 0x000a, Level
    u8  EH_SW;               // len:    1 @ 0x000b, Switch
    u8  EH_ENHANCE;          // len:    1 @ 0x000c, Enhance
    u8  EH_COMPRESS;         // len:    1 @ 0x000d, Compress
    u8  EH_DEESSER;          // len:    1 @ 0x000e, De-Esser
    u8  EQ_SW;               // len:    1 @ 0x000f, Switch
    s8  EQ_LOW_GAIN;         // len:    1 @ 0x0010, Low Gain
    s8  EQ_HIGH_GAIN;        // len:    1 @ 0x0011, High Gain
    s8  EQ_LEVEL;            // len:    1 @ 0x0012, Level
    s8  EQ_LMID_GAIN;        // len:    1 @ 0x0013, Low-Mid Gain
    u8  EQ_LMID_FREQ;        // len:    1 @ 0x0014, Low-Mid Freq
    u8  EQ_LMID_Q;           // len:    1 @ 0x0015, Low-Mid Q
    s8  EQ_HMID_GAIN;        // len:    1 @ 0x0016, High-Mid Gain
    u8  EQ_HMID_FREQ;        // len:    1 @ 0x0017, High-Mid Freq
    u8  EQ_HMID_Q;           // len:    1 @ 0x0018, High-Mid Q
    u8  EQ_LOW_CUT;          // len:    1 @ 0x0019, Low Cut
    u8  EQ_HIGH_CUT;         // len:    1 @ 0x001a, High Cut
    u8  PADDING1;            // len:    1 @ 0x001b, __padding
    u8  PCR_SW;              // len:    1 @ 0x001c, Switch
    u8  PCR_TYPE;            // len:    1 @ 0x001d, Tune Type
    u8  PCR_SCALE;           // len:    1 @ 0x001e, Tune Scale
    u8  PCR_NOTE;            // len:    1 @ 0x001f, Tune Robot Note
    s8  PCR_PAN;             // len:    1 @ 0x0020, Tune Pan
    s8  PCR_FORMANT;         // len:    1 @ 0x0021, Tune Formant
    u8  PCR_SHIFT;           // len:    1 @ 0x0022, Tune Shift
    u8  PCR_SPEED;           // len:    1 @ 0x0023, Tune Speed
    u8  PCR_STABILITY;       // len:    1 @ 0x0024, Tune Stability
    u8  PCR_MIDI2PCR;        // len:    1 @ 0x0025, Tune MIDI
    u8  PCR_M2P_ZONE_LOWER;  // len:    1 @ 0x0026, Tune Zone Lower
    u8  PCR_M2P_ZONE_UPPER;  // len:    1 @ 0x0027, Tune Zone Upper
    u8  HRM_SW;              // len:    1 @ 0x0028, Switch
    u8  HRM_LEVEL;           // len:    1 @ 0x0029, Hrm Effect Level
    u8  HRM_DIRECT;          // len:    1 @ 0x002a, Hrm Direct Level
    u8  HRM_HIGH_NOTE_SENS;  // len:    1 @ 0x002b, High Note Sens
    u8  HRM1_VOICE_AUTO;     // len:    1 @ 0x002c, Hrm1 Voice Auto
    u8  HRM1_VOICE_MANUAL;   // len:    1 @ 0x002d, Hrm1 Voice Manual
    s8  HRM1_PAN;            // len:    1 @ 0x002e, Hrm1 Pan
    u8  HRM1_LEVEL;          // len:    1 @ 0x002f, Hrm1 Level
    u8  HRM1_DELAY;          // len:    1 @ 0x0030, Hrm1 Delay
    u8  HRM1_ACCURATE;       // len:    1 @ 0x0031, Hrm1 Accuracy
    s8  HRM1_VIBRATO;        // len:    1 @ 0x0032, Hrm1 Vibrato
    u8  HRM1_APPROACH;       // len:    1 @ 0x0033, Hrm1 Method
    s8  HRM1_FORMANT;        // len:    1 @ 0x0034, Hrm1 Formant
    s8  HRM1_TONE;           // len:    1 @ 0x0035, Hrm1 Tone
    u8  HRM1_MIDI2VOICE;     // len:    1 @ 0x0036, Hrm1 MIDI
    u8  HRM1_M2V_ZONE_LOWER; // len:    1 @ 0x0037, Hrm1 Zone Lower
    u8  HRM1_M2V_ZONE_UPPER; // len:    1 @ 0x0038, Hrm1 Zone Upper
    u8  HRM2_VOICE_AUTO;     // len:    1 @ 0x0039, Hrm2 Voice Auto
    u8  HRM2_VOICE_MANUAL;   // len:    1 @ 0x003a, Hrm2 Voice Manual
    s8  HRM2_PAN;            // len:    1 @ 0x003b, Hrm2 Pan
    u8  HRM2_LEVEL;          // len:    1 @ 0x003c, Hrm2 Level
    u8  HRM2_DELAY;          // len:    1 @ 0x003d, Hrm2 Delay
    u8  HRM2_ACCURATE;       // len:    1 @ 0x003e, Hrm2 Accuracy
    s8  HRM2_VIBRATO;        // len:    1 @ 0x003f, Hrm2 Vibrato
    u8  HRM2_APPROACH;       // len:    1 @ 0x0040, Hrm2 Method
    s8  HRM2_FORMANT;        // len:    1 @ 0x0041, Hrm2 Formant
    s8  HRM2_TONE;           // len:    1 @ 0x0042, Hrm2 Tone
    u8  HRM2_MIDI2VOICE;     // len:    1 @ 0x0043, Hrm2 MIDI
    u8  HRM2_M2V_ZONE_LOWER; // len:    1 @ 0x0044, Hrm2 Zone Lower
    u8  HRM2_M2V_ZONE_UPPER; // len:    1 @ 0x0045, Hrm2 Zone Upper
    u8  HRM3_VOICE_AUTO;     // len:    1 @ 0x0046, Hrm3 Voice Auto
    u8  HRM3_VOICE_MANUAL;   // len:    1 @ 0x0047, Hrm3 Voice Manual
    s8  HRM3_PAN;            // len:    1 @ 0x0048, Hrm3 Pan
    u8  HRM3_LEVEL;          // len:    1 @ 0x0049, Hrm3 Level
    u8  HRM3_DELAY;          // len:    1 @ 0x004a, Hrm3 Delay
    u8  HRM3_ACCURATE;       // len:    1 @ 0x004b, Hrm3 Accuracy
    s8  HRM3_VIBRATO;        // len:    1 @ 0x004c, Hrm3 Vibrato
    u8  HRM3_APPROACH;       // len:    1 @ 0x004d, Hrm3 Method
    s8  HRM3_FORMANT;        // len:    1 @ 0x004e, Hrm3 Formant
    s8  HRM3_TONE;           // len:    1 @ 0x004f, Hrm3 Tone
    u8  HRM3_MIDI2VOICE;     // len:    1 @ 0x0050, Hrm3 MIDI
    u8  HRM3_M2V_ZONE_LOWER; // len:    1 @ 0x0051, Hrm3 Zone Lower
    u8  HRM3_M2V_ZONE_UPPER; // len:    1 @ 0x0052, Hrm3 Zone Upper
    u8  PADDING2;            // len:    1 @ 0x0053, __padding
    s16 KNOB_ASGN;           // len:    2 @ 0x0054, Knob Assign
    u16 PADDING3;            // len:    2 @ 0x0056, __padding
    u8  NAME_1;              // len:    1 @ 0x0058, Patch Name 1
    u8  reserved_1[15];      // len:   15 @ 0x0059, implicit padding
    u8  PADDING4[24];        // len:   24 @ 0x0068, __padding
} VCLP;

/* VCLU: Block */
/* Total length: 16 bytes (0x0010) */
typedef struct VCLU {
    s8  USRINT_C;  // len:    1 @ 0x0000, User Intv:C
    s8  USRINT_CS; // len:    1 @ 0x0001, User Intv:Db
    s8  USRINT_D;  // len:    1 @ 0x0002, User Intv:D
    s8  USRINT_DS; // len:    1 @ 0x0003, User Intv:Eb
    s8  USRINT_E;  // len:    1 @ 0x0004, User Intv:E
    s8  USRINT_F;  // len:    1 @ 0x0005, User Intv:F
    s8  USRINT_FS; // len:    1 @ 0x0006, User Intv:Gb
    s8  USRINT_G;  // len:    1 @ 0x0007, User Intv:G
    s8  USRINT_GS; // len:    1 @ 0x0008, User Intv:Ab
    s8  USRINT_A;  // len:    1 @ 0x0009, User Intv:A
    s8  USRINT_AS; // len:    1 @ 0x000a, User Intv:Bb
    s8  USRINT_B;  // len:    1 @ 0x000b, User Intv:B
    u32 PADDING1;  // len:    4 @ 0x000c, __padding
} VCLU;

/* VOCAL_SEQ_DATA: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct VOCAL_SEQ_DATA {
    u16 START_TICK; // len:    2 @ 0x0000, Start Tick
    u16 LENG_TICK;  // len:    2 @ 0x0002, Length Tick
    s8  TAKE_ID;    // len:    1 @ 0x0004, Take ID
    u8  MUTE_FLG;   // len:    1 @ 0x0005, Mute Flag
    s16 NEXT_SEQ;   // len:    2 @ 0x0006, Next Seq
    s16 PREV_SEQ;   // len:    2 @ 0x0008, Prev Seq
    u16 PADDING1;   // len:    2 @ 0x000a, __padding
} VOCAL_SEQ_DATA;

/* VOCAL_SEQ: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct VOCAL_SEQ {
    s16 BEGIN_SEQ;   // len:    2 @ 0x0000, Begin Seq
    u16 NUM_SEQ;     // len:    2 @ 0x0002, Num of Seq
    u8  PADDING1[8]; // len:    8 @ 0x0004, __padding
} VOCAL_SEQ;

/* ZB_CC: Block */
/* Total length: 93 bytes (0x005d) */
typedef struct ZB_CC {
    u8  SYS_WRITE;     // len:    1 @ 0x0000, System Write
    u8  PRJ_WRITE;     // len:    1 @ 0x0001, Project Write
    u8  SYS_LOCK;      // len:    1 @ 0x0002, System Lock
    u8  ACTIVATE;      // len:    1 @ 0x0003, Activate_not_use
    u8  PADDING1[12];  // len:   12 @ 0x0004, __padding
    u8  IS_PLAY;       // len:    1 @ 0x0010, IsPlaying_not_use
    u8  DISP_MSG;      // len:    1 @ 0x0011, Disp Message_not_use
    u8  GET_VER;       // len:    1 @ 0x0012, Get Version_not_use
    u8  RX_EDIT;       // len:    1 @ 0x0013, RX EDIT_not_use
    u8  PADDING2;      // len:    1 @ 0x0014, __padding
    u8  CHG_PRJ;       // len:    1 @ 0x0015, Changed Project
    u8  PADDING3[10];  // len:   10 @ 0x0016, __padding
    u8  SEL_CLIP;      // len:    1 @ 0x0020, Select Clip
    u8  SEL_TRACK;     // len:    1 @ 0x0021, Select Track
    u8  PRV_CLIP_SW;   // len:    1 @ 0x0022, Preview Clip Sw
    u8  PRV_CLIP;      // len:    1 @ 0x0023, Preview Clip
    u8  PRV_SCT_SW;    // len:    1 @ 0x0024, Preview Section Sw
    u8  PRV_SCT;       // len:    1 @ 0x0025, Preview Section
    u8  CHG_MODE;      // len:    1 @ 0x0026, Change Mode
    u8  PADDING4;      // len:    1 @ 0x0027, __padding
    u8  MUTE_BD;       // len:    1 @ 0x0028, Mute BD
    u8  MUTE_SD;       // len:    1 @ 0x0029, Mute SD
    u8  MUTE_HH;       // len:    1 @ 0x002a, Mute HH
    u8  MUTE_KT;       // len:    1 @ 0x002b, Mute KT
    u8  MUTE_BS;       // len:    1 @ 0x002c, Mute BS
    u8  MUTE_I1;       // len:    1 @ 0x002d, Mute I1
    u8  MUTE_I2;       // len:    1 @ 0x002e, Mute I2
    u8  MUTE_VO;       // len:    1 @ 0x002f, Mute VO
    u8  COPY_CLIP_SRC; // len:    1 @ 0x0030, Copy Clip Src
    u8  COPY_CLIP_DST; // len:    1 @ 0x0031, Copy Clip Dst
    u8  COPY_SCT_SRC;  // len:    1 @ 0x0032, Copy Section Src
    u8  COPY_SCT_DST;  // len:    1 @ 0x0033, Copy Section Dst
    u8  SWAP_CLIP_SRC; // len:    1 @ 0x0034, Swap Clip Src
    u8  SWAP_CLIP_DST; // len:    1 @ 0x0035, Swap Clip Dst
    u8  SWAP_SCT_SRC;  // len:    1 @ 0x0036, Swap Section Src
    u8  SWAP_SCT_DST;  // len:    1 @ 0x0037, Swap Section Dst
    u8  DEL_CLIP;      // len:    1 @ 0x0038, Delete Clip
    u8  DEL_SCT;       // len:    1 @ 0x0039, Delete Section
    u8  PADDING5[6];   // len:    6 @ 0x003a, __padding
    u8  OPTIMIZE;      // len:    1 @ 0x0040, Optimize_not_use
    u8  SMP_FREE;      // len:    1 @ 0x0041, Sample Free_not_use
    u8  NUMOF_FREE;    // len:    1 @ 0x0042, Num Of Free_not_use
    u8  TONE_FREE;     // len:    1 @ 0x0043, Tone Free_not_use
    u8  TONE_DEL;      // len:    1 @ 0x0044, Tone Delete_not_use
    u8  PADDING6[11];  // len:   11 @ 0x0045, __padding
    u8  SET_TONE_CLIP; // len:    1 @ 0x0050, Set Tone Clip
    u8  SET_TONE_BANK; // len:    1 @ 0x0051, Set Tone Bank
    u16 SET_TONE_NUM;  // len:    2 @ 0x0052, Set Tone Number
    u8  SET_KIT_CLIP;  // len:    1 @ 0x0054, Set Kit Clip
    u8  SET_KIT_BANK;  // len:    1 @ 0x0055, Set Kit Bank
    u16 SET_KIT_NUM;   // len:    2 @ 0x0056, Set Kit Number
    u8  SET_INST_CLIP; // len:    1 @ 0x0058, Set Inst Clip
    u8  SET_INST_PAD;  // len:    1 @ 0x0059, Set Inst Pad
    u8  SET_INST_BANK; // len:    1 @ 0x005a, Set Inst Bank
    u16 SET_INST_NUM;  // len:    2 @ 0x005b, Set Inst Number
} ZB_CC;

/* ZB_IN: Block */
/* Total length: 2 bytes (0x0002) */
typedef struct ZB_IN {
    u16 GET_INDEX_NOTE; // len:    2 @ 0x0000, Get Index Note
} ZB_IN;

/* ZB_TN: Block */
/* Total length: 2 bytes (0x0002) */
typedef struct ZB_TN {
    u16 GET_TOTAL_NOTE; // len:    2 @ 0x0000, Get Total Note
} ZB_TN;

/* Clip: Group */
/* Total length: 23616 bytes (0x5c40) */
typedef struct Clip {
    CLC     CLC;          // len:  128 @ 0x0000, CLC
    CLP     CLP;          // len:  640 @ 0x0080, CLP
    PHR     PHR;          // len:  192 @ 0x0300, PHR
    PHR_NT  PHR_NT[128];  // len:12288 @ 0x03c0, PHR_NT
    PHR_CC  PHR_CC[128];  // len: 8192 @ 0x33c0, PHR_CC
    PHR_BND PHR_BND[128]; // len: 2048 @ 0x53c0, PHR_BND
    ARP     ARP;          // len:  128 @ 0x5bc0, ARP
} Clip;

/* Ctrl: Group */
/* Total length: 97 bytes (0x0061) */
typedef struct Ctrl {
    ZB_CC ZB_CC; // len:   93 @ 0x0000, ZB_CC
    ZB_TN ZB_TN; // len:    2 @ 0x005d, ZB_TN
    ZB_IN ZB_IN; // len:    2 @ 0x005f, ZB_IN
} Ctrl;

/* LOOP: Group */
/* Total length: 208 bytes (0x00d0) */
typedef struct LOOP {
    LOOP_CMN LOOP_CMN; // len:  124 @ 0x0000, LOOP_CMN
    MFX      MFX;      // len:   84 @ 0x007c, MFX
} LOOP;

/* MultiSample: Group */
/* Total length: 528 bytes (0x0210) */
typedef struct MultiSample {
    MSMP_CMN  MSMP_CMN;       // len:   16 @ 0x0000, MSMP_CMN
    MSMP_SPLT MSMP_SPLT[128]; // len:  512 @ 0x0010, MSMP_SPLT
} MultiSample;

/* MVProj: Group */
/* Total length: 4968 bytes (0x1368) */
typedef struct MVProj {
    SCT            SCT[16];             // len: 1024 @ 0x0000, SCT
    SNG_CMN        SNG_CMN;             // len:   64 @ 0x0400, SNG_CMN
    SNG            SNG[99];             // len: 1584 @ 0x0440, SNG
    VCLP           VCLP;                // len:  128 @ 0x0a70, VCLP
    VCLU           VCLU[4];             // len:   64 @ 0x0af0, VCLU
    KBDARP         KBDARP;              // len:   12 @ 0x0b30, KBDARP
    TAKE           TAKE[16];            // len:  448 @ 0x0b3c, TAKE
    VOCAL_SEQ      VOCAL_SEQ;           // len:   12 @ 0x0cfc, VOCAL_SEQ
    VOCAL_SEQ_DATA VOCAL_SEQ_DATA[128]; // len: 1536 @ 0x0d08, VOCAL_SEQ_DATA
    SLIM           SLIM;                // len:   12 @ 0x1308, SLIM
    TCMP           TCMP[7];             // len:   84 @ 0x1314, TCMP
} MVProj;

/* PCMEX: Group */
/* Total length: 1632 bytes (0x0660) */
typedef struct PCMEX {
    PCMT_CMN PCMT_CMN;    // len:   64 @ 0x0000, PCMT_CMN
    MFX      MFX;         // len:   84 @ 0x0040, MFX
    PCMT_PMT PCMT_PMT;    // len:   52 @ 0x0094, PCMT_PMT
    PCMT_PTL PCMT_PTL[4]; // len:  496 @ 0x00c8, PCMT_PTL
    PTL_PENV PTL_PENV[4]; // len:   96 @ 0x02b8, PTL_PENV
    PTL_FENV PTL_FENV[4]; // len:   96 @ 0x0318, PTL_FENV
    PTL_AENV PTL_AENV[4]; // len:   64 @ 0x0378, PTL_AENV
    PTL_LFO  PTL_LFO[4];  // len:  416 @ 0x03b8, PTL_LFO
    PTL_EQ   PTL_EQ[4];   // len:   64 @ 0x0558, PTL_EQ
    PCMS_CMN PCMS_CMN;    // len:   20 @ 0x0598, PCMS_CMN
    PCMS_PMT PCMS_PMT;    // len:   36 @ 0x05ac, PCMS_PMT
    PCMS_PTL PCMS_PTL[4]; // len:  144 @ 0x05d0, PCMS_PTL
} PCMEX;

/* PCMR: Group */
/* Total length: 3328 bytes (0x0d00) */
typedef struct PCMR {
    PCMR_CMN PCMR_CMN;     // len:   28 @ 0x0000, PCMR_CMN
    MFX      MFX;          // len:   84 @ 0x001c, MFX
    RCMP     RCMP[6];      // len:   48 @ 0x0070, RCMP
    PCMR_PTL PCMR_PTL[88]; // len: 1760 @ 0x00a0, PCMR_PTL
    PTL_EQ   PTL_EQ[88];   // len: 1408 @ 0x0780, PTL_EQ
} PCMR;

/* PCMRInst: Group */
/* Total length: 216 bytes (0x00d8) */
typedef struct PCMRInst {
    INST_CMN INST_CMN; // len:  152 @ 0x0000, INST_CMN
    PTL_PENV PTL_PENV; // len:   24 @ 0x0098, PTL_PENV
    PTL_FENV PTL_FENV; // len:   24 @ 0x00b0, PTL_FENV
    PTL_AENV PTL_AENV; // len:   16 @ 0x00c8, PTL_AENV
} PCMRInst;

/* Proj: Group */
/* Total length: 4311 bytes (0x10d7) */
typedef struct Proj {
    PJC  PJC;      // len:  369 @ 0x0000, PJC
    PJC2 PJC2;     // len:  134 @ 0x0171, PJC2
    PJT  PJT[8];   // len: 2048 @ 0x01f7, PJT
    PEQ  PEQ[8];   // len:   96 @ 0x09f7, PEQ
    MFX  MFX[3];   // len:  252 @ 0x0a57, MFX
    SH   SH;       // len:   48 @ 0x0b53, SH
    SV   SV;       // len:   44 @ 0x0b83, SV
    GLT  GLT;      // len:   64 @ 0x0baf, GLT
    GLT2 GLT2[16]; // len: 1216 @ 0x0bef, GLT2
    SEQ  SEQ;      // len:   16 @ 0x10af, SEQ
    SCMP SCMP;     // len:   24 @ 0x10bf, SCMP
} Proj;

/* Sys: Group */
/* Total length: 512 bytes (0x0200) */
typedef struct Sys {
    SC    SC;    // len:  256 @ 0x0000, SC
    SPATH SPATH; // len:  256 @ 0x0100, SPATH
} Sys;

/* UserSample: Group */
/* Total length: 78 bytes (0x004e) */
typedef struct UserSample {
    UserSampleCmn    UserSampleCmn;    // len:   64 @ 0x0000, UserSampleCmn
    UserSampleModify UserSampleModify; // len:   14 @ 0x0040, UserSampleModify
} UserSample;

#pragma pack(pop)

#endif /* MV_1_180_A_GENERATED_H */
