import { writeFileSync } from "fs";

function toPythonLiteral(value, indent = 0) {
    const pad = "    ".repeat(indent);
    const inner = "    ".repeat(indent + 1);

    if (value === null || value === undefined) return "None";
    if (value === true) return "True";
    if (value === false) return "False";
    if (typeof value === "number") return String(value);
    if (typeof value === "string") return JSON.stringify(value);

    if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value.map(v => `${inner}${toPythonLiteral(v, indent + 1)}`);
        return `[\n${items.join(",\n")},\n${pad}]`;
    }

    if (typeof value === "object") {
        const keys = Object.keys(value);
        if (keys.length === 0) return "{}";
        const items = keys.map(k => `${inner}${JSON.stringify(k)}: ${toPythonLiteral(value[k], indent + 1)}`);
        return `{\n${items.join(",\n")},\n${pad}}`;
    }

    return String(value);
}

export function generatePython(configName, blocks, groups, outputPath) {
    const merged = { ...blocks, ...groups };
    const content = `# Autogenerated from config: ${configName}\n# Do not edit manually\n\nZenProperties = ${toPythonLiteral(merged)}\n`;
    writeFileSync(outputPath, content);
    console.log(`Python generated: ${outputPath}`);
}
