/* Autogenerated from config: juno */
#ifndef JUNO_GENERATED_H
#define JUNO_GENERATED_H

#include <stdint.h>

typedef int8_t s8;
typedef uint8_t u8;
typedef int16_t s16;
typedef uint16_t u16;
typedef int32_t s32;
typedef uint32_t u32;

#pragma pack(push, 1)

/* ARPC: Arpeggio Common */
/* Total length: 28 bytes (0x001c) */
typedef struct ARPC {
    u8  ARP_SW;       // len:    1 @ 0x0000, Master Switch
    u8  ARP_HOLD;     // len:    1 @ 0x0001, Master Hold Switch
    u8  KEYS_SW;      // len:    1 @ 0x0002, Keys Detect
    u8  BEAT_SW;      // len:    1 @ 0x0003, Beat Detect
    u8  BEAT_SENS;    // len:    1 @ 0x0004, Beat Detect Sens
    u8  SHFL_RATE;    // len:    1 @ 0x0005, G-Shuffle Rate
    s8  DURATION;     // len:    1 @ 0x0006, G-Duration
    u8  RESERVE;      // len:    1 @ 0x0007, Reserved
    u16 TYPE;         // len:    2 @ 0x0008, Original Type No.
    u16 RHYTHM;       // len:    2 @ 0x000a, Original Rhythm No.
    u8  IN_RANGE_LOW; // len:    1 @ 0x000c, Keyboard Input Range Lower
    u8  IN_RANGE_UP;  // len:    1 @ 0x000d, Keyboard Input Range Upper
    u8  PADDING1[14]; // len:   14 @ 0x000e, __padding
} ARPC;

/* ARPP: Arpeggio Part */
/* Total length: 68 bytes (0x0044) */
typedef struct ARPP {
    u8  SW;                  // len:    1 @ 0x0000, Part Switch
    u8  PADDING1;            // len:    1 @ 0x0001, __padding
    u16 RSVD_ARP_PATSET;     // len:    2 @ 0x0002, Reserved
    u8  DURATION;            // len:    1 @ 0x0004, Duration
    u8  SHFL_RATE;           // len:    1 @ 0x0005, Shuffle Rate
    s8  OCTAVE;              // len:    1 @ 0x0006, Octave Range
    s8  TRANS;               // len:    1 @ 0x0007, Transpose
    u8  HOLD;                // len:    1 @ 0x0008, Part Hold Switch
    u8  MOTIF;               // len:    1 @ 0x0009, Motif
    u8  SHFL_RESO;           // len:    1 @ 0x000a, Shuffle Resolution
    u8  GRID_NOTE;           // len:    1 @ 0x000b, Grid Note
    u8  END;                 // len:    1 @ 0x000c, End of Grid
    u8  VELO;                // len:    1 @ 0x000d, Velocity
    s8  GRID_OFFSET;         // len:    1 @ 0x000e, Grid Offset
    u8  GRID_SYNC;           // len:    1 @ 0x000f, Grid Sync
    s8  OFS_VELO;            // len:    1 @ 0x0010, Offset Velocity
    u8  DUCKING_RATE;        // len:    1 @ 0x0011, Ducking Rate
    u8  DUCKING_NOTE;        // len:    1 @ 0x0012, Ducking Note
    u8  DUCKING_MASTER_PART; // len:    1 @ 0x0013, Ducking Part
    u8  RANGE_LO;            // len:    1 @ 0x0014, Key Range Low
    u8  RANGE_OCT;           // len:    1 @ 0x0015, Key Range Octave
    u8  RECIEVE_SW;          // len:    1 @ 0x0016, Receive Switch
    u8  NOTEOFFMODE;         // len:    1 @ 0x0017, Note Off Mode
    u8  PTN_CHANGE;          // len:    1 @ 0x0018, Pattern Change Timing
    u8  RSTOCTSHIFT;         // len:    1 @ 0x0019, Reset Octave Shift
    u8  REMAINNOTE;          // len:    1 @ 0x001a, Arp Poly Remain Notes
    u8  RSVD_STEP_SEQ;       // len:    1 @ 0x001b, Reserved
    u16 INIT_PAT;            // len:    2 @ 0x001c, Initial Pattern Number
    u8  ARP_MODE;            // len:    1 @ 0x001e, Arp Mode
    u8  KSW_SYNC;            // len:    1 @ 0x001f, Key Switch Sync
    u8  STEP_KSHFT;          // len:    1 @ 0x0020, Step Key Shift
    u8  IARP_PART;           // len:    1 @ 0x0021, I-Arp Style Part
    u16 IARP_STYLE;          // len:    2 @ 0x0022, I-Arp Style
    u8  ARP_STYLE;           // len:    1 @ 0x0024, Arp Style
    u8  ARP_VARI;            // len:    1 @ 0x0025, Arp Variation
    u8  ARP_STEP;            // len:    1 @ 0x0026, Arp Step Switch
    u8  PROB_STYLE;          // len:    1 @ 0x0027, Probability Style
    u8  PROB_AMNT;           // len:    1 @ 0x0028, Probability Amount
    u8  PROB_AMNT_DIR;       // len:    1 @ 0x0029, Probability Amount Direction
    u8  PROB_AMNT_AUTO;      // len:    1 @ 0x002a, Probability Amount Auto
    u8  PROB_VL_AMNT;        // len:    1 @ 0x002b, Probability Velocity Amount
    u16 PROB_ENA;            // len:    2 @ 0x002c, Probability Enable
    s8  PROB_OFFSET;         // len:    1 @ 0x002e, Probability Grid Offset
    u8  PADDING2[21];        // len:   21 @ 0x002f, __padding
} ARPP;

/* ARPUSER_NOTE: NOTE */
/* Total length: 68 bytes (0x0044) */
typedef struct ARPUSER_NOTE {
    u8 TYPE;           // len:    1 @ 0x0000, [02$] Type
    u8 NUM;            // len:    1 @ 0x0001, [02$] Number
    u8 VAL_1;          // len:    1 @ 0x0002, [021] Value Step.02$
    u8 reserved_1[63]; // len:   63 @ 0x0003, implicit padding
    u8 PAD0;           // len:    1 @ 0x0042, Reserved
    u8 PAD1;           // len:    1 @ 0x0043, Reserved
} ARPUSER_NOTE;

/* ARPUSER: Arpeggio User Pattern Data */
/* Total length: 68 bytes (0x0044) */
typedef struct ARPUSER {
    ARPUSER_NOTE NOTE; // len:   68 @ 0x0000, NOTE
} ARPUSER;

/* BCS: Button Color Setup */
/* Total length: 4 bytes (0x0004) */
typedef struct BCS {
    u8 BUTTON_COLOR; // len:    1 @ 0x0000, Button Color(01$)
    u8 PADDING1[3];  // len:    3 @ 0x0001, __padding
} BCS;

/* EDLEXZ: EXZ List */
/* Total length: 4 bytes (0x0004) */
typedef struct EDLEXZ {
    u8 LIST;        // len:    1 @ 0x0000, EXZ List
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDLEXZ;

/* EDLEXZR: EXZ List Request Command */
/* Total length: 4 bytes (0x0004) */
typedef struct EDLEXZR {
    u8  FROM;     // len:    1 @ 0x0000, EXZ List Request From
    u8  SIZE;     // len:    1 @ 0x0001, EXZ List Request Size
    u16 PADDING1; // len:    2 @ 0x0002, __padding
} EDLEXZR;

/* EDLF: Scene List */
/* Total length: 4 bytes (0x0004) */
typedef struct EDLF {
    u8 LIST;        // len:    1 @ 0x0000, Scene List
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDLF;

/* EDLFR: Scene List Request Command */
/* Total length: 8 bytes (0x0008) */
typedef struct EDLFR {
    u8  GROUP;    // len:    1 @ 0x0000, Reserved
    u8  SLOT;     // len:    1 @ 0x0001, Reserved
    u16 FROM;     // len:    2 @ 0x0002, Scene Request From
    u16 SIZE;     // len:    2 @ 0x0004, Scene Request Size
    u16 PADDING1; // len:    2 @ 0x0006, __padding
} EDLFR;

/* EDLT: Tone List */
/* Total length: 4 bytes (0x0004) */
typedef struct EDLT {
    u8 LIST;        // len:    1 @ 0x0000, Tone List
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDLT;

/* EDLTR: Tone List Request Command */
/* Total length: 8 bytes (0x0008) */
typedef struct EDLTR {
    u8  GROUP;    // len:    1 @ 0x0000, Tone Request Group
    u8  SLOT;     // len:    1 @ 0x0001, Tone Request Slot
    u16 FROM;     // len:    2 @ 0x0002, Tone Request From
    u16 SIZE;     // len:    2 @ 0x0004, Tone Request Size
    u16 PADDING1; // len:    2 @ 0x0006, __padding
} EDLTR;

/* EDLW: Wave List */
/* Total length: 4 bytes (0x0004) */
typedef struct EDLW {
    u8 LIST;        // len:    1 @ 0x0000, Wave List
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDLW;

/* EDLWR: Wave List Request Command */
/* Total length: 8 bytes (0x0008) */
typedef struct EDLWR {
    u8  GROUP;    // len:    1 @ 0x0000, Wave Request Group
    u8  SLOT;     // len:    1 @ 0x0001, Wave Request Slot
    u16 FROM;     // len:    2 @ 0x0002, Wave Request From
    u16 SIZE;     // len:    2 @ 0x0004, Wave Request Size
    u16 PADDING1; // len:    2 @ 0x0006, __padding
} EDLWR;

/* EDPC: Mode */
/* Total length: 4 bytes (0x0004) */
typedef struct EDPC {
    u8 EDTRMODE; // len:    1 @ 0x0000, Editor Mode
    u8 EDITTX;   // len:    1 @ 0x0001, Edit Tx
    u8 PAWS;     // len:    1 @ 0x0002, Pending Auto Write Switch
    u8 PADDING1; // len:    1 @ 0x0003, __padding
} EDPC;

/* EDPTI: Part Info Reply */
/* Total length: 4 bytes (0x0004) */
typedef struct EDPTI {
    u8 INFO;        // len:    1 @ 0x0000, Part Info Reply
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDPTI;

/* EDPTIR: Part Info Request Command */
/* Total length: 4 bytes (0x0004) */
typedef struct EDPTIR {
    u8 PART;        // len:    1 @ 0x0000, Part Info Request
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDPTIR;

/* EDS: System Information */
/* Total length: 4 bytes (0x0004) */
typedef struct EDS {
    u8  SYS_REQ;  // len:    1 @ 0x0000, System Request
    u8  VER_INFO; // len:    1 @ 0x0001, Version Information
    u16 PADDING1; // len:    2 @ 0x0002, __padding
} EDS;

/* EDSEXZ: EXZ Slot */
/* Total length: 4 bytes (0x0004) */
typedef struct EDSEXZ {
    u8 LIST;        // len:    1 @ 0x0000, EXZ Slot
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDSEXZ;

/* EDSEXZR: EXZ Slot Request Command */
/* Total length: 4 bytes (0x0004) */
typedef struct EDSEXZR {
    u8  FROM;     // len:    1 @ 0x0000, EXZ Slot Request From
    u8  SIZE;     // len:    1 @ 0x0001, EXZ Slot Request Size
    u16 PADDING1; // len:    2 @ 0x0002, __padding
} EDSEXZR;

/* EDVD: VoDsgn Command */
/* Total length: 4 bytes (0x0004) */
typedef struct EDVD {
    u8 CTMODE;      // len:    1 @ 0x0000, Carrier Thru Mode
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
} EDVD;

/* EDWM: Write Message */
/* Total length: 8 bytes (0x0008) */
typedef struct EDWM {
    u8 WRI_SYS;  // len:    1 @ 0x0000, System Write
    u8 WRI_PRF;  // len:    1 @ 0x0001, Scene Write
    u8 WRI_PAT1; // len:    1 @ 0x0002, Tone Write (Part 1)
    u8 WRI_PAT2; // len:    1 @ 0x0003, Tone Write (Part 2)
    u8 WRI_PAT3; // len:    1 @ 0x0004, Tone Write (Part 3)
    u8 WRI_PAT4; // len:    1 @ 0x0005, Tone Write (Part 4)
    u8 PAWWC;    // len:    1 @ 0x0006, Writes pending items
    u8 PADDING1; // len:    1 @ 0x0007, __padding
} EDWM;

/* FC: Scene Common */
/* Total length: 39 bytes (0x0027) */
typedef struct FC {
    u8  NAME_1;         // len:    1 @ 0x0000,  1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  LEVEL;          // len:    1 @ 0x0010, Scene Level
    u8  RESERVE;        // len:    1 @ 0x0011, Reserved
    u16 TEMPO;          // len:    2 @ 0x0012, Scene Tempo
    u8  KEY_FUNC;       // len:    1 @ 0x0014, Assignable Button(01$) Function
    u8  KEY_MODE;       // len:    1 @ 0x0015, Assignable Button(01$) Mode
    u8  HOLD_PDL_FUNC;  // len:    1 @ 0x0016, Hold Pedal Function
    u8  HOLD_PDL_POLE;  // len:    1 @ 0x0017, Hold Pedal Polarity
    u8  CTRL_PDL_FUNC;  // len:    1 @ 0x0018, Ctrl Pedal Function
    u8  SLIDER_FUNC;    // len:    1 @ 0x0019, Assignable Slider(01$) Function
    u8  WHLBND_FUNC;    // len:    1 @ 0x001a, Control Wheel1 Function
    u8  WHLMOD_FUNC;    // len:    1 @ 0x001b, Control Wheel2 Function
    u8  CTRL_SRC_1;     // len:    1 @ 0x001c, Control Source(011)
    u8  reserved_2[3];  // len:    3 @ 0x001d, implicit padding
    u8  V_RSRV;         // len:    1 @ 0x0020, Voice Reserve Layer(01$)
    u8  CUR_PART;       // len:    1 @ 0x0021, Current Part
    u8  XFADEPOS;       // len:    1 @ 0x0022, Part Crossfade Position
    u32 PADDING1;       // len:    4 @ 0x0023, __padding
} FC;

/* FP: Scene Part */
/* Total length: 84 bytes (0x0054) */
typedef struct FP {
    u8 SW;                 // len:    1 @ 0x0000, Part Switch
    u8 MUTE_SW;            // len:    1 @ 0x0001, Mute Switch
    u8 BANK_MSB;           // len:    1 @ 0x0002, Tone Bank Select MSB (CC#0)
    u8 BANK_LSB;           // len:    1 @ 0x0003, Tone Bank Select LSB (CC#32)
    u8 PC;                 // len:    1 @ 0x0004, Tone Program Change (PC)
    u8 LEVEL;              // len:    1 @ 0x0005, Part Level (CC#7)
    s8 PAN;                // len:    1 @ 0x0006, Part Pan (CC#10)
    s8 PIT_CRS;            // len:    1 @ 0x0007, Part Coarse Tune (RPN#2)
    s8 PIT_FINE;           // len:    1 @ 0x0008, Part Fine Tune (RPN#1)
    u8 MONO_POLY;          // len:    1 @ 0x0009, Part Mono/Poly
    u8 LEGATO;             // len:    1 @ 0x000a, Part Legato Switch
    u8 BEND_RANGE;         // len:    1 @ 0x000b, Part Bend Range
    u8 PORT_SW;            // len:    1 @ 0x000c, Part Portamento Switch (CC#65)
    u8 PORT_TIME;          // len:    1 @ 0x000d, Part Portamento Time (CC#5)
    s8 CUTOFF_OFST;        // len:    1 @ 0x000e, Part Cutoff Offset (CC#74)
    s8 RESO_OFST;          // len:    1 @ 0x000f, Part Resonance Offset (CC#71)
    s8 ATK_OFST;           // len:    1 @ 0x0010, Part Attack Time Offset (CC#73)
    s8 DCY_OFST;           // len:    1 @ 0x0011, Part Decay Time Offset (CC#75)
    s8 REL_OFST;           // len:    1 @ 0x0012, Part Release Time Offset (CC#72)
    s8 VIB_RATE;           // len:    1 @ 0x0013, Part Vibrato Rate (CC#76)
    s8 VIB_DEPTH;          // len:    1 @ 0x0014, Part Vibrato Depth (CC#77)
    s8 VIB_DELAY;          // len:    1 @ 0x0015, Part Vibrato Delay (CC#78)
    u8 UNISON_SW;          // len:    1 @ 0x0016, Unison Switch
    u8 BEND_MODE;          // len:    1 @ 0x0017, Bend Mode
    u8 TONE_MFX;           // len:    1 @ 0x0018, Follow Tone MFX
    u8 OUTPUT;             // len:    1 @ 0x0019, Output Assign
    u8 CHO_SEND;           // len:    1 @ 0x001a, Part Chorus Send Level (CC#93)
    u8 REV_SEND;           // len:    1 @ 0x001b, Part Reverb Send Level (CC#91)
    u8 DLY_SEND;           // len:    1 @ 0x001c, Part Delay Send Level
    s8 OCT_SHIFT;          // len:    1 @ 0x001d, Part Octave Shift
    s8 VEL_SENS_OFST;      // len:    1 @ 0x001e, Part Velocity Sens Offset
    u8 ASGN_MODE;          // len:    1 @ 0x001f, Voice Assign Mode
    u8 TUNE_TYPE;          // len:    1 @ 0x0020, Part Scale Tune Type
    u8 TUNE_KEY;           // len:    1 @ 0x0021, Part Scale Tune Key
    s8 TUNE_C;             // len:    1 @ 0x0022, Part Scale Tune for C
    s8 TUNE_CS;            // len:    1 @ 0x0023, Part Scale Tune for C#
    s8 TUNE_D;             // len:    1 @ 0x0024, Part Scale Tune for D
    s8 TUNE_DS;            // len:    1 @ 0x0025, Part Scale Tune for D#
    s8 TUNE_E;             // len:    1 @ 0x0026, Part Scale Tune for E
    s8 TUNE_F;             // len:    1 @ 0x0027, Part Scale Tune for F
    s8 TUNE_FS;            // len:    1 @ 0x0028, Part Scale Tune for F#
    s8 TUNE_G;             // len:    1 @ 0x0029, Part Scale Tune for G
    s8 TUNE_GS;            // len:    1 @ 0x002a, Part Scale Tune for G#
    s8 TUNE_A;             // len:    1 @ 0x002b, Part Scale Tune for A
    s8 TUNE_AS;            // len:    1 @ 0x002c, Part Scale Tune for A#
    s8 TUNE_B;             // len:    1 @ 0x002d, Part Scale Tune for B
    u8 RX_PC_SW;           // len:    1 @ 0x002e, Receive Program Change
    u8 RX_BS_SW;           // len:    1 @ 0x002f, Receive Bank Select
    u8 RX_PB_SW;           // len:    1 @ 0x0030, Receive Pitch Bend
    u8 RX_PAF_SW;          // len:    1 @ 0x0031, Receive Poly Key Pressure
    u8 RX_CAF_SW;          // len:    1 @ 0x0032, Receive Channel Pressure
    u8 RX_MOD_SW;          // len:    1 @ 0x0033, Receive Modulation
    u8 RX_CC07_SW;         // len:    1 @ 0x0034, Receive Volume
    u8 RX_CC10_SW;         // len:    1 @ 0x0035, Receive Pan
    u8 RX_CC11_SW;         // len:    1 @ 0x0036, Receive Expression
    u8 RX_CC64_SW;         // len:    1 @ 0x0037, Receive Hold-1
    u8 KBD_VELO_MODE;      // len:    1 @ 0x0038, Keyboard Velocity Mode
    u8 KBD_FIXED_VELO;     // len:    1 @ 0x0039, Keyboard Fixed Velocity
    u8 VCRV_TYPE;          // len:    1 @ 0x003a, Velocity Curve Type
    s8 AMP_ATK_OFST;       // len:    1 @ 0x003b, Part Amp Attack Time Offset
    s8 AMP_DCY_OFST;       // len:    1 @ 0x003c, Part Amp Decay Time Offset
    s8 AMP_SUS_OFST;       // len:    1 @ 0x003d, Part Amp Sustain Level Offset
    s8 AMP_REL_OFST;       // len:    1 @ 0x003e, Part Amp Release Time Offset
    s8 FLT_KF_OFST;        // len:    1 @ 0x003f, Part Filter Keyfollow Offset
    s8 FLT_ENV_DEPTH_OFST; // len:    1 @ 0x0040, Part Filter Envelope Depth Offset
    s8 FLT_ATK_OFST;       // len:    1 @ 0x0041, Part Filter Attack Time Offset
    s8 FLT_DCY_OFST;       // len:    1 @ 0x0042, Part Filter Decay Time Offset
    s8 FLT_SUS_OFST;       // len:    1 @ 0x0043, Part Filter Sustain Level Offset
    s8 FLT_REL_OFST;       // len:    1 @ 0x0044, Part Filter Release Time Offset
    s8 PIT_ENV_DEPTH_OFST; // len:    1 @ 0x0045, Part Pitch Envelope Depth Offset
    s8 PIT_ATK_OFST;       // len:    1 @ 0x0046, Part Pitch Attack Time Offset
    s8 PIT_DCY_OFST;       // len:    1 @ 0x0047, Part Pitch Decay Time Offset
    s8 PIT_SUS_OFST;       // len:    1 @ 0x0048, Part Pitch Sustain Level Offset
    s8 PIT_REL_OFST;       // len:    1 @ 0x0049, Part Pitch Release Time Offset
    s8 LFO_FLT_DEPTH;      // len:    1 @ 0x004a, Part Filter LFO Depth
    s8 LFO_AMP_DEPTH;      // len:    1 @ 0x004b, Part Amp LFO Depth
    s8 LFO_PIT_DEPTH;      // len:    1 @ 0x004c, Part Pitch LFO Depth
    u8 RX_CH;              // len:    1 @ 0x004d, Receive Channel
    u8 PNL_SW;             // len:    1 @ 0x004e, Panel Edit Switch
    u8 PADDING1[5];        // len:    5 @ 0x004f, __padding
} FP;

/* FZ: Scene Zone */
/* Total length: 25 bytes (0x0019) */
typedef struct FZ {
    u8  KBD_SW;      // len:    1 @ 0x0000, Keyboard Switch
    u8  KRANGE_LO;   // len:    1 @ 0x0001, Keyboard Range Lower
    u8  KRANGE_UP;   // len:    1 @ 0x0002, Keyboard Range Upper
    u8  KFADE_LO;    // len:    1 @ 0x0003, Keyboard Fade Width Lower
    u8  KFADE_UP;    // len:    1 @ 0x0004, Keyboard Fade Width Upper
    u8  VRANGE_LO;   // len:    1 @ 0x0005, Velocity Range Lower
    u8  VRANGE_UP;   // len:    1 @ 0x0006, Velocity Range Upper
    u8  VFADE_LO;    // len:    1 @ 0x0007, Velocity Fade Width Lower
    u8  VFADE_UP;    // len:    1 @ 0x0008, Velocity Fade Width Upper
    u8  RX_ASGN_KEY; // len:    1 @ 0x0009, Rx Assignable Button(01$)
    u8  RX_PDL_HOLD; // len:    1 @ 0x000a, RX Hold Pedal
    u8  RX_PDL_CTRL; // len:    1 @ 0x000b, Rx Control Pedal
    u8  RX_SLIDER;   // len:    1 @ 0x000c, Rx Assignable Slider(01$)
    u8  RX_WHLBND;   // len:    1 @ 0x000d, Rx Control Wheel1
    u8  RX_WHLMOD;   // len:    1 @ 0x000e, Rx Control Wheel2
    u8  PTX;         // len:    1 @ 0x000f, Tx Mode
    u8  MKB_CH;      // len:    1 @ 0x0010, Master Keyboard Tx CH
    u8  MKB_MSB;     // len:    1 @ 0x0011, Master Keyboard Bank MSB
    u8  MKB_LSB;     // len:    1 @ 0x0012, Master Keyboard Bank LSB
    u8  MKB_PC;      // len:    1 @ 0x0013, Master Keyboard Program Change
    u8  MKB_VOL;     // len:    1 @ 0x0014, Master Keyboard Volume
    u32 PADDING1;    // len:    4 @ 0x0015, __padding
} FZ;

/* IFX: Block */
/* Total length: 84 bytes (0x0054) */
typedef struct IFX {
    u8  ifxType;        // len:    1 @ 0x0000, IFX Type
    u8  ifxSwitch;      // len:    1 @ 0x0001, IFX Switch
    u8  choSend;        // len:    1 @ 0x0002, IFX Chorus Send Level
    u8  revSend;        // len:    1 @ 0x0003, IFX Reverb Send Level
    u8  ctrlSrc1;       // len:    1 @ 0x0004, IFX CtrlSrc 1
    s8  ctrlSens1;      // len:    1 @ 0x0005, IFX CtrlSens 1
    u8  ctrlSrc2;       // len:    1 @ 0x0006, IFX CtrlSrc 2
    s8  ctrlSens2;      // len:    1 @ 0x0007, IFX CtrlSens 2
    u8  ctrlSrc3;       // len:    1 @ 0x0008, IFX CtrlSrc 3
    s8  ctrlSens3;      // len:    1 @ 0x0009, IFX CtrlSens 3
    u8  ctrlSrc4;       // len:    1 @ 0x000a, IFX CtrlSrc 4
    s8  ctrlSens4;      // len:    1 @ 0x000b, IFX CtrlSens 4
    u8  ctrlAsgn_1;     // len:    1 @ 0x000c, IFX CtrlAsgn 1
    u8  reserved_1[3];  // len:    3 @ 0x000d, implicit padding
    s16 param_1;        // len:    2 @ 0x0010, IFX Parameter 1
    u8  reserved_2[62]; // len:   62 @ 0x0012, implicit padding
    u32 PADDING1;       // len:    4 @ 0x0050, __padding
} IFX;

/* MBAS: System Model Bank Assign */
/* Total length: 8 bytes (0x0008) */
typedef struct MBAS {
    u8  ATTR;        // len:    1 @ 0x0000, Attribute
    u8  PADDING1[3]; // len:    3 @ 0x0001, __padding
    u8  MODEL;       // len:    1 @ 0x0004, Model
    u8  CATEGORY;    // len:    1 @ 0x0005, Category
    u16 EXZ;         // len:    2 @ 0x0006, EXZ
} MBAS;

/* MDLCORE: Model Core Parameter */
/* Total length: 112 bytes (0x0070) */
typedef struct MDLCORE {
    u8  MODEL;       // len:    1 @ 0x0000, Model
    u8  LFOWAVE;     // len:    1 @ 0x0001, LFO WAVE FORM
    u16 LFORATE;     // len:    2 @ 0x0002, LFO RATE
    u16 LFODLY;      // len:    2 @ 0x0004, LFO DELAY TIME
    s8  OSC1MOD;     // len:    1 @ 0x0006, OSC1 MOD
    s8  OSC1PENV;    // len:    1 @ 0x0007, OSC1 PITCH ENV DEPTH
    u8  OSC1DEST;    // len:    1 @ 0x0008, OSC1 DEST SELECT
    u8  OSC1ENVS;    // len:    1 @ 0x0009, OSC1 ENVT SELECT
    u16 OSC1WAVE;    // len:    2 @ 0x000a, OSC1 WAVE FORM
    u8  OSC1FEET;    // len:    1 @ 0x000c, OSC1 FEET
    s8  OSC1COARSE;  // len:    1 @ 0x000d, OSC1 COARSE TUNE
    s8  OSC1FINE;    // len:    1 @ 0x000e, OSC1 FINE TUNE
    u8  OSC1LOWFREQ; // len:    1 @ 0x000f, OSC1 LOW FREQ PITCH
    u8  OSC1MODE;    // len:    1 @ 0x0010, OSC1 MODE
    s8  OSC1PWM;     // len:    1 @ 0x0011, OSC1 PWM DEPTH
    u8  OSC1PLSW;    // len:    1 @ 0x0012, OSC1 PULSE WIDTH
    u8  OSC1PLSM;    // len:    1 @ 0x0013, OSC1 PULSE WIDTH MODE
    s8  OSC2MOD;     // len:    1 @ 0x0014, OSC2 MOD
    s8  OSC2PENV;    // len:    1 @ 0x0015, OSC2 PITCH ENV DEPTH
    u16 OSC2WAVE;    // len:    2 @ 0x0016, OSC2 WAVE FORM
    u8  OSC2FEET;    // len:    1 @ 0x0018, OSC2 FEET
    s8  OSC2COARSE;  // len:    1 @ 0x0019, OSC2 COARSE TUNE
    s8  OSC2FINE;    // len:    1 @ 0x001a, OSC2 FINE TUNE
    u8  OSC2LOWFREQ; // len:    1 @ 0x001b, OSC2 LOW FREQ PITCH
    u8  OSC2MODE;    // len:    1 @ 0x001c, OSC2 MODE
    u8  OSC2PW;      // len:    1 @ 0x001d, OSC2 PULSE WIDTH
    s8  OSC3MOD;     // len:    1 @ 0x001e, OSC3 MOD
    s8  OSC3PENV;    // len:    1 @ 0x001f, OSC3 PITCH ENV DEPTH
    u16 OSC3WAVE;    // len:    2 @ 0x0020, OSC3 WAVE FORM
    u8  OSC3FEET;    // len:    1 @ 0x0022, OSC3 FEET
    s8  OSC3COARSE;  // len:    1 @ 0x0023, OSC3 COARSE TUNE
    s8  OSC3FINE;    // len:    1 @ 0x0024, OSC3 FINE TUNE
    u8  OSC3LOWFREQ; // len:    1 @ 0x0025, OSC3 LOW FREQ PITCH
    u8  OSC3MODE;    // len:    1 @ 0x0026, OSC3 MODE
    u8  NOISE;       // len:    1 @ 0x0027, NOISE
    u16 MODDPTH;     // len:    2 @ 0x0028, MOD DEPTH
    u8  MODMODE;     // len:    1 @ 0x002a, MOD MODE
    u8  MXROSC1;     // len:    1 @ 0x002b, OSC1 LEVEL
    u8  MXROSC2;     // len:    1 @ 0x002c, OSC2 LEVEL
    u8  MXROSC3;     // len:    1 @ 0x002d, OSC3 LEVEL
    u8  MXRNOISE;    // len:    1 @ 0x002e, NOISE LEVEL
    s8  MXRENVD;     // len:    1 @ 0x002f, MIXER ENV DEPTH
    u8  MXRENVS;     // len:    1 @ 0x0030, MIXER ENV SELECT
    u8  MXRDYNA;     // len:    1 @ 0x0031, MIXER DYNAMICS
    u8  FLTTYPE;     // len:    1 @ 0x0032, FILTER TYPE
    u8  FLTHPF2;     // len:    1 @ 0x0033, FILTER HPF STEP
    u16 FLTHPF1;     // len:    2 @ 0x0034, FILTER HPF
    u16 FLTFREQ;     // len:    2 @ 0x0036, FILTER FREQ
    u16 FLTRESO;     // len:    2 @ 0x0038, FILTER RESO
    s16 FLTENVD;     // len:    2 @ 0x003a, FILTER ENV DEPTH
    u8  FLTENVS;     // len:    1 @ 0x003c, FILTER ENV SELECT
    u8  FLTSLOPE;    // len:    1 @ 0x003d, FILTER SLOPE
    s16 FLTKYBD;     // len:    2 @ 0x003e, FILTER KEY FOLLOW
    s8  FLTMOD;      // len:    1 @ 0x0040, FILTER MOD
    u8  PADDING1;    // len:    1 @ 0x0041, __padding
    u8  AMPLVL;      // len:    1 @ 0x0042, AMP LEVEL
    s8  AMPMOD1;     // len:    1 @ 0x0043, AMP MOD
    u8  AMPMOD2;     // len:    1 @ 0x0044, AMP MOD STEP
    u8  AMPENVS;     // len:    1 @ 0x0045, AMP ENV SELECT
    u16 ENV1A;       // len:    2 @ 0x0046, ENV1 ATTACK
    u16 ENV1D;       // len:    2 @ 0x0048, ENV1 DECAY
    u16 ENV1S;       // len:    2 @ 0x004a, ENV1 SUSTAIN
    u16 ENV1R;       // len:    2 @ 0x004c, ENV1 RELEASE
    s8  ENV1KYBD1;   // len:    1 @ 0x004e, ENV1 KEY FOLLOW
    u8  ENV1KYBD2;   // len:    1 @ 0x004f, ENV1 KEY FOLLOW STEP
    u16 ENV2A;       // len:    2 @ 0x0050, ENV2 ATTACK
    u16 ENV2D;       // len:    2 @ 0x0052, ENV2 DECAY
    u16 ENV2S;       // len:    2 @ 0x0054, ENV2 SUSTAIN
    u16 ENV2R;       // len:    2 @ 0x0056, ENV2 RELEASE
    u8  ENV2MODE;    // len:    1 @ 0x0058, ENV2 MODE
    s8  ENV2KYBD1;   // len:    1 @ 0x0059, ENV2 KEY FOLLOW
    u8  ENV2KYBD2;   // len:    1 @ 0x005a, ENV2 KEY FOLLOW STEP
    u8  DYNPTCH;     // len:    1 @ 0x005b, DYNAMICS PITCH
    u8  DYNFLTT;     // len:    1 @ 0x005c, DYNAMICS FILTER
    u8  DYNAMP;      // len:    1 @ 0x005d, DYNAMICS AMP
    u8  PCHDRFT;     // len:    1 @ 0x005e, PITCH DRIFT
    u8  BNDPTCH2;    // len:    1 @ 0x005f, BENDER PITCH DEPTH STEP
    s8  BNDFLT;      // len:    1 @ 0x0060, BENDER FILTER DEPTH
    s8  BNDLFO;      // len:    1 @ 0x0061, MODULATION LFO DEPTH
    u16 BNDPTCH1;    // len:    2 @ 0x0062, BENDER PITCH DEPTH
    u16 PTATIME;     // len:    2 @ 0x0064, PORTAMENT TIME
    u8  PTAMODE;     // len:    1 @ 0x0066, PORTAMENT MODE
    u8  KBDMODE;     // len:    1 @ 0x0067, KEY MODE
    u8  EXPAND;      // len:    1 @ 0x0068, PARAMETER EXPANSION SWITCH
    u8  CONDITION;   // len:    1 @ 0x0069, CONDITION
    u8  PTACRV;      // len:    1 @ 0x006a, PORTAMENT CURVE TYPE
    s8  AFT_LFO;     // len:    1 @ 0x006b, AFTER TOUCH SENS LFO
    s8  AFT_FREQ;    // len:    1 @ 0x006c, AFTER TOUCH SENS FREQ
    s8  AFT_LEV;     // len:    1 @ 0x006d, AFTER TOUCH SENS LEVEL
    u16 PADDING2;    // len:    2 @ 0x006e, __padding
} MDLCORE;

/* MDLJD800COM: JD-800 Model Common */
/* Total length: 44 bytes (0x002c) */
typedef struct MDLJD800COM {
    u8  LEVEL;        // len:    1 @ 0x0000, Level
    u8  KEYA_RNG_LO;  // len:    1 @ 0x0001, Key Range A Low
    u8  KEYA_RNG_HI;  // len:    1 @ 0x0002, Key Range A High
    u8  KEYB_RNG_LO;  // len:    1 @ 0x0003, Key Range B Low
    u8  KEYB_RNG_HI;  // len:    1 @ 0x0004, Key Range B High
    u8  KEYC_RNG_LO;  // len:    1 @ 0x0005, Key Range C Low
    u8  KEYC_RNG_HI;  // len:    1 @ 0x0006, Key Range C High
    u8  KEYD_RNG_LO;  // len:    1 @ 0x0007, Key Range D Low
    u8  KEYD_RNG_HI;  // len:    1 @ 0x0008, Key Range D High
    u8  BND_RNG_DW;   // len:    1 @ 0x0009, Bender Range Down
    u8  BND_RNG_UP;   // len:    1 @ 0x000a, Bender Range Up
    u8  AFT_BEND;     // len:    1 @ 0x000b, After Touch Bend Sens
    u8  SOLO_SW;      // len:    1 @ 0x000c, Solo Switch
    u8  LEGATO_SW;    // len:    1 @ 0x000d, Solo Legato Switch
    u8  PORT_SW;      // len:    1 @ 0x000e, Portamento Switch
    u8  PORT_MODE;    // len:    1 @ 0x000f, Portamento Mode
    u8  PORT_TIME;    // len:    1 @ 0x0010, Portamento Time
    u8  EQ_MID_Q;     // len:    1 @ 0x0011, EQ Mid Q
    u16 EQ_LO_F;      // len:    2 @ 0x0012, EQ Low Frequency
    u16 EQ_MID_F;     // len:    2 @ 0x0014, EQ Mid Frequency
    u16 EQ_HI_F;      // len:    2 @ 0x0016, EQ High Frequency
    s16 EQ_LO_G;      // len:    2 @ 0x0018, EQ Low Gain
    s16 EQ_MID_G;     // len:    2 @ 0x001a, EQ Mid Gain
    s16 EQ_HI_G;      // len:    2 @ 0x001c, EQ High Gain
    u8  EQ_SW;        // len:    1 @ 0x001e, EQ Switch
    u8  UNISON;       // len:    1 @ 0x001f, Unison Switch
    u8  PADDING1[12]; // len:   12 @ 0x0020, __padding
} MDLJD800COM;

/* MDLJD800FxB: JD-800 Model Group B Effect */
/* Total length: 32 bytes (0x0020) */
typedef struct MDLJD800FxB {
    u8  SEQUENCE;    // len:    1 @ 0x0000, Sequence
    u8  DLY_SW;      // len:    1 @ 0x0001, DL Switch
    u8  DLY_C_SYNC;  // len:    1 @ 0x0002, Delay Center (sync sw)
    u8  DLY_C_TIME;  // len:    1 @ 0x0003, Delay Center (time)
    u8  DLY_C_NOTE;  // len:    1 @ 0x0004, Delay Center (note)
    u8  DLY_L_SYNC;  // len:    1 @ 0x0005, Delay Left (sync sw)
    u8  DLY_L_TIME;  // len:    1 @ 0x0006, Delay Left (time)
    u8  DLY_L_NOTE;  // len:    1 @ 0x0007, Delay Left (note)
    u8  DLY_R_SYNC;  // len:    1 @ 0x0008, Delay Right (sync sw)
    u8  DLY_R_TIME;  // len:    1 @ 0x0009, Delay Right (time)
    u8  DLY_R_NOTE;  // len:    1 @ 0x000a, Delay Right (note)
    u8  DLY_C_LEV;   // len:    1 @ 0x000b, Center Level
    u8  DLY_L_LEV;   // len:    1 @ 0x000c, Left Level
    u8  DLY_R_LEV;   // len:    1 @ 0x000d, Right Level
    u8  DLY_FB;      // len:    1 @ 0x000e, Delay Feedback
    u8  CHO_SW;      // len:    1 @ 0x000f, Chorus Sw
    u8  CHO_RATE;    // len:    1 @ 0x0010, Chorus Rate
    u8  CHO_DEPTH;   // len:    1 @ 0x0011, Chorus Depth
    u8  CHO_DLY;     // len:    1 @ 0x0012, Chorus Delay
    u8  CHO_FB;      // len:    1 @ 0x0013, Chorus Feedback
    u8  CHO_LEV;     // len:    1 @ 0x0014, Chorus Level
    u8  REV_SW;      // len:    1 @ 0x0015, Reverb Sw
    u8  REV_TYPE;    // len:    1 @ 0x0016, Reverb Type
    u8  REV_DLY;     // len:    1 @ 0x0017, Reverb Pre Delay
    u8  REV_ER_LEV;  // len:    1 @ 0x0018, Reverb ER Lev
    u8  REV_HF_DAMP; // len:    1 @ 0x0019, Reverb HF Damp
    u8  REV_TIME;    // len:    1 @ 0x001a, Reverb Time
    u8  REV_LEV;     // len:    1 @ 0x001b, Reverb Level
    u8  BAL;         // len:    1 @ 0x001c, Balance
    u8  LEVEL;       // len:    1 @ 0x001d, Level
    u16 PADDING1;    // len:    2 @ 0x001e, __padding
} MDLJD800FxB;

/* MDLJD800PTL: JD-800 Model Partial */
/* Total length: 80 bytes (0x0050) */
typedef struct MDLJD800PTL {
    u8  PTL_SW;      // len:    1 @ 0x0000, Layer Partial Switch
    u8  ACT_SW;      // len:    1 @ 0x0001, Active Partial Switch
    u8  VELO_CRV;    // len:    1 @ 0x0002, Velocity Curve
    u8  HOLD_CTRL;   // len:    1 @ 0x0003, Hold Control Switch
    u8  LFO1_WAV;    // len:    1 @ 0x0004, LFO1:Waveform
    u8  LFO1_SYNC;   // len:    1 @ 0x0005, LFO1:Rate sync
    u8  LFO1_RATE;   // len:    1 @ 0x0006, LFO1:Rate
    u8  LFO1_NOTE;   // len:    1 @ 0x0007, LFO1:Rate nt
    u8  LFO1_DLY;    // len:    1 @ 0x0008, LFO1:Delay time
    s8  LFO1_FADE;   // len:    1 @ 0x0009, LFO1:Fade time
    u8  LFO1_OFST;   // len:    1 @ 0x000a, LFO1:Offset
    u8  LFO1_KEY;    // len:    1 @ 0x000b, LFO1:Key trig
    u8  LFO2_WAV;    // len:    1 @ 0x000c, LFO2:Waveform
    u8  LFO2_SYNC;   // len:    1 @ 0x000d, LFO2:Rate Sync
    u8  LFO2_RATE;   // len:    1 @ 0x000e, LFO2:Rate
    u8  LFO2_NOTE;   // len:    1 @ 0x000f, LFO2:Rate nt
    u8  LFO2_DLY;    // len:    1 @ 0x0010, LFO2:Delay Time
    s8  LFO2_FADE;   // len:    1 @ 0x0011, LFO2:Fade time
    u8  LFO2_OFST;   // len:    1 @ 0x0012, LFO2:Offset
    u8  LFO2_KEY;    // len:    1 @ 0x0013, LFO2:Key trig
    u16 WAV_NUM;     // len:    2 @ 0x0014, WG:Waveform
    u8  WAV_SRC;     // len:    1 @ 0x0016, WG:Wave source
    u8  WAV_GAIN;    // len:    1 @ 0x0017, WG:Wave gain
    s8  PIT_COARSE;  // len:    1 @ 0x0018, WG:Pitch coarse
    s8  PIT_FINE;    // len:    1 @ 0x0019, WG:Pitch fine
    u8  PIT_RND;     // len:    1 @ 0x001a, WG:Pitch random
    u8  PIT_KF;      // len:    1 @ 0x001b, WG:Pitch KF
    u8  BENDER_SW;   // len:    1 @ 0x001c, WG:Bender Sw
    u8  AFT_BEND_SW; // len:    1 @ 0x001d, WG:Atch bend sw
    s8  LFO1_DEP;    // len:    1 @ 0x001e, WG:LFO1 depth
    s8  LFO2_DEP;    // len:    1 @ 0x001f, WG:LFO2 depth
    s8  LEVER_SENS;  // len:    1 @ 0x0020, WG:Lever sens
    s8  AFT_SENS;    // len:    1 @ 0x0021, WG:Atch msens
    s8  PENV_VSENS;  // len:    1 @ 0x0022, Pitch Env Velocity Sens
    s8  PENV_T_VS;   // len:    1 @ 0x0023, Pitch Env Time Velocity Sens
    s8  PENV_T_KF;   // len:    1 @ 0x0024, Pitch Env Time Keyfollow
    s8  PENV_L0;     // len:    1 @ 0x0025, Pitch Env L0
    s8  PENV_L1;     // len:    1 @ 0x0026, Pitch Env L1
    s8  PENV_L2;     // len:    1 @ 0x0027, Pitch Env L2
    u8  PENV_T1;     // len:    1 @ 0x0028, Pitch Env T1
    u8  PENV_T2;     // len:    1 @ 0x0029, Pitch Env T2
    u8  PENV_T3;     // len:    1 @ 0x002a, Pitch Env T3
    u8  TVF_FLT;     // len:    1 @ 0x002b, TVF:Filter mode
    u8  TVF_CUTOFF;  // len:    1 @ 0x002c, TVF:Cutoff freq
    u8  TVF_RESO;    // len:    1 @ 0x002d, TVF:Resonance
    u8  TVF_KF;      // len:    1 @ 0x002e, TVF:Cutoff KF
    s8  TVF_AFT;     // len:    1 @ 0x002f, TVF:Atch sens
    u8  TVF_LFO;     // len:    1 @ 0x0030, TVF:LFO select
    s8  TVF_LFO_DEP; // len:    1 @ 0x0031, TVF:LFO depth
    s8  TVF_ENV_DEP; // len:    1 @ 0x0032, TVF:ENV depth
    s8  FENV_VSENS;  // len:    1 @ 0x0033, F-ENV:Velo sens
    s8  FENV_T_VS;   // len:    1 @ 0x0034, F-ENV:T vsens
    s8  FENV_T_KF;   // len:    1 @ 0x0035, F-ENV:Time KF
    u8  FENV_L1;     // len:    1 @ 0x0036, F-ENV:Level 1
    u8  FENV_L2;     // len:    1 @ 0x0037, F-ENV:Level 2
    u8  FENV_SUS;    // len:    1 @ 0x0038, F-ENV:Sus Level
    u8  FENV_L4;     // len:    1 @ 0x0039, F-ENV:Level 4
    u8  FENV_T1;     // len:    1 @ 0x003a, F-ENV:Time 1
    u8  FENV_T2;     // len:    1 @ 0x003b, F-ENV:Time 2
    u8  FENV_T3;     // len:    1 @ 0x003c, F-ENV:Time 3
    u8  FENV_T4;     // len:    1 @ 0x003d, F-ENV:Time 4
    u8  TVA_BS_DIR;  // len:    1 @ 0x003e, TVA Bias Direction
    u8  TVA_BS_KEY;  // len:    1 @ 0x003f, TVA Bias Point
    s8  TVA_BS_LVL;  // len:    1 @ 0x0040, TVA:Bias level
    u8  TVA_LEVEL;   // len:    1 @ 0x0041, TVA:Level
    s8  TVA_AFT;     // len:    1 @ 0x0042, TVA After Touch Sens
    u8  TVA_LFO;     // len:    1 @ 0x0043, TVA:LFO select
    s8  TVA_LFO_DEP; // len:    1 @ 0x0044, TVA:LFO depth
    s8  AENV_VSENS;  // len:    1 @ 0x0045, A-ENV:Velo sens
    s8  AENV_T_VS;   // len:    1 @ 0x0046, A-ENV:T vsens
    s8  AENV_T_KF;   // len:    1 @ 0x0047, A-ENV:Time KF
    u8  AENV_L1;     // len:    1 @ 0x0048, A-ENV:Level 1
    u8  AENV_L2;     // len:    1 @ 0x0049, A-ENV:Level 2
    u8  AENV_SUS;    // len:    1 @ 0x004a, A-ENV:Sus level
    u8  AENV_T1;     // len:    1 @ 0x004b, A-ENV:Time 1
    u8  AENV_T2;     // len:    1 @ 0x004c, A-ENV:Time 2
    u8  AENV_T3;     // len:    1 @ 0x004d, A-ENV:Time 3
    u8  AENV_T4;     // len:    1 @ 0x004e, A-ENV:Time 4
    u8  PADDING1;    // len:    1 @ 0x004f, __padding
} MDLJD800PTL;

/* MDLJUNOX: JUNO-X Model Parameter */
/* Total length: 100 bytes (0x0064) */
typedef struct MDLJUNOX {
    u8  LFOWAVE;      // len:    1 @ 0x0000, LFO WAVE FORM
    u8  LFONOTE;      // len:    1 @ 0x0001, LFO RATE (Note)
    u16 LFORATE;      // len:    2 @ 0x0002, LFO RATE
    u16 LFODLY;       // len:    2 @ 0x0004, LFO DELAY TIME
    u8  LFOSYNC;      // len:    1 @ 0x0006, LFO SYNC SWITCH
    u8  LFOPIT;       // len:    1 @ 0x0007, LFO PITCH DEPTH
    u8  LFOFLT;       // len:    1 @ 0x0008, LFO FILTER DEPTH
    u8  LFOAMP;       // len:    1 @ 0x0009, LFO AMP DEPTH
    u8  SSAW_SW;      // len:    1 @ 0x000a, SUPER SAW SWITCH
    u8  PW_MODE;      // len:    1 @ 0x000b, PW MODE
    u8  PW_PWM;       // len:    1 @ 0x000c, PW PWM
    u8  SUB_PHASE;    // len:    1 @ 0x000d, SUB OSC PHASE SHIFT
    s8  PITCH;        // len:    1 @ 0x000e, PITCH
    s8  DETUNE;       // len:    1 @ 0x000f, OSC DETUNE
    s8  PAN_SPLIT;    // len:    1 @ 0x0010, OSC PAN SPLIT
    u8  PW_LEVEL;     // len:    1 @ 0x0011, PW LEVEL
    u8  SAW_LEVEL;    // len:    1 @ 0x0012, SAW LEVEL
    u8  SUB_LEVEL;    // len:    1 @ 0x0013, SUB OSC LEVEL
    u8  NZ_LEVEL;     // len:    1 @ 0x0014, NOISE LEVEL
    u8  AMP_LEVEL;    // len:    1 @ 0x0015, AMP LEVEL
    u8  AMP_CTRL;     // len:    1 @ 0x0016, AMP CONTROL SELECT
    s8  AMP_VSENS;    // len:    1 @ 0x0017, AMP VELOCITY SENS
    u16 FLT_FREQ;     // len:    2 @ 0x0018, FILTER CUTOFF FREQ
    u16 FLT_RESO;     // len:    2 @ 0x001a, FILTER RESONANCE
    s16 FENV_DEPTH;   // len:    2 @ 0x001c, FILTER ENV DEPTH
    s16 FLT_KF;       // len:    2 @ 0x001e, FILTER KEY FOLLOW
    u8  FLT_TYPE;     // len:    1 @ 0x0020, FILTER TYPE
    s8  FLT_VSENS;    // len:    1 @ 0x0021, FILTER VELOCITY SENS
    u16 PENV_A;       // len:    2 @ 0x0022, PITCH ENV ATTACK
    u16 PENV_D;       // len:    2 @ 0x0024, PITCH ENV DECAY
    u16 PENV_S;       // len:    2 @ 0x0026, PITCH ENV SUSTAIN
    u16 PENV_R;       // len:    2 @ 0x0028, PITCH ENV RELEASE
    s8  PENV_VSENS;   // len:    1 @ 0x002a, PITCH ENV VELOCITY SENS
    s8  PENV_DEPTH;   // len:    1 @ 0x002b, PITCH ENV DEPTH
    u16 ENV_A;        // len:    2 @ 0x002c, ENV ATTACK
    u16 ENV_D;        // len:    2 @ 0x002e, ENV DECAY
    u16 ENV_S;        // len:    2 @ 0x0030, ENV SUSTAIN
    u16 ENV_R;        // len:    2 @ 0x0032, ENV RELEASE
    s8  AFT_LFO;      // len:    1 @ 0x0034, AFTER TOUCH SENS LFO
    s8  AFT_FREQ;     // len:    1 @ 0x0035, AFTER TOUCH SENS FREQ
    s8  AFT_LEV;      // len:    1 @ 0x0036, AFTER TOUCH SENS LEVEL
    s8  BNDFLT;       // len:    1 @ 0x0037, BENDER FILTER DEPTH
    u16 BNDPTCH;      // len:    2 @ 0x0038, BENDER PITCH DEPTH
    s8  BNDLFO;       // len:    1 @ 0x003a, MODULATION LFO DEPTH
    u8  PTAMODE;      // len:    1 @ 0x003b, PORTAMENT MODE
    u16 PTATIME;      // len:    2 @ 0x003c, PORTAMENT TIME
    u8  PTACRV;       // len:    1 @ 0x003e, PORTAMENT CURVE TYPE
    u8  HPF;          // len:    1 @ 0x003f, HPF
    u8  KBDMODE;      // len:    1 @ 0x0040, KEY MODE
    u8  PCHDRFT;      // len:    1 @ 0x0041, PITCH DRIFT
    u8  CONDITION;    // len:    1 @ 0x0042, CONDITION
    u8  EXPAND;       // len:    1 @ 0x0043, PARAMETER EXPANSION SWITCH
    u8  PADDING1[32]; // len:   32 @ 0x0044, __padding
} MDLJUNOX;

/* MDLSYN0: Model Synth Parameter Interface type0 */
/* Total length: 112 bytes (0x0070) */
typedef struct MDLSYN0 {
    u8  MODEL;       // len:    1 @ 0x0000, Model
    u8  LFOWAVE;     // len:    1 @ 0x0001, LFO WAVE FORM
    u16 LFORATE;     // len:    2 @ 0x0002, LFO RATE
    u16 LFODLY;      // len:    2 @ 0x0004, LFO DELAY TIME
    s8  OSC1MOD;     // len:    1 @ 0x0006, OSC1 MOD
    s8  OSC1PENV;    // len:    1 @ 0x0007, OSC1 PITCH ENV DEPTH
    u8  OSC1DEST;    // len:    1 @ 0x0008, OSC1 DEST SELECT
    u8  OSC1ENVS;    // len:    1 @ 0x0009, OSC1 ENVT SELECT
    u16 OSC1WAVE;    // len:    2 @ 0x000a, OSC1 WAVE FORM
    u8  OSC1FEET;    // len:    1 @ 0x000c, OSC1 FEET
    s8  OSC1COARSE;  // len:    1 @ 0x000d, OSC1 COARSE TUNE
    s8  OSC1FINE;    // len:    1 @ 0x000e, OSC1 FINE TUNE
    u8  OSC1LOWFREQ; // len:    1 @ 0x000f, OSC1 LOW FREQ PITCH
    u8  OSC1MODE;    // len:    1 @ 0x0010, OSC1 MODE
    s8  OSC1PWM;     // len:    1 @ 0x0011, OSC1 PWM DEPTH
    u8  OSC1PLSW;    // len:    1 @ 0x0012, OSC1 PULSE WIDTH
    u8  OSC1PLSM;    // len:    1 @ 0x0013, OSC1 PULSE WIDTH MODE
    s8  OSC2MOD;     // len:    1 @ 0x0014, OSC2 MOD
    s8  OSC2PENV;    // len:    1 @ 0x0015, OSC2 PITCH ENV DEPTH
    u16 OSC2WAVE;    // len:    2 @ 0x0016, OSC2 WAVE FORM
    u8  OSC2FEET;    // len:    1 @ 0x0018, OSC2 FEET
    s8  OSC2COARSE;  // len:    1 @ 0x0019, OSC2 COARSE TUNE
    s8  OSC2FINE;    // len:    1 @ 0x001a, OSC2 FINE TUNE
    u8  OSC2LOWFREQ; // len:    1 @ 0x001b, OSC2 LOW FREQ PITCH
    u8  OSC2MODE;    // len:    1 @ 0x001c, OSC2 MODE
    u8  OSC2PW;      // len:    1 @ 0x001d, OSC2 PULSE WIDTH
    s8  OSC3MOD;     // len:    1 @ 0x001e, OSC3 MOD
    s8  OSC3PENV;    // len:    1 @ 0x001f, OSC3 PITCH ENV DEPTH
    u16 OSC3WAVE;    // len:    2 @ 0x0020, OSC3 WAVE FORM
    u8  OSC3FEET;    // len:    1 @ 0x0022, OSC3 FEET
    s8  OSC3COARSE;  // len:    1 @ 0x0023, OSC3 COARSE TUNE
    s8  OSC3FINE;    // len:    1 @ 0x0024, OSC3 FINE TUNE
    u8  OSC3LOWFREQ; // len:    1 @ 0x0025, OSC3 LOW FREQ PITCH
    u8  OSC3MODE;    // len:    1 @ 0x0026, OSC3 MODE
    u8  NOISE;       // len:    1 @ 0x0027, NOISE
    u16 MODDPTH;     // len:    2 @ 0x0028, MOD DEPTH
    u8  MODMODE;     // len:    1 @ 0x002a, MOD MODE
    u8  MXROSC1;     // len:    1 @ 0x002b, OSC1 LEVEL
    u8  MXROSC2;     // len:    1 @ 0x002c, OSC2 LEVEL
    u8  MXROSC3;     // len:    1 @ 0x002d, OSC3 LEVEL
    u8  MXRNOISE;    // len:    1 @ 0x002e, NOISE LEVEL
    s8  MXRENVD;     // len:    1 @ 0x002f, MIXER ENV DEPTH
    u8  MXRENVS;     // len:    1 @ 0x0030, MIXER ENV SELECT
    u8  MXRDYNA;     // len:    1 @ 0x0031, MIXER DYNAMICS
    u8  FLTTYPE;     // len:    1 @ 0x0032, FILTER TYPE
    u8  FLTHPF2;     // len:    1 @ 0x0033, FILTER HPF STEP
    u16 FLTHPF1;     // len:    2 @ 0x0034, FILTER HPF
    u16 FLTFREQ;     // len:    2 @ 0x0036, FILTER FREQ
    u16 FLTRESO;     // len:    2 @ 0x0038, FILTER RESO
    s16 FLTENVD;     // len:    2 @ 0x003a, FILTER ENV DEPTH
    u8  FLTENVS;     // len:    1 @ 0x003c, FILTER ENV SELECT
    u8  FLTSLOPE;    // len:    1 @ 0x003d, FILTER SLOPE
    s16 FLTKYBD;     // len:    2 @ 0x003e, FILTER KEY FOLLOW
    s8  FLTMOD;      // len:    1 @ 0x0040, FILTER MOD
    u8  PADDING1;    // len:    1 @ 0x0041, __padding
    u8  AMPLVL;      // len:    1 @ 0x0042, AMP LEVEL
    s8  AMPMOD1;     // len:    1 @ 0x0043, AMP MOD
    u8  AMPMOD2;     // len:    1 @ 0x0044, AMP MOD STEP
    u8  AMPENVS;     // len:    1 @ 0x0045, AMP ENV SELECT
    u16 ENV1A;       // len:    2 @ 0x0046, ENV1 ATTACK
    u16 ENV1D;       // len:    2 @ 0x0048, ENV1 DECAY
    u16 ENV1S;       // len:    2 @ 0x004a, ENV1 SUSTAIN
    u16 ENV1R;       // len:    2 @ 0x004c, ENV1 RELEASE
    s8  ENV1KYBD1;   // len:    1 @ 0x004e, ENV1 KEY FOLLOW
    u8  ENV1KYBD2;   // len:    1 @ 0x004f, ENV1 KEY FOLLOW STEP
    u16 ENV2A;       // len:    2 @ 0x0050, ENV2 ATTACK
    u16 ENV2D;       // len:    2 @ 0x0052, ENV2 DECAY
    u16 ENV2S;       // len:    2 @ 0x0054, ENV2 SUSTAIN
    u16 ENV2R;       // len:    2 @ 0x0056, ENV2 RELEASE
    u8  ENV2MODE;    // len:    1 @ 0x0058, ENV2 MODE
    s8  ENV2KYBD1;   // len:    1 @ 0x0059, ENV2 KEY FOLLOW
    u8  ENV2KYBD2;   // len:    1 @ 0x005a, ENV2 KEY FOLLOW STEP
    u8  DYNPTCH;     // len:    1 @ 0x005b, DYNAMICS PITCH
    u8  DYNFLTT;     // len:    1 @ 0x005c, DYNAMICS FILTER
    u8  DYNAMP;      // len:    1 @ 0x005d, DYNAMICS AMP
    u8  PCHDRFT;     // len:    1 @ 0x005e, PITCH DRIFT
    u8  BNDPTCH2;    // len:    1 @ 0x005f, BENDER PITCH DEPTH STEP
    s8  BNDFLT;      // len:    1 @ 0x0060, BENDER FILTER DEPTH
    s8  BNDLFO;      // len:    1 @ 0x0061, MODULATION LFO DEPTH
    u16 BNDPTCH1;    // len:    2 @ 0x0062, BENDER PITCH DEPTH
    u16 PTATIME;     // len:    2 @ 0x0064, PORTAMENT TIME
    u8  PTAMODE;     // len:    1 @ 0x0066, PORTAMENT MODE
    u8  KBDMODE;     // len:    1 @ 0x0067, KEY MODE
    u8  EXPAND;      // len:    1 @ 0x0068, PARAMETER EXPANSION SWITCH
    u8  CONDITION;   // len:    1 @ 0x0069, CONDITION
    u8  PTACRV;      // len:    1 @ 0x006a, PORTAMENT CURVE TYPE
    s8  AFT_LFO;     // len:    1 @ 0x006b, AFTER TOUCH SENS LFO
    s8  AFT_FREQ;    // len:    1 @ 0x006c, AFTER TOUCH SENS FREQ
    s8  AFT_LEV;     // len:    1 @ 0x006d, AFTER TOUCH SENS LEVEL
    u16 PADDING2;    // len:    2 @ 0x006e, __padding
} MDLSYN0;

/* MDLVDN: Vocal Designer Model */
/* Total length: 32 bytes (0x0020) */
typedef struct MDLVDN {
    u8 MSTR_LVL;      // len:    1 @ 0x0000, Level
    u8 MIC_LVL;       // len:    1 @ 0x0001, Mic Direct Level
    u8 VOC_LVL;       // len:    1 @ 0x0002, Vocoder Level
    u8 ALGO;          // len:    1 @ 0x0003, Algorithm
    u8 CRR_TYPE;      // len:    1 @ 0x0004, Carrier Type
    u8 RSV_CRR_BASIC; // len:    1 @ 0x0005, Reserved
    u8 LEVEL;         // len:    1 @ 0x0006, Carrier Basic Level
    s8 PAN;           // len:    1 @ 0x0007, Carrier Basic Pan
    s8 PIT_CRS;       // len:    1 @ 0x0008, Carrier Basic Coarse Tune
    s8 PIT_FINE;      // len:    1 @ 0x0009, Carrier Basic Fine Tune
    s8 OCTAVE;        // len:    1 @ 0x000a, Carrier Basic Octave Shift
    u8 PADDING1[21];  // len:   21 @ 0x000b, __padding
} MDLVDN;

/* MFX: Block */
/* Total length: 84 bytes (0x0054) */
typedef struct MFX {
    u8  mfxType;        // len:    1 @ 0x0000, Type
    u8  mfxSwitch;      // len:    1 @ 0x0001, MFX Switch
    u8  choSend;        // len:    1 @ 0x0002, MFX Chorus Send Level
    u8  revSend;        // len:    1 @ 0x0003, MFX Reverb Send Level
    u8  ctrlSrc1;       // len:    1 @ 0x0004, MFX CtrlSrc 1
    s8  ctrlSens1;      // len:    1 @ 0x0005, MFX CtrlSens 1
    u8  ctrlSrc2;       // len:    1 @ 0x0006, MFX CtrlSrc 2
    s8  ctrlSens2;      // len:    1 @ 0x0007, MFX CtrlSens 2
    u8  ctrlSrc3;       // len:    1 @ 0x0008, MFX CtrlSrc 3
    s8  ctrlSens3;      // len:    1 @ 0x0009, MFX CtrlSens 3
    u8  ctrlSrc4;       // len:    1 @ 0x000a, MFX CtrlSrc 4
    s8  ctrlSens4;      // len:    1 @ 0x000b, MFX CtrlSens 4
    u8  ctrlAsgn_1;     // len:    1 @ 0x000c, MFX CtrlAsgn 1
    u8  reserved_1[3];  // len:    3 @ 0x000d, implicit padding
    s16 param_1;        // len:    2 @ 0x0010, MFX Parameter 1
    u8  reserved_2[62]; // len:   62 @ 0x0012, implicit padding
    u32 PADDING1;       // len:    4 @ 0x0050, __padding
} MFX;

/* OD: Driver */
/* Total length: 8 bytes (0x0008) */
typedef struct OD {
    u8 DRV;         // len:    1 @ 0x0000, Drive
    u8 CHO_SEND;    // len:    1 @ 0x0001, Chorus Send Level
    u8 REV_SEND;    // len:    1 @ 0x0002, Reverb Send Level
    u8 DLY_SEND;    // len:    1 @ 0x0003, Delay Send Level
    u8 SW;          // len:    1 @ 0x0004, Drive Switch
    u8 PADDING1[3]; // len:    3 @ 0x0005, __padding
} OD;

/* PCMR_CMN: PCMRhythm Common */
/* Total length: 28 bytes (0x001c) */
typedef struct PCMR_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u16 PADDING1;         // len:    2 @ 0x0010, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Phrase Number
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    u16 PADDING2;         // len:    2 @ 0x0015, __padding
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x0017, Phrase Velo Rate
    s8  PHRASE_VEL_SHIFT; // len:    1 @ 0x0018, Phrase Velo Shift
    u8  PADDING3[3];      // len:    3 @ 0x0019, __padding
} PCMR_CMN;

/* PCMR_PTL: PCMRhythm Partial */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMR_PTL {
    u16 INST_NUM;      // len:    2 @ 0x0000, Inst Number
    u8  INST_GTYPE;    // len:    1 @ 0x0002, Inst Bank
    u8  PADDING1;      // len:    1 @ 0x0003, __padding
    u16 INST_GID;      // len:    2 @ 0x0004, Inst Group ID
    u8  LEVEL;         // len:    1 @ 0x0006, Level
    u8  PADDING2;      // len:    1 @ 0x0007, __padding
    s8  PAN;           // len:    1 @ 0x0008, Pan
    u8  CHO_SEND;      // len:    1 @ 0x0009, Chorus Send Level
    u8  REV_SEND;      // len:    1 @ 0x000a, Reverb Send Level
    u8  MUTE_GRP;      // len:    1 @ 0x000b, Mute Group
    u8  OUT_ASGN;      // len:    1 @ 0x000c, Output Assign
    s8  KEY_OFST;      // len:    1 @ 0x000d, Key Offset
    s8  PIT_FINE_OFST; // len:    1 @ 0x000e, Fine Tune Offset
    s8  CUTOFF_OFST;   // len:    1 @ 0x000f, TVF Cutoff Offset
    s8  RESO_OFST;     // len:    1 @ 0x0010, TVF Resonance Offset
    s8  TVA_ATK_OFST;  // len:    1 @ 0x0011, TVA Attack Time Offset
    s8  TVA_DCY_OFST;  // len:    1 @ 0x0012, TVA Decay Time Offset
    s8  TVA_REL_OFST;  // len:    1 @ 0x0013, TVA Release Time Offset
} PCMR_PTL;

/* PCMS_CMN: PCMSynth Common */
/* Total length: 20 bytes (0x0014) */
typedef struct PCMS_CMN {
    u8 UNISON_SW;          // len:    1 @ 0x0000, Unison Switch
    u8 UNISON_SIZE;        // len:    1 @ 0x0001, Unison Size
    u8 UNISON_DETN;        // len:    1 @ 0x0002, Unison Detune
    u8 PADDING1;           // len:    1 @ 0x0003, __padding
    u8 BEND_RANGE_FINE_UP; // len:    1 @ 0x0004, Bend Range Fine Up
    u8 BEND_RANGE_FINE_DW; // len:    1 @ 0x0005, Bend Range Fine Down
    u8 RND_PIT_VAL;        // len:    1 @ 0x0006, Pitch Drift
    u8 RND_PIT_NUM;        // len:    1 @ 0x0007, Pitch Drift Cycle Number
    u8 CONDITION;          // len:    1 @ 0x0008, Condition
    u8 PADDING2[11];       // len:   11 @ 0x0009, __padding
} PCMS_CMN;

/* PCMS_PMT: PCMSynth PMT */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PMT {
    u8  STRUCT12;        // len:    1 @ 0x0000, Structure1-2
    u8  STRUCT34;        // len:    1 @ 0x0001, Structure3-4
    u16 PADDING1;        // len:    2 @ 0x0002, __padding
    u8  RING12_LEVEL;    // len:    1 @ 0x0004, RING1-2 Level
    u8  RING34_LEVEL;    // len:    1 @ 0x0005, RING3-4 Level
    u8  RING_OSC1_LEVEL; // len:    1 @ 0x0006, RING OSC1 Level
    u8  RING_OSC2_LEVEL; // len:    1 @ 0x0007, RING OSC2 Level
    u8  RING_OSC3_LEVEL; // len:    1 @ 0x0008, RING OSC3 Level
    u8  RING_OSC4_LEVEL; // len:    1 @ 0x0009, RING OSC4 Level
    u16 PADDING2;        // len:    2 @ 0x000a, __padding
    u16 XMOD12_DEPTH;    // len:    2 @ 0x000c, CrossMod1-2 Depth
    u16 XMOD34_DEPTH;    // len:    2 @ 0x000e, CrossMod3-4 Depth
    u8  XMOD_OSC1_LEVEL; // len:    1 @ 0x0010, CrossMod OSC1 Level
    u8  XMOD_OSC2_LEVEL; // len:    1 @ 0x0011, CrossMod OSC2 Level
    u8  XMOD_OSC3_LEVEL; // len:    1 @ 0x0012, CrossMod OSC3 Level
    u8  XMOD_OSC4_LEVEL; // len:    1 @ 0x0013, CrossMod OSC4 Level
    u8  PTL_PHS_LOCK;    // len:    1 @ 0x0014, Partial Phase Lock
    u8  XMOD2_12_DEPTH;  // len:    1 @ 0x0015, CrossMod2 1-2 Depth
    u8  XMOD2_34_DEPTH;  // len:    1 @ 0x0016, CrossMod2 3-4 Depth
    u8  PADDING3[13];    // len:   13 @ 0x0017, __padding
} PCMS_PMT;

/* PCMS_PTL: PCMSynth Partial */
/* Total length: 36 bytes (0x0024) */
typedef struct PCMS_PTL {
    u8  OSC_TYPE;         // len:    1 @ 0x0000, OSC Type
    u8  VA_FORM;          // len:    1 @ 0x0001, VA Waveform
    u16 SYNC_WAV_NUM;     // len:    2 @ 0x0002, PCM-Sync Wave Number
    u8  PW;               // len:    1 @ 0x0004, Pulse Width
    s8  PWM_DEPTH;        // len:    1 @ 0x0005, PWM Depth
    u8  SSAW_DETUNE;      // len:    1 @ 0x0006, SuperSAW Detune
    u8  CLICK_TYPE;       // len:    1 @ 0x0007, Click Type
    u16 HPF_CUTOFF;       // len:    2 @ 0x0008, HPF Cutoff
    u8  FILTER_TYPE;      // len:    1 @ 0x000a, Filter Type
    u8  FILTER_SLOPE;     // len:    1 @ 0x000b, Filter Slope
    u8  ADSR_ENV_SW;      // len:    1 @ 0x000c, ADSREnv Switch
    u8  FAT;              // len:    1 @ 0x000d, Fat
    u8  VCF_TYPE;         // len:    1 @ 0x000e, VCF Type
    u8  OSC_ATT;          // len:    1 @ 0x000f, OSC Attenuator
    u8  CUTOFF_KF_BP;     // len:    1 @ 0x0010, Cutoff Keyfollow Base Point
    u8  VA_INVERT_SW;     // len:    1 @ 0x0011, VA Waveform Invert Switch
    s8  FENV_FINE_DEPTH;  // len:    1 @ 0x0012, TVF Env Fine Depth
    u8  PENV_LFO_TRIG_SW; // len:    1 @ 0x0013, PENV LFO Trigger Switch
    u8  FENV_LFO_TRIG_SW; // len:    1 @ 0x0014, FENV LFO Trigger Switch
    u8  AENV_LFO_TRIG_SW; // len:    1 @ 0x0015, AENV LFO Trigger Switch
    u8  PITCH_DOWN_DEPTH; // len:    1 @ 0x0016, Pitch Down Depth
    u8  VCF_GC;           // len:    1 @ 0x0017, VCF Gain Correction
    u8  VA_INIT_PHASE;    // len:    1 @ 0x0018, VA Init Phase
    u8  PADDING1[11];     // len:   11 @ 0x0019, __padding
} PCMS_PTL;

/* PCMT_CMN: PCMTone Common */
/* Total length: 64 bytes (0x0040) */
typedef struct PCMT_CMN {
    u8  NAME_1;           // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15];   // len:   15 @ 0x0001, implicit padding
    u8  CATEGORY;         // len:    1 @ 0x0010, Category
    u8  PADDING1;         // len:    1 @ 0x0011, __padding
    u16 PHRASE;           // len:    2 @ 0x0012, Reserved
    u8  LEVEL;            // len:    1 @ 0x0014, Level
    s8  PAN;              // len:    1 @ 0x0015, Pan
    u16 PADDING2;         // len:    2 @ 0x0016, __padding
    u8  PRIORITY;         // len:    1 @ 0x0018, Priority
    s8  PIT_CRS;          // len:    1 @ 0x0019, Tone Coarse Tune
    s8  PIT_FINE;         // len:    1 @ 0x001a, Tone Fine Tune
    s8  OCTAVE;           // len:    1 @ 0x001b, Octave Shift
    u8  STRETCH;          // len:    1 @ 0x001c, Stretch Tune Depth
    u8  ANALOG_FEEL;      // len:    1 @ 0x001d, Analog Feel
    u8  MONO_POLY;        // len:    1 @ 0x001e, Mono/Poly
    u8  LEGATO_SW;        // len:    1 @ 0x001f, Legato Switch
    u8  RETRIG_INTVL;     // len:    1 @ 0x0020, Legato Retrigger Interval
    u8  PORTA_SW;         // len:    1 @ 0x0021, Portamento Switch
    u8  PORTA_MODE;       // len:    1 @ 0x0022, Portamento Mode
    u8  PORTA_TYPE;       // len:    1 @ 0x0023, Portamento Type
    u8  PADDING3;         // len:    1 @ 0x0024, __padding
    u8  PORTA_START;      // len:    1 @ 0x0025, Portamento Start
    u16 PORTA_TIME;       // len:    2 @ 0x0026, Portamento Time
    u8  BEND_RANGE_UP;    // len:    1 @ 0x0028, Bend Range Up
    u8  BEND_RANGE_DW;    // len:    1 @ 0x0029, Bend Range Down
    u8  BEND_MODE;        // len:    1 @ 0x002a, Bend Mode
    u8  SOFT_LEVEL_SENS;  // len:    1 @ 0x002b, Soft Level Sens
    u8  PHRASE_OCT;       // len:    1 @ 0x002c, Reserved
    u8  PHRASE_VEL_RATE;  // len:    1 @ 0x002d, Reserved
    u8  PHRASE_VEL_SHIFT; // len:    1 @ 0x002e, Reserved
    u8  SYMP_DEPTH;       // len:    1 @ 0x002f, Reserved
    u8  PORTA_CRV;        // len:    1 @ 0x0030, Portamento Curve Type
    u8  PTL_LFO_LOCK;     // len:    1 @ 0x0031, Partial LFO Phase Lock
    u8  PADDING4[14];     // len:   14 @ 0x0032, __padding
} PCMT_CMN;

/* PCMT_PMT_PMT: PMT */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PMT_PMT {
    u8 PTL_SW;      // len:    1 @ 0x0000, Partial Switch
    u8 PADDING1[3]; // len:    3 @ 0x0001, __padding
    u8 KRANGE_LO;   // len:    1 @ 0x0004, KeyRange Lower
    u8 KRANGE_UP;   // len:    1 @ 0x0005, KeyRange Upper
    u8 KFADE_LO;    // len:    1 @ 0x0006, KeyFade Lower
    u8 KFADE_UP;    // len:    1 @ 0x0007, KeyFade Upper
    u8 VRANGE_LO;   // len:    1 @ 0x0008, VeloRange Lower
    u8 VRANGE_UP;   // len:    1 @ 0x0009, VeloRange Upper
    u8 VFADE_LO;    // len:    1 @ 0x000a, VeloFade Lower
    u8 VFADE_UP;    // len:    1 @ 0x000b, VeloFade Upper
} PCMT_PMT_PMT;

/* PCMT_PMT: PCMTone PartialMixTable */
/* Total length: 52 bytes (0x0034) */
typedef struct PCMT_PMT {
    u8           VEL_CTRL;      // len:    1 @ 0x0000, Velocity Control
    u8           PMT_LEVEL_CRV; // len:    1 @ 0x0001, PMT Level Curve
    u16          PADDING1;      // len:    2 @ 0x0002, __padding
    PCMT_PMT_PMT PMT[4];        // len:   48 @ 0x0004, PMT
} PCMT_PMT;

/* PCMT_PTL_MCTL: Matrix Control */
/* Total length: 12 bytes (0x000c) */
typedef struct PCMT_PTL_MCTL {
    u8 SRC;         // len:    1 @ 0x0000, Source
    u8 DST1;        // len:    1 @ 0x0001, Destination 1
    s8 SENS1;       // len:    1 @ 0x0002, Sens 1
    u8 DST2;        // len:    1 @ 0x0003, Destination 2
    s8 SENS2;       // len:    1 @ 0x0004, Sens 2
    u8 DST3;        // len:    1 @ 0x0005, Destination 3
    s8 SENS3;       // len:    1 @ 0x0006, Sens 3
    u8 DST4;        // len:    1 @ 0x0007, Destination 4
    s8 SENS4;       // len:    1 @ 0x0008, Sens 4
    u8 PADDING1[3]; // len:    3 @ 0x0009, __padding
} PCMT_PTL_MCTL;

/* PCMT_PTL: PCMTone Partial */
/* Total length: 124 bytes (0x007c) */
typedef struct PCMT_PTL {
    u8            LEVEL;         // len:    1 @ 0x0000, Level
    u8            PADDING1;      // len:    1 @ 0x0001, __padding
    s8            PIT_CRS;       // len:    1 @ 0x0002, Coarse Tune
    s8            PIT_FINE;      // len:    1 @ 0x0003, Fine Tune
    u16           PIT_RND;       // len:    2 @ 0x0004, Random Pitch Depth
    s8            PAN;           // len:    1 @ 0x0006, Pan
    s8            PAN_KF;        // len:    1 @ 0x0007, Pan Keyfollow
    u8            PAN_RND;       // len:    1 @ 0x0008, Random Pan Depth
    s8            PAN_ALT;       // len:    1 @ 0x0009, Alternate Pan Depth
    u8            ENV_MODE;      // len:    1 @ 0x000a, Envelope Mode
    u8            DELAY_MODE;    // len:    1 @ 0x000b, Delay Mode
    u8            DLY_TIME_SYNC; // len:    1 @ 0x000c, DelayTime Sync
    u8            DLY_TIME_NOTE; // len:    1 @ 0x000d, DelayTime (note)
    u16           DLY_TIME;      // len:    2 @ 0x000e, DelayTime
    u8            CHO_SEND;      // len:    1 @ 0x0010, Chorus Send Level
    u8            REV_SEND;      // len:    1 @ 0x0011, Reverb Send Level
    u8            RX_BEND;       // len:    1 @ 0x0012, Receive Bender
    u8            RX_EXPR;       // len:    1 @ 0x0013, Receive Expression
    u8            RX_HOLD;       // len:    1 @ 0x0014, Receive Hold-1
    u8            REDAMP_SW;     // len:    1 @ 0x0015, Redamper Switch
    u8            OUT_ASGN;      // len:    1 @ 0x0016, Output Assign
    u8            WAV_GTYPE;     // len:    1 @ 0x0017, Wave Group Type
    u16           WAV_GID;       // len:    2 @ 0x0018, Wave Group ID
    u16           WAV_NUM_L;     // len:    2 @ 0x001a, Wave Number L
    u16           WAV_NUM_R;     // len:    2 @ 0x001c, Wave Number R
    u8            WAV_GAIN;      // len:    1 @ 0x001e, Gain
    u8            FXM_SW;        // len:    1 @ 0x001f, FXM Switch
    u8            FXM_COLOR;     // len:    1 @ 0x0020, FXM Color
    u8            FXM_DEPTH;     // len:    1 @ 0x0021, FXM Depth
    s16           PIT_KF;        // len:    2 @ 0x0022, Pitch Keyfollow
    u8            SOFT_EQ_SENS;  // len:    1 @ 0x0024, Soft EQ Sens
    u8            FILTER_TYPE;   // len:    1 @ 0x0025, TVF Filter Type
    u16           PADDING2;      // len:    2 @ 0x0026, __padding
    u16           CUTOFF;        // len:    2 @ 0x0028, TVF Cutoff Frequency
    s16           CUTOFF_KF;     // len:    2 @ 0x002a, TVF Cutoff Keyfollow
    u8            CUTOFF_VCRV;   // len:    1 @ 0x002c, TVF Cutoff Velocity Curve
    s8            CUTOFF_VSENS;  // len:    1 @ 0x002d, TVF Cutoff Velocity Sens
    u16           RESO;          // len:    2 @ 0x002e, TVF Resonance
    s8            RESO_VSENS;    // len:    1 @ 0x0030, TVF Resonance Velocity Sens
    s8            BIAS_LEVEL;    // len:    1 @ 0x0031, Bias Level
    u8            BIAS_POS;      // len:    1 @ 0x0032, Bias Position
    u8            BIAS_DIR;      // len:    1 @ 0x0033, Bias Direction
    u8            LEVEL_VCRV;    // len:    1 @ 0x0034, TVA Level Velocity Curve
    s8            LEVEL_VSENS;   // len:    1 @ 0x0035, TVA Level Velocity Sens
    s8            PENV_TKF;      // len:    1 @ 0x0036, Pitch Env Time Keyfollow
    s8            FENV_TKF;      // len:    1 @ 0x0037, TVF Env Time Keyfollow
    s8            AENV_TKF;      // len:    1 @ 0x0038, TVA Env Time Keyfollow
    s8            VIB_PIT_SENS;  // len:    1 @ 0x0039, Vibrato Pitch Sens
    s8            VIB_CUT_SENS;  // len:    1 @ 0x003a, Vibrato Cutoff Sens
    s8            VIB_AMP_SENS;  // len:    1 @ 0x003b, Vibrato Level Sens
    PCMT_PTL_MCTL MCTL[4];       // len:   48 @ 0x003c, Matrix Control
    u8            DAMP_FREE;     // len:    1 @ 0x006c, Damper Free Note
    u8            STEREO_WIDTH;  // len:    1 @ 0x006d, Stereo Width
    s8            STEREO_DETN;   // len:    1 @ 0x006e, Stereo Detune
    s8            DF_DCY_OFST;   // len:    1 @ 0x006f, Damper Free Decay Offset
    u8            TEMPO_SYNC;    // len:    1 @ 0x0070, Wave Tempo Sync
    u8            PADDING3[11];  // len:   11 @ 0x0071, __padding
} PCMT_PTL;

/* PEQ: Part EQ */
/* Total length: 12 bytes (0x000c) */
typedef struct PEQ {
    s8 EQ_IN_GAIN;  // len:    1 @ 0x0000, EQ Input Gain
    s8 EQ_LO_GAIN;  // len:    1 @ 0x0001, EQ Low Gain
    s8 EQ_MID_GAIN; // len:    1 @ 0x0002, EQ Mid Gain
    s8 EQ_HI_GAIN;  // len:    1 @ 0x0003, EQ High Gain
    u8 EQ_LO_FREQ;  // len:    1 @ 0x0004, EQ Low Frequency
    u8 EQ_MID_FREQ; // len:    1 @ 0x0005, EQ Mid Frequency
    u8 EQ_HI_FREQ;  // len:    1 @ 0x0006, EQ High Frequency
    u8 EQ_MID_Q;    // len:    1 @ 0x0007, EQ Mid Q
    u8 EQ_SW;       // len:    1 @ 0x0008, Switch
    u8 PADDING1[3]; // len:    3 @ 0x0009, __padding
} PEQ;

/* PNLFUNC: Panel Surface Interface */
/* Total length: 6 bytes (0x0006) */
typedef struct PNLFUNC {
    u16 KNOB; // len:    2 @ 0x0000, Panel Function Number
    u16 SW;   // len:    2 @ 0x0002, Panel Function Number
    u16 ENC;  // len:    2 @ 0x0004, Panel Function Number
} PNLFUNC;

/* PTL_AENV: Partial TVA Envelope */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_AENV {
    s8  T1_VSENS; // len:    1 @ 0x0000, TVA Env Time1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0001, TVA Env Time4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0002, TVA Env Time1
    u16 T2;       // len:    2 @ 0x0004, TVA Env Time2
    u16 T3;       // len:    2 @ 0x0006, TVA Env Time3
    u16 T4;       // len:    2 @ 0x0008, TVA Env Time4
    u16 L1;       // len:    2 @ 0x000a, TVA Env Level1
    u16 L2;       // len:    2 @ 0x000c, TVA Env Level2
    u16 L3;       // len:    2 @ 0x000e, TVA Env Level3
} PTL_AENV;

/* PTL_EQ: Partial EQ */
/* Total length: 16 bytes (0x0010) */
typedef struct PTL_EQ {
    s16 LO_GAIN;  // len:    2 @ 0x0000, EQ Low Gain
    s16 MID_GAIN; // len:    2 @ 0x0002, EQ Mid Gain
    s16 HI_GAIN;  // len:    2 @ 0x0004, EQ High Gain
    u16 LO_FREQ;  // len:    2 @ 0x0006, EQ Low Frequency
    u16 MID_FREQ; // len:    2 @ 0x0008, EQ Mid Frequency
    u16 HI_FREQ;  // len:    2 @ 0x000a, EQ High Frequency
    u8  MID_Q;    // len:    1 @ 0x000c, EQ Mid Q
    u8  SW;       // len:    1 @ 0x000d, EQ Switch
    u16 PADDING1; // len:    2 @ 0x000e, __padding
} PTL_EQ;

/* PTL_FENV: Partial TVF Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_FENV {
    s8  DEPTH;    // len:    1 @ 0x0000, TVF Env Depth
    u8  VCRV;     // len:    1 @ 0x0001, TVF Env Velocity Curve
    s8  VSENS;    // len:    1 @ 0x0002, TVF Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0003, TVF Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0004, TVF Env T4 Velocity Sens
    u8  PADDING1; // len:    1 @ 0x0005, __padding
    u16 T1;       // len:    2 @ 0x0006, TVF Env Time1
    u16 T2;       // len:    2 @ 0x0008, TVF Env Time2
    u16 T3;       // len:    2 @ 0x000a, TVF Env Time3
    u16 T4;       // len:    2 @ 0x000c, TVF Env Time4
    u16 L0;       // len:    2 @ 0x000e, TVF Env Level0
    u16 L1;       // len:    2 @ 0x0010, TVF Env Level1
    u16 L2;       // len:    2 @ 0x0012, TVF Env Level2
    u16 L3;       // len:    2 @ 0x0014, TVF Env Level3
    u16 L4;       // len:    2 @ 0x0016, TVF Env Level4
} PTL_FENV;

/* PTL_LFO_LFO: LFO */
/* Total length: 52 bytes (0x0034) */
typedef struct PTL_LFO_LFO {
    u8  FORM;           // len:    1 @ 0x0000, Waveform
    u8  RATE_SYNC;      // len:    1 @ 0x0001, Rate Sync
    u8  RATE_NOTE;      // len:    1 @ 0x0002, Rate (note)
    u8  STEP_MAX;       // len:    1 @ 0x0003, Step Size
    u16 RATE;           // len:    2 @ 0x0004, Rate
    s8  OFST;           // len:    1 @ 0x0006, Offset
    u8  RATE_DETN;      // len:    1 @ 0x0007, Rate Detune
    u16 DELAY;          // len:    2 @ 0x0008, Delay Time
    s8  DELAY_KF;       // len:    1 @ 0x000a, Delay Time Keyfolow
    u8  FADE_MODE;      // len:    1 @ 0x000b, Fade Mode
    u16 FADE;           // len:    2 @ 0x000c, Fade Time
    u8  KEY_TRIG;       // len:    1 @ 0x000e, Key Trigger
    s8  PIT_DEPTH;      // len:    1 @ 0x000f, Pitch Depth
    s8  TVF_DEPTH;      // len:    1 @ 0x0010, TVF Depth
    s8  TVA_DEPTH;      // len:    1 @ 0x0011, TVA Depth
    s8  PAN_DEPTH;      // len:    1 @ 0x0012, PAN Depth
    u8  PHASE_POS;      // len:    1 @ 0x0013, Phase Position
    s8  STEP_1;         // len:    1 @ 0x0014, Step 1
    u8  reserved_1[15]; // len:   15 @ 0x0015, implicit padding
    u8  STEP_CURVE_1;   // len:    1 @ 0x0024, Step Curve 1
    u8  reserved_2[15]; // len:   15 @ 0x0025, trailing padding
} PTL_LFO_LFO;

/* PTL_LFO: Partial LFO */
/* Total length: 104 bytes (0x0068) */
typedef struct PTL_LFO {
    PTL_LFO_LFO LFO[2]; // len:  104 @ 0x0000, LFO
} PTL_LFO;

/* PTL_PENV: Partial Pitch Envelope */
/* Total length: 24 bytes (0x0018) */
typedef struct PTL_PENV {
    s8  DEPTH;    // len:    1 @ 0x0000, Pitch Env Depth
    s8  VSENS;    // len:    1 @ 0x0001, Pitch Env Velocity Sens
    s8  T1_VSENS; // len:    1 @ 0x0002, Pitch Env T1 Velocity Sens
    s8  T4_VSENS; // len:    1 @ 0x0003, Pitch Env T4 Velocity Sens
    u16 T1;       // len:    2 @ 0x0004, Pitch Env Time1
    u16 T2;       // len:    2 @ 0x0006, Pitch Env Time2
    u16 T3;       // len:    2 @ 0x0008, Pitch Env Time3
    u16 T4;       // len:    2 @ 0x000a, Pitch Env Time4
    s16 L0;       // len:    2 @ 0x000c, Pitch Env Level0
    s16 L1;       // len:    2 @ 0x000e, Pitch Env Level1
    s16 L2;       // len:    2 @ 0x0010, Pitch Env Level2
    s16 L3;       // len:    2 @ 0x0012, Pitch Env Level3
    s16 L4;       // len:    2 @ 0x0014, Pitch Env Level4
    u8  VCRV;     // len:    1 @ 0x0016, Pitch Env Velocity Curve
    u8  PADDING1; // len:    1 @ 0x0017, __padding
} PTL_PENV;

/* RCMP: System RhythmComp */
/* Total length: 8 bytes (0x0008) */
typedef struct RCMP {
    u8 SW;        // len:    1 @ 0x0000, Comp Switch
    u8 ATTCK;     // len:    1 @ 0x0001, Comp Attack Time
    u8 RELEASE;   // len:    1 @ 0x0002, Comp Release Time
    s8 THRESHOLD; // len:    1 @ 0x0003, Comp Threshold
    u8 RATIO;     // len:    1 @ 0x0004, Comp Ratio
    u8 KNEE;      // len:    1 @ 0x0005, Comp Knee
    s8 POSTGAIN;  // len:    1 @ 0x0006, Comp Output Gain
    u8 OUT_ASGN;  // len:    1 @ 0x0007, Comp Output Assign
} RCMP;

/* RDAPFX: RD Piano Sympathetic Resonance */
/* Total length: 4 bytes (0x0004) */
typedef struct RDAPFX {
    u8 SW;        // len:    1 @ 0x0000, SymReso Switch
    u8 VSB_TYPE;  // len:    1 @ 0x0001, Reserved
    u8 VSB_DEPTH; // len:    1 @ 0x0002, SymReso Depth
    u8 CABI_RESO; // len:    1 @ 0x0003, Cabinet Resonance
} RDAPFX;

/* SC: System Common */
/* Total length: 100 bytes (0x0064) */
typedef struct SC {
    s16 TUNE;               // len:    2 @ 0x0000, Master Tune
    s8  KEY_SHIFT;          // len:    1 @ 0x0002, Master Key Shift
    u8  SCALE_TUNE_SW;      // len:    1 @ 0x0003, ScaleTune Sw
    u8  PERF_CTRL_CH;       // len:    1 @ 0x0004, Scene Control Channel
    u8  RESERVED_BASIC_CH;  // len:    1 @ 0x0005, Reserved
    u8  REMOTE_KEY;         // len:    1 @ 0x0006, Remote Keyboard
    u8  CTRL_SRC_SEL;       // len:    1 @ 0x0007, Control Source Select
    u8  SYS_CTRL_SRC_1;     // len:    1 @ 0x0008, System Control Source(011)
    u8  reserved_1[3];      // len:    3 @ 0x0009, implicit padding
    u16 TEMPO;              // len:    2 @ 0x000c, System Tempo
    u8  OR_TEMPO;           // len:    1 @ 0x000e, Tempo Source
    u8  RX_PC;              // len:    1 @ 0x000f, Receive Program Change
    u8  RX_BS;              // len:    1 @ 0x0010, Receive Bank Select
    u8  CHO_SRC;            // len:    1 @ 0x0011, Chorus Source
    u8  REV_SRC;            // len:    1 @ 0x0012, Reverb Source
    u8  DLY_SRC;            // len:    1 @ 0x0013, Delay Source
    u8  MIC_NS_SW;          // len:    1 @ 0x0014, Noise Suppressor Switch
    s8  MIC_NS_THRESHOLD;   // len:    1 @ 0x0015, Mic Noise Supressor Threshold
    u8  MIC_NS_RELEASE;     // len:    1 @ 0x0016, Mic Noise Supressor Release
    u8  MIC_COMP_SW;        // len:    1 @ 0x0017, Mic Comp Switch
    u8  MIC_COMP_ATTCK;     // len:    1 @ 0x0018, Mic Comp Attack Time
    u8  MIC_COMP_RELEASE;   // len:    1 @ 0x0019, Mic Comp Release Time
    s8  MIC_COMP_THRESHOLD; // len:    1 @ 0x001a, Mic Comp Threshold
    u8  MIC_COMP_RATIO;     // len:    1 @ 0x001b, Mic Comp Ratio
    u8  MIC_COMP_KNEE;      // len:    1 @ 0x001c, Mic Comp Knee
    s8  MIC_COMP_POSTGAIN;  // len:    1 @ 0x001d, Mic Comp Output Gain
    u8  MIC_THRU_SW;        // len:    1 @ 0x001e, Mic Thru Switch
    u8  MIC_REV_SEND;       // len:    1 @ 0x001f, Mic Reverb Send Level
    u8  MIC_CHO_SEND;       // len:    1 @ 0x0020, Mic Chorus Send Level
    u8  MIC_DLY_SEND;       // len:    1 @ 0x0021, Mic Delay Send Level
    u8  USB_INP_LEVEL;      // len:    1 @ 0x0022, USB Audio Input Level
    u8  USB_OUT_LEVEL;      // len:    1 @ 0x0023, USB Audio Output Level
    u8  LOCAL_SW;           // len:    1 @ 0x0024, Local Switch
    u8  AGING;              // len:    1 @ 0x0025, Aging Warm-Up
    u8  ARP_SET_TEMPO;      // len:    1 @ 0x0026, Arpeggio Set Rhythm Tempo
    u8  ARP_SET_KIT;        // len:    1 @ 0x0027, Arpeggio Set Rhythm Sound
    u8  ARP_SET_TONE;       // len:    1 @ 0x0028, Arpeggio Set Type Sound
    u8  AGING_THERMO;       // len:    1 @ 0x0029, Aging Initial Temperature
    u8  COLOR_SET;          // len:    1 @ 0x002a, Button Color Set
    u8  PADDING1[19];       // len:   19 @ 0x002b, __padding
    u8  LCD_CNT;            // len:    1 @ 0x003e, LCD Contrast
    u8  DEV_ID;             // len:    1 @ 0x003f, Device ID
    u8  SOFT_THRU;          // len:    1 @ 0x0040, Soft Through
    u8  USB_MIDI_THRU;      // len:    1 @ 0x0041, USB-MIDI Thru
    u8  RX_EXC;             // len:    1 @ 0x0042, Receive Exclusive
    u8  TX_EDIT;            // len:    1 @ 0x0043, Transmit Edit Data
    s8  LINE_GAIN;          // len:    1 @ 0x0044, Line Output Gain
    s8  SPEAKER_GAIN;       // len:    1 @ 0x0045, Speaker Output Gain
    u8  AUTO_OFF;           // len:    1 @ 0x0046, Auto Poweroff
    u8  BT_SW;              // len:    1 @ 0x0047, Bluetooth Sw
    u8  BT_ID;              // len:    1 @ 0x0048, Bluetooth ID
    u8  APLAY_LVL;          // len:    1 @ 0x0049, Audio Player Level
    u8  USB_DRIVER;         // len:    1 @ 0x004a, USB Driver Select
    u8  SYNC_MODE;          // len:    1 @ 0x004b, Sync Mode
    u8  SYNC_OUT;           // len:    1 @ 0x004c, Sync Out
    s8  MIC_INP_GAIN;       // len:    1 @ 0x004d, Mic Input Gain
    u8  MIC_POWER;          // len:    1 @ 0x004e, Mic Plug-In Power
    u8  ANLG_INP_LEVEL;     // len:    1 @ 0x004f, AuxIn/BT Input Level
    u8  SPEAKER_OUT_SW;     // len:    1 @ 0x0050, Speaker Output Switch
    u8  LED_ON_BRIGHT;      // len:    1 @ 0x0051, LED On Brightness
    u8  LED_OFF_BRIGHT;     // len:    1 @ 0x0052, LED Off Brightness
    u8  CTRLER_MODE;        // len:    1 @ 0x0053, Knob Mode
    u8  ARP_SYNC;           // len:    1 @ 0x0054, Arpeggio Sync Start
    u8  CONDITION;          // len:    1 @ 0x0055, Aging Age
    u8  SCENE_STARTUP;      // len:    1 @ 0x0056, Startup Scene
    u8  SCENE_LOCK;         // len:    1 @ 0x0057, Scene Lock
    u8  UA_THRU_USB;        // len:    1 @ 0x0058, USB Audio USB IN Thru
    u8  UA_THRU_AUX;        // len:    1 @ 0x0059, AUXIN USB Audio Thru
    u8  TONE_CC_MAP;        // len:    1 @ 0x005a, Tone CC Map
    u8  PADDING2[9];        // len:    9 @ 0x005b, __padding
} SC;

/* SCMP: System Master Comp */
/* Total length: 24 bytes (0x0018) */
typedef struct SCMP {
    u8 SW;            // len:    1 @ 0x0000, Switch
    u8 LO_ATTACK;     // len:    1 @ 0x0001, Low Attack Time
    u8 LO_RELEASE;    // len:    1 @ 0x0002, Low Release Time
    s8 LO_THRES;      // len:    1 @ 0x0003, Low Threshold
    u8 LO_RATIO;      // len:    1 @ 0x0004, Low Ratio
    u8 LO_KNEE;       // len:    1 @ 0x0005, Low Knee
    s8 LO_GAIN;       // len:    1 @ 0x0006, Low Output Gain
    u8 MI_ATTACK;     // len:    1 @ 0x0007, Mid Attack Time
    u8 MI_RELEASE;    // len:    1 @ 0x0008, Mid Release Time
    s8 MI_THRES;      // len:    1 @ 0x0009, Mid Threshold
    u8 MI_RATIO;      // len:    1 @ 0x000a, Mid Ratio
    u8 MI_KNEE;       // len:    1 @ 0x000b, Mid Knee
    s8 MI_GAIN;       // len:    1 @ 0x000c, Mid Output Gain
    u8 HI_ATTACK;     // len:    1 @ 0x000d, High Attack Time
    u8 HI_RELEASE;    // len:    1 @ 0x000e, High Release Time
    s8 HI_THRES;      // len:    1 @ 0x000f, High Threshold
    u8 HI_RATIO;      // len:    1 @ 0x0010, High Ratio
    u8 HI_KNEE;       // len:    1 @ 0x0011, High Knee
    s8 HI_GAIN;       // len:    1 @ 0x0012, High Output Gain
    u8 LO_SPLIT_FREQ; // len:    1 @ 0x0013, Split Freq Low
    u8 HI_SPLIT_FREQ; // len:    1 @ 0x0014, Split Freq Hi
    u8 PADDING1[3];   // len:    3 @ 0x0015, __padding
} SCMP;

/* SEQ: System Master EQ */
/* Total length: 16 bytes (0x0010) */
typedef struct SEQ {
    s8 IN_GAIN;   // len:    1 @ 0x0000, EQ Input Gain
    s8 LO_GAIN;   // len:    1 @ 0x0001, EQ Low Gain
    s8 MID1_GAIN; // len:    1 @ 0x0002, EQ Mid1 Gain
    s8 MID2_GAIN; // len:    1 @ 0x0003, EQ Mid2 Gain
    s8 MID3_GAIN; // len:    1 @ 0x0004, EQ Mid3 Gain
    s8 HI_GAIN;   // len:    1 @ 0x0005, EQ High Gain
    u8 LO_FREQ;   // len:    1 @ 0x0006, EQ Low Frequency
    u8 MID1_FREQ; // len:    1 @ 0x0007, EQ Mid1 Frequency
    u8 MID2_FREQ; // len:    1 @ 0x0008, EQ Mid2 Frequency
    u8 MID3_FREQ; // len:    1 @ 0x0009, EQ Mid3 Frequency
    u8 HI_FREQ;   // len:    1 @ 0x000a, EQ High Frequency
    u8 MID1_Q;    // len:    1 @ 0x000b, EQ Mid1 Q
    u8 MID2_Q;    // len:    1 @ 0x000c, EQ Mid2 Q
    u8 MID3_Q;    // len:    1 @ 0x000d, EQ Mid3 Q
    u8 SW;        // len:    1 @ 0x000e, EQ Switch
    u8 PADDING1;  // len:    1 @ 0x000f, __padding
} SEQ;

/* SH: System Chorus */
/* Total length: 48 bytes (0x0030) */
typedef struct SH {
    u8  sw;             // len:    1 @ 0x0000, Switch
    u8  choType;        // len:    1 @ 0x0001, Chorus Type
    u8  level;          // len:    1 @ 0x0002, Chorus Level
    u8  PADDING1;       // len:    1 @ 0x0003, __padding
    u8  REV_SEND;       // len:    1 @ 0x0004, Reverb Send Level
    u8  PADDING2[3];    // len:    3 @ 0x0005, __padding
    s16 param_1;        // len:    2 @ 0x0008, Chorus Parameter 1
    u8  reserved_1[38]; // len:   38 @ 0x000a, trailing padding
} SH;

/* SL: System Controller */
/* Total length: 30 bytes (0x001e) */
typedef struct SL {
    u8  TX_PC;          // len:    1 @ 0x0000, Transmit Program Change
    u8  TX_BS;          // len:    1 @ 0x0001, Transmit Bank Select
    u8  KBD_VELO;       // len:    1 @ 0x0002, Keyboard Velocity
    u8  KBD_VCRV;       // len:    1 @ 0x0003, Keyboard Velocity Curve
    s8  KBD_VCRV_OFST;  // len:    1 @ 0x0004, Keyboard Velocity Curve Offset
    u8  KEY_FUNC;       // len:    1 @ 0x0005, Assignable Button(01$) Function
    u8  KEY_MODE;       // len:    1 @ 0x0006, Assignable Button(01$) Mode
    u8  KEY_SRC;        // len:    1 @ 0x0007, Assignable Button Source
    u8  HOLD_PDL_SRC;   // len:    1 @ 0x0008, Hold Pedal Source
    u8  HOLD_PDL_FUNC;  // len:    1 @ 0x0009, Hold Pedal Function
    u8  HOLD_PDL_POLE;  // len:    1 @ 0x000a, Hold Pedal Polarity
    u8  CTRL_PDL_SRC;   // len:    1 @ 0x000b, Ctrl Pedal Source
    u8  CTRL_PDL_FUNC;  // len:    1 @ 0x000c, Ctrl Pedal Function
    u8  SLIDER_SRC;     // len:    1 @ 0x000d, Assignable Slider(01$) Source
    u8  SLIDER_FUNC;    // len:    1 @ 0x000e, Assignable Slider(01$) Function
    u8  WHLBND_SRC;     // len:    1 @ 0x000f, Control Wheel1 Source
    u8  WHLBND_FUNC;    // len:    1 @ 0x0010, Control Wheel1 Function
    u8  WHLMOD_SRC;     // len:    1 @ 0x0011, Control Wheel2 Source
    u8  WHLMOD_FUNC;    // len:    1 @ 0x0012, Control Wheel2 Function
    u8  PARTSW_ASGN_1;  // len:    1 @ 0x0013, Part Button Assign [1]-[5]
    u8  PARTSW_ASGN_1S; // len:    1 @ 0x0014, Part Button Assign SHIFT+[1]-[5]
    u8  reserved_1;     // len:    1 @ 0x0015, implicit padding
    u8  PARTSW_ASGN_2S; // len:    1 @ 0x0016, Part Button Assign SHIFT+[6]-[10]
    u8  reserved_2;     // len:    1 @ 0x0017, implicit padding
    u8  PARTSW_ASGN_3S; // len:    1 @ 0x0018, Part Button Assign SHIFT+[11]-[15]
    u8  AFT_SENS;       // len:    1 @ 0x0019, Aftertouch Sens
    u32 PADDING1;       // len:    4 @ 0x001a, __padding
} SL;

/* STP: Setup */
/* Total length: 92 bytes (0x005c) */
typedef struct STP {
    u8  PERF_BS_MSB;         // len:    1 @ 0x0000, Scene BS MSB (CC# 0)
    u8  PERF_BS_LSB;         // len:    1 @ 0x0001, Scene BS LSB (CC# 32)
    u8  PERF_PC;             // len:    1 @ 0x0002, Scene PC (PC)
    u8  PADDING1;            // len:    1 @ 0x0003, __padding
    u8  CUR_PART;            // len:    1 @ 0x0004, Current Part
    u8  CUR_PTL;             // len:    1 @ 0x0005, Current Tone Partial
    u8  CUR_RHY_PTL;         // len:    1 @ 0x0006, Current Rhythm Partial
    u8  LEVEL;               // len:    1 @ 0x0007, Master Level
    u8  MIC_INP_SW;          // len:    1 @ 0x0008, MIC_INP_SW
    s8  MIC_INP_GAIN;        // len:    1 @ 0x0009, MIC_INP_GAIN
    s8  MIC_VOC_GAIN;        // len:    1 @ 0x000a, Mic to Vocoder Send Gain
    u8  MIC_DRY_LEVEL;       // len:    1 @ 0x000b, Mic Dry Level (Vocoder)
    u8  MIC_REV_SEND;        // len:    1 @ 0x000c, Mic to Reverb Send Level
    u8  MIC_CHO_SEND;        // len:    1 @ 0x000d, Mic to Chorus Send Level
    u8  MIC_DLY_SEND;        // len:    1 @ 0x000e, Mic to Delay Send Level
    u8  SFX_DLY_SEND;        // len:    1 @ 0x000f, SystemFx(OD) Delay Send Level
    s8  OCT_SHIFT;           // len:    1 @ 0x0010, Temp Octave Shift
    s8  KEY_TRANS;           // len:    1 @ 0x0011, Temp keyboard Transpose
    u16 TEMPO;               // len:    2 @ 0x0012, Tempo Master
    u16 TEMPO_DULL;          // len:    2 @ 0x0014, Tempo Dul for EffectSync
    u8  TEMPO_CLKSRC;        // len:    1 @ 0x0016, Tempo Clock Source
    u8  EFCT_TEMPO_SRC;      // len:    1 @ 0x0017, Effect Tempo Source
    u8  APP_MODE;            // len:    1 @ 0x0018, Application mode
    u8  MFX_MODE;            // len:    1 @ 0x0019, MFX Mode
    u8  ANLG_INP_SW;         // len:    1 @ 0x001a, ANLG_INP_SW
    u8  ANLG_INP_LEVEL;      // len:    1 @ 0x001b, ANLG_INP_LEVEL
    u8  ANLG_INP_STEREO;     // len:    1 @ 0x001c, ANLG_INP_STEREO
    u8  MIC_JACK_STATE;      // len:    1 @ 0x001d, MicJackState
    u8  VP770TYPE;           // len:    1 @ 0x001e, VP770Type
    u8  AGING_TIMER_SW;      // len:    1 @ 0x001f, Aging Timer Switch
    u8  AGING_INIT_PHASE;    // len:    1 @ 0x0020, Aging Init Phase
    u8  AGING_THERMO;        // len:    1 @ 0x0021, Aging Thermometer
    u8  AGING_INIT_PIT_OFST; // len:    1 @ 0x0022, AGING_INIT_PIT_OFST
    u8  AGING_AUTO_TUNE_SW;  // len:    1 @ 0x0023, AGING_AUTO_TUNE_SW
    u16 AGING_TIMER;         // len:    2 @ 0x0024, Aging Timer
    u8  AUTO_TUNE_INERTIA;   // len:    1 @ 0x0026, AUTO_TUNE_INERTIA
    u8  AGING_END_PIT_OFST;  // len:    1 @ 0x0027, Aging End Pitch(01$)
    u8  AGING_START_SW;      // len:    1 @ 0x0028, AGING_START_SW
    u8  PADDING2;            // len:    1 @ 0x0029, __padding
    u16 TYPE;                // len:    2 @ 0x002a, TYPE knob
    u16 RHYTHM;              // len:    2 @ 0x002c, RHYTHM knob
    u8  PANEL_MODE;          // len:    1 @ 0x002e, Panel Mode
    u8  KNOB_MFX;            // len:    1 @ 0x002f, Knob Position MFX
    u8  KNOB_DLYTIME;        // len:    1 @ 0x0030, Knob Position DELAY TIME
    u8  KNOB_DLYFDBK;        // len:    1 @ 0x0031, Knob Position DELAY FEEDBACK
    u8  KNOB_REVTIME;        // len:    1 @ 0x0032, Knob Position REVERB TIME
    u8  START_MODE;          // len:    1 @ 0x0033, Start On Beat Mode
    u8  BEBEAT_SW;           // len:    1 @ 0x0034, BeBeatDetect Switch
    u8  BEBEAT_GAIN;         // len:    1 @ 0x0035, BeBeatDetect Gain
    u8  BEBEAT_PON;          // len:    1 @ 0x0036, BeBeatDetect Pon Level
    u8  PADDING3;            // len:    1 @ 0x0037, __padding
    u16 BEBEAT_MIN;          // len:    2 @ 0x0038, BeBeatDetect Min Tempo
    u16 BEBEAT_MAX;          // len:    2 @ 0x003a, BeBeatDetect Max Tempo
    u8  CONDITION;           // len:    1 @ 0x003c, Aging Age
    u8  PNL_EDIT_PART;       // len:    1 @ 0x003d, Panel Edit Part
    u8  VD_REF_TONE;         // len:    1 @ 0x003e, Vocal Designer Copy Ref Tone Command
    u8  VOC_OUT_SEL;         // len:    1 @ 0x003f, Vocoder Output Select
    u8  VOC_CRR_OUT;         // len:    1 @ 0x0040, Vocoder Carrier Output
    u8  PADDING4[3];         // len:    3 @ 0x0041, __padding
    u16 SINE_FREQ;           // len:    2 @ 0x0044, Sine Freq
    u16 SQR_FREQ;            // len:    2 @ 0x0046, Square Freq
    u16 IMP_RATE;            // len:    2 @ 0x0048, Impulse Rate (Hz)
    u16 SINE_LEVEL;          // len:    2 @ 0x004a, Sine Level
    u16 SQR_LEVEL;           // len:    2 @ 0x004c, Square Level
    u16 IMP_LEVEL;           // len:    2 @ 0x004e, Impulse Level
    u16 WHITE_LEVEL;         // len:    2 @ 0x0050, White Level
    s16 DC_LEVEL;            // len:    2 @ 0x0052, DC Level
    u16 OSC_LEV_DAC0L;       // len:    2 @ 0x0054, Osc Level DAC 0L
    u16 OSC_LEV_DAC0R;       // len:    2 @ 0x0056, Osc Level DAC 0R
    u16 OSC_LEV_DAC1L;       // len:    2 @ 0x0058, Osc Level DAC 1L
    u16 OSC_LEV_DAC1R;       // len:    2 @ 0x005a, Osc Level DAC 1R
} STP;

/* SURFACE: model surfaceは仮想パラメータでSysExcからも見せない、 */
/* Total length: 6 bytes (0x0006) */
typedef struct SURFACE {
    u8  surfaceType; // len:    1 @ 0x0000, MODEL Type
    u8  PADDING1[3]; // len:    3 @ 0x0001, __padding
    s16 param;       // len:    2 @ 0x0004, MODEL Parameter $
} SURFACE;

/* SV: System Reverb */
/* Total length: 44 bytes (0x002c) */
typedef struct SV {
    u8  sw;             // len:    1 @ 0x0000, Switch
    u8  revType;        // len:    1 @ 0x0001, Reverb Type
    u8  level;          // len:    1 @ 0x0002, Reverb Level
    u8  PADDING1;       // len:    1 @ 0x0003, __padding
    s16 param_1;        // len:    2 @ 0x0004, Reverb Parameter 1
    u8  reserved_1[38]; // len:   38 @ 0x0006, trailing padding
} SV;

/* TONECOM: ToneCom */
/* Total length: 20 bytes (0x0014) */
typedef struct TONECOM {
    u8  NAME_1;         // len:    1 @ 0x0000, Name 1
    u8  reserved_1[15]; // len:   15 @ 0x0001, implicit padding
    u8  CATEGORY;       // len:    1 @ 0x0010, Category
    u8  RSRV8;          // len:    1 @ 0x0011, Reserved
    u16 RSRV16;         // len:    2 @ 0x0012, Reserved
} TONECOM;

/* TONENAME: ToneName */
/* Total length: 16 bytes (0x0010) */
typedef struct TONENAME {
    u8 NAME_1;         // len:    1 @ 0x0000, Name 1
    u8 reserved_1[15]; // len:   15 @ 0x0001, trailing padding
} TONENAME;

/* TONETYPE: Tone Type */
/* Total length: 4 bytes (0x0004) */
typedef struct TONETYPE {
    u16 TYPE;  // len:    2 @ 0x0000, ToneType
    u16 MODEL; // len:    2 @ 0x0002, Model
} TONETYPE;

/* TWCmn: Block */
/* Total length: 20 bytes (0x0014) */
typedef struct TWCmn {
    u8 TW_EBL;          // len:    1 @ 0x0000, Tonewheel Enable
    u8 UPPER_PART;      // len:    1 @ 0x0001, Upper Part
    u8 LOWER_PART;      // len:    1 @ 0x0002, Lower Part
    u8 PEDAL_PART;      // len:    1 @ 0x0003, Pedal Part
    u8 LEVEL;           // len:    1 @ 0x0004, ToneWheel Part Level
    s8 PIT_FINE;        // len:    1 @ 0x0005, ToneWheel Part Fine Tune
    u8 WHEEL_TYPE;      // len:    1 @ 0x0006, ToneWheel Type
    u8 ON_CLICK;        // len:    1 @ 0x0007, Key On Click Level
    u8 OFF_CLICK;       // len:    1 @ 0x0008, Key Off Click Level
    u8 LEAKAGE_LEVEL;   // len:    1 @ 0x0009, Leakage Level
    u8 PERC_SOFT_LEVEL; // len:    1 @ 0x000a, Percussion Soft Level
    u8 PERC_NORM_LEVEL; // len:    1 @ 0x000b, Percussion Norm Level
    u8 PERC_SLOW_TIME;  // len:    1 @ 0x000c, Percussion Slow Time
    u8 PERC_FAST_TIME;  // len:    1 @ 0x000d, Percussion Fast Time
    u8 PERC_RECHARGE;   // len:    1 @ 0x000e, Percussion Recharge Time
    u8 PERC_HBAR_LEVEL; // len:    1 @ 0x000f, Percussion H.Bar Level
    u8 CTRL_PART;       // len:    1 @ 0x0010, Control Part
    u8 PADDING1[3];     // len:    3 @ 0x0011, __padding
} TWCmn;

/* TWEfct: Block */
/* Total length: 12 bytes (0x000c) */
typedef struct TWEfct {
    u8  BMC_SND_SEL; // len:    1 @ 0x0000, BMC Send Select
    u32 PADDING1;    // len:    4 @ 0x0001, __padding
    u8  VIBCHO_SW;   // len:    1 @ 0x0005, Vibrato Chorus Switch
    u8  VIBCHO_TYPE; // len:    1 @ 0x0006, Vibrato Chorus Type
    u8  EXP_CRV;     // len:    1 @ 0x0007, Organ Expression Curve
    u8  EXP_VAL;     // len:    1 @ 0x0008, Organ Expression Value
    u8  PADDING2[3]; // len:    3 @ 0x0009, __padding
} TWEfct;

/* TWMod: Block */
/* Total length: 28 bytes (0x001c) */
typedef struct TWMod {
    u8  reserved_1[8];  // len:    8 @ 0x0000, implicit padding
    u8  UP_HBAR_1;      // len:    1 @ 0x0008, Upper Harmonic Bar 1'
    u8  reserved_2[8];  // len:    8 @ 0x0009, implicit padding
    u8  LW_HBAR_1;      // len:    1 @ 0x0011, Lower Harmonic Bar 1'
    u8  reserved_3[2];  // len:    2 @ 0x0012, implicit padding
    u8  PERC_SW;        // len:    1 @ 0x0014, Percussion Switch
    u8  PERC_HARM;      // len:    1 @ 0x0015, Percussion Harmonic
    u8  PERC_DECAY;     // len:    1 @ 0x0016, Percussion Decay
    u8  PERC_SOFT;      // len:    1 @ 0x0017, Percussion Soft
    u8  WHEEL_BRAKE;    // len:    1 @ 0x0018, Wheel Brake
    u8  WHEEL_SPEED_UP; // len:    1 @ 0x0019, ToneWheel Speed Up
    u16 PADDING1;       // len:    2 @ 0x001a, __padding
} TWMod;

/* USRDATABLK: User Tone Data Block */
/* Total length: 1 bytes (0x0001) */
typedef struct USRDATABLK {
    u8 BLK; // len:    1 @ 0x0000, DataBlock0(01$)
} USRDATABLK;

/* VIF: Favorite Scene */
/* Total length: 4 bytes (0x0004) */
typedef struct VIF {
    u16 NUM;      // len:    2 @ 0x0000, Favorite Scene Number
    u16 PADDING1; // len:    2 @ 0x0002, __padding
} VIF;

/* Edit: Group */
/* Total length: 80 bytes (0x0050) */
typedef struct Edit {
    EDS     EDS;     // len:    4 @ 0x0000, EDS
    EDLWR   EDLWR;   // len:    8 @ 0x0004, EDLWR
    EDLW    EDLW;    // len:    4 @ 0x000c, EDLW
    EDLFR   EDLFR;   // len:    8 @ 0x0010, EDLFR
    EDLF    EDLF;    // len:    4 @ 0x0018, EDLF
    EDLTR   EDLTR;   // len:    8 @ 0x001c, EDLTR
    EDLT    EDLT;    // len:    4 @ 0x0024, EDLT
    EDVD    EDVD;    // len:    4 @ 0x0028, EDVD
    EDPTIR  EDPTIR;  // len:    4 @ 0x002c, EDPTIR
    EDPTI   EDPTI;   // len:    4 @ 0x0030, EDPTI
    EDSEXZR EDSEXZR; // len:    4 @ 0x0034, EDSEXZR
    EDSEXZ  EDSEXZ;  // len:    4 @ 0x0038, EDSEXZ
    EDLEXZR EDLEXZR; // len:    4 @ 0x003c, EDLEXZR
    EDLEXZ  EDLEXZ;  // len:    4 @ 0x0040, EDLEXZ
    EDWM    EDWM;    // len:    8 @ 0x0044, EDWM
    EDPC    EDPC;    // len:    4 @ 0x004c, EDPC
} Edit;

/* MdlJD800: Group */
/* Total length: 500 bytes (0x01f4) */
typedef struct MdlJD800 {
    MDLJD800COM MDLJD800COM;    // len:   44 @ 0x0000, MDLJD800COM
    MDLJD800PTL MDLJD800PTL[4]; // len:  320 @ 0x002c, MDLJD800PTL
    MFX         MFX;            // len:   84 @ 0x016c, MFX
    MDLJD800FxB MDLJD800FxB;    // len:   32 @ 0x01c0, MDLJD800FxB
    TONECOM     TONECOM;        // len:   20 @ 0x01e0, TONECOM
} MdlJD800;

/* MdlJunoX: Group */
/* Total length: 204 bytes (0x00cc) */
typedef struct MdlJunoX {
    MDLJUNOX MDLJUNOX; // len:  100 @ 0x0000, MDLJUNOX
    MFX      MFX;      // len:   84 @ 0x0064, MFX
    TONECOM  TONECOM;  // len:   20 @ 0x00b8, TONECOM
} MdlJunoX;

/* MdlSynPrm0: Group */
/* Total length: 216 bytes (0x00d8) */
typedef struct MdlSynPrm0 {
    MDLSYN0 MDLSYN0; // len:  112 @ 0x0000, MDLSYN0
    MFX     MFX;     // len:   84 @ 0x0070, MFX
    TONECOM TONECOM; // len:   20 @ 0x00c4, TONECOM
} MdlSynPrm0;

/* ModelCore: Group */
/* Total length: 118 bytes (0x0076) */
typedef struct ModelCore {
    MDLCORE MDLCORE; // len:  112 @ 0x0000, MDLCORE
    SURFACE SURFACE; // len:    6 @ 0x0070, SURFACE
} ModelCore;

/* PartInfo: Group */
/* Total length: 16 bytes (0x0010) */
typedef struct PartInfo {
    TONENAME TONENAME; // len:   16 @ 0x0000, TONENAME
} PartInfo;

/* PCMEX: Group */
/* Total length: 1632 bytes (0x0660) */
typedef struct PCMEX {
    PCMT_CMN PCMT_CMN;    // len:   64 @ 0x0000, PCMT_CMN
    MFX      MFX;         // len:   84 @ 0x0040, MFX
    PCMT_PMT PCMT_PMT;    // len:   52 @ 0x0094, PCMT_PMT
    PCMT_PTL PCMT_PTL[4]; // len:  496 @ 0x00c8, PCMT_PTL
    PTL_PENV PTL_PENV[4]; // len:   96 @ 0x02b8, PTL_PENV
    PTL_FENV PTL_FENV[4]; // len:   96 @ 0x0318, PTL_FENV
    PTL_AENV PTL_AENV[4]; // len:   64 @ 0x0378, PTL_AENV
    PTL_LFO  PTL_LFO[4];  // len:  416 @ 0x03b8, PTL_LFO
    PTL_EQ   PTL_EQ[4];   // len:   64 @ 0x0558, PTL_EQ
    PCMS_CMN PCMS_CMN;    // len:   20 @ 0x0598, PCMS_CMN
    PCMS_PMT PCMS_PMT;    // len:   36 @ 0x05ac, PCMS_PMT
    PCMS_PTL PCMS_PTL[4]; // len:  144 @ 0x05d0, PCMS_PTL
} PCMEX;

/* PCMR: Group */
/* Total length: 3328 bytes (0x0d00) */
typedef struct PCMR {
    PCMR_CMN PCMR_CMN;     // len:   28 @ 0x0000, PCMR_CMN
    MFX      MFX;          // len:   84 @ 0x001c, MFX
    RCMP     RCMP[6];      // len:   48 @ 0x0070, RCMP
    PCMR_PTL PCMR_PTL[88]; // len: 1760 @ 0x00a0, PCMR_PTL
    PTL_EQ   PTL_EQ[88];   // len: 1408 @ 0x0780, PTL_EQ
} PCMR;

/* Perf: Group */
/* Total length: 1920 bytes (0x0780) */
typedef struct Perf {
    FC      FC;             // len:   39 @ 0x0000, FC
    FP      FP[5];          // len:  420 @ 0x0027, FP
    PEQ     PEQ[5];         // len:   60 @ 0x01cb, PEQ
    MFX     MFX[5];         // len:  420 @ 0x0207, MFX
    FZ      FZ[5];          // len:  125 @ 0x03ab, FZ
    u8      reserved_1[48]; // len:   48 @ 0x0428, implicit padding
    SH      SH;             // len:   48 @ 0x0458, SH
    SV      SV;             // len:   44 @ 0x0488, SV
    OD      OD;             // len:    8 @ 0x04b4, OD
    ARPC    ARPC;           // len:   28 @ 0x04bc, ARPC
    ARPP    ARPP[5];        // len:  340 @ 0x04d8, ARPP
    ARPUSER ARPUSER[5];     // len:  340 @ 0x062c, ARPUSER
} Perf;

/* PnlAsgn: Group */
/* Total length: 6 bytes (0x0006) */
typedef struct PnlAsgn {
    PNLFUNC PNLFUNC; // len:    6 @ 0x0000, PNLFUNC
} PnlAsgn;

/* RDTONE: Group */
/* Total length: 20 bytes (0x0014) */
typedef struct RDTONE {
    TONENAME TONENAME; // len:   16 @ 0x0000, TONENAME
    RDAPFX   RDAPFX;   // len:    4 @ 0x0010, RDAPFX
} RDTONE;

/* Sys: Group */
/* Total length: 478 bytes (0x01de) */
typedef struct Sys {
    SC   SC;             // len:  100 @ 0x0000, SC
    SL   SL;             // len:   30 @ 0x0064, SL
    u8   reserved_1[48]; // len:   48 @ 0x0082, implicit padding
    SH   SH;             // len:   48 @ 0x00b2, SH
    SV   SV;             // len:   44 @ 0x00e2, SV
    SEQ  SEQ;            // len:   16 @ 0x010e, SEQ
    SCMP SCMP;           // len:   24 @ 0x011e, SCMP
    MBAS MBAS[16];       // len:  128 @ 0x0136, MBAS
    BCS  BCS[10];        // len:   40 @ 0x01b6, BCS
} Sys;

/* ToneType: Group */
/* Total length: 4 bytes (0x0004) */
typedef struct ToneType {
    TONETYPE TONETYPE; // len:    4 @ 0x0000, TONETYPE
} ToneType;

/* USRTONE: Group */
/* Total length: 16 bytes (0x0010) */
typedef struct USRTONE {
    USRDATABLK USRDATABLK[16]; // len:   16 @ 0x0000, USRDATABLK
} USRTONE;

/* VoDsgn: Group */
/* Total length: 136 bytes (0x0088) */
typedef struct VoDsgn {
    MDLVDN  MDLVDN;  // len:   32 @ 0x0000, MDLVDN
    TONECOM TONECOM; // len:   20 @ 0x0020, TONECOM
    MFX     MFX;     // len:   84 @ 0x0034, MFX
} VoDsgn;

/* VTWM: Group */
/* Total length: 48 bytes (0x0030) */
typedef struct VTWM {
    TWCmn TWCmn; // len:   20 @ 0x0000, TWCmn
    TWMod TWMod; // len:   28 @ 0x0014, TWMod
} VTWM;

/* VTWMEfct: Group */
/* Total length: 12 bytes (0x000c) */
typedef struct VTWMEfct {
    TWEfct TWEfct; // len:   12 @ 0x0000, TWEfct
} VTWMEfct;

#pragma pack(pop)

#endif /* JUNO_GENERATED_H */
